import MatrixMortality

open MatrixMortality

#print axioms terminal_match_iff_tagHaltsFrom
#print axioms nearyPCP_solvable_iff_tagHaltsFrom
#print axioms nearyPCP_primitive_terminal
#print axioms nearyGPCP_solvable_iff_tagHaltsFrom
#print axioms nearyGPCPPlus_solvable_iff_tagHaltsFrom
#print axioms nearyMortalityFamilyInt_mortal_iff_tagHaltsFrom
#print axioms neary_generator_count
#print axioms neary_source_generator_count
#print axioms neary_morphisms_nonerasing
#print axioms NearyArithmeticEnvelope.pcp_solvable_iff_halts
#print axioms NearyArithmeticEnvelope.pcp_primitive_terminal
#print axioms NearyArithmeticEnvelope.gpcp_solvable_iff_halts
#print axioms NearyArithmeticEnvelope.gpcpPlus_solvable_iff_halts
#print axioms NearyArithmeticEnvelope.mortality_iff_halts
#print axioms nearyMortality_ordinary_det_ne_zero
#print axioms nearyMortality_ordinary_upperTriangular
#print axioms nearyMortality_terminal_ne_zero
#print axioms nearyMortality_terminal_rank_eq_one
#print axioms Undecidability.codeHalts_not_computable
#print axioms Undecidability.exists_universalTM2
#print axioms Undecidability.CyclicTag.simulate_reaches
#print axioms Undecidability.CyclicTag.reaches_firing_phase
#print axioms Undecidability.CyclicTag.exists_avoidingReaches_firing_of_run
#print axioms Undecidability.NearyCompiler.read_wholeAppendant_track
#print axioms Undecidability.NearyCompiler.read_next_dataBit
#print axioms Undecidability.NearyCompiler.initialTokens_stable
#print axioms Undecidability.NearyCompiler.read_initialQueue
#print axioms Undecidability.NearyCompiler.read_avoidingReaches
#print axioms Undecidability.NearyCompiler.read_until_firing
#print axioms Undecidability.NearyCompiler.read_to_haltingSeed
#print axioms Undecidability.NearyCompiler.read_exact_firing_to_haltingSeed
#print axioms Undecidability.NearyCompiler.drain_junk_before_haltingSeed
