/- Free-monoid action. -/
import MatrixMortality.WordMorphism

/- Exact linear behavior. -/
import MatrixMortality.ExactBehavior
import MatrixMortality.LinearRepresentation
import MatrixMortality.BoundaryTax

/- Finite-rank repair. -/
import MatrixMortality.InternalSandwich
import MatrixMortality.ReturnFamily
import MatrixMortality.EdgeCompression
import MatrixMortality.TwoPlaneEdges
import MatrixMortality.ReverseEdge
import MatrixMortality.ReturnSquare
import MatrixMortality.ReturnSquareDynamics
import MatrixMortality.ReturnSquareNoGo
import MatrixMortality.ReturnSquareClassification
import MatrixMortality.ReturnSquareTax
import MatrixMortality.ReturnJordan
import MatrixMortality.ReturnConvert
import MatrixMortality.ProjectiveLine
import MatrixMortality.PadicValuation
import MatrixMortality.ReturnGuard
import MatrixMortality.ReturnGuardDynamics
import MatrixMortality.ReturnGuardShift
import MatrixMortality.ReturnGuardGauss
import MatrixMortality.ReturnGuardAddress
import MatrixMortality.ReturnGuardArithmetic
import MatrixMortality.ReturnGuardValuation
import MatrixMortality.ReturnGuardTerminalGate
import MatrixMortality.ReturnGuardQuotient
import MatrixMortality.ReturnGuardIntegralLift
import MatrixMortality.ReturnGuardQuotientCompleteness
import MatrixMortality.ReturnGuardDriftCertificate
import MatrixMortality.ReturnGuardFrame
import MatrixMortality.ReturnGuardGap
import MatrixMortality.ReturnGuardEndpoint
import MatrixMortality.ReturnGuardAdelic
import MatrixMortality.ReturnGuardPumping
import MatrixMortality.ReturnGuardResonance
import MatrixMortality.ReturnGuardCumulative
import MatrixMortality.ReturnGuardContinued
import MatrixMortality.ReturnGuardSmith
import MatrixMortality.ReturnGuardPeriodicity
import MatrixMortality.ReturnGuardFiniteOrbit
import MatrixMortality.ReturnGuardRail
import MatrixMortality.ReturnGuardExamples
import MatrixMortality.ReturnGuardQuotientExamples

/- Finite-controller amalgamation. -/
import MatrixMortality.ControllerPushout
import MatrixMortality.TwoStatePushout

/- Physical context certificates. -/
import MatrixMortality.FullMatrixBehavior

/- Deterministic execution evidence. -/
import MatrixMortality.IndexedExecution
import MatrixMortality.ClosedSubstitution

/- Protected global synchronization. -/
import MatrixMortality.TerminalCompiler
import MatrixMortality.NearyEncoding

/- Computable endpoint reductions. -/
import MatrixMortality.Undecidability.UniversalNeary

/- Source-specific obstructions and finite certificates. -/
import MatrixMortality.MacroIrreducibility
import MatrixMortality.NearyBinaryDefect
import MatrixMortality.NearyPhaseSignature
import MatrixMortality.CHHNPackingRank
import MatrixMortality.PairedBoundaryTax
import MatrixMortality.PairedBinaryFullAlgebra
import MatrixMortality.PrefixFullAlgebra
import MatrixMortality.ScheduledBinaryRank
import MatrixMortality.SchottkyPunctuation
import MatrixMortality.TwoStateObstructions
import MatrixMortality.OverlapQueue
import MatrixMortality.OverlapLag
import MatrixMortality.OverlapLagDecision
import MatrixMortality.ParabolicBlade
import MatrixMortality.ParabolicResidueWall
import MatrixMortality.ParabolicExterior
import MatrixMortality.ParabolicFlag
import MatrixMortality.ParabolicSafeFlag
import MatrixMortality.ParabolicDefect
import MatrixMortality.ParabolicSemanticObstruction
import MatrixMortality.ParabolicIncidence
import MatrixMortality.ParabolicRetuned
import MatrixMortality.ParabolicRetunedBoundary
import MatrixMortality.ParabolicRetunedObstruction
