import MatrixMortality.MixedPrimeRealTrapReturn

/-!
# Guarded upper-run cycle core in the mixed-prime real trap

For every lower depth `n ≥ 7`, middle depth `2 ≤ m ≤ 6`, and upper-run length `r`,
this module constructs a guarded cycle with reverse-branch itinerary `L_n, U₀^r, U₁, M_m`
and shell schedule `0^(r+1), n, m−2`.

The arithmetic core records the four boundary mantissas and every intermediate upper mantissa.
Their interval bounds certify the reverse branches, the orbit identities close the cycle, and
five-adic prefix units keep the entire cycle inside the guarded shell.  Two-adic phase separation
and minimal-period consequences are proved in `MixedPrimeRealTrapUpperCyclePeriods`.
-/

namespace MatrixMortality.MixedPrimeDebt

open PadicValuation
open PeriodicShell

private local instance : Fact (Nat.Prime 5) := ⟨by norm_num⟩

/-- Five-power accumulated by an upper run of the displayed length. -/
def wallOddUpperRunFivePower (runLength : ℕ) : ℕ :=
  5 ^ runLength

/-- Three-power accumulated by an upper run of the displayed length. -/
def wallOddUpperRunThreePower (runLength : ℕ) : ℕ :=
  3 ^ runLength

/-- Positive power gap generated by the upper run. -/
def wallOddUpperRunPowerGap (runLength : ℕ) : ℕ :=
  wallOddUpperRunFivePower runLength - wallOddUpperRunThreePower runLength

private theorem wallOddUpperRunPowerGap_data (runLength : ℕ) :
    wallOddUpperRunPowerGap runLength +
        wallOddUpperRunThreePower runLength =
      wallOddUpperRunFivePower runLength := by
  apply Nat.sub_add_cancel
  exact Nat.pow_le_pow_left (by norm_num) _

/-! ## Exact family -/

/-- Difference between the large-depth three- and two-power scales. -/
def wallOddUpperFamilyLargePowerGap (depth : ℕ) : ℕ :=
  wallOddLargeThreePower depth - wallOddLargeTwoPower depth

/-- Difference between the middle-depth three- and two-power scales. -/
def wallOddUpperFamilyMiddlePowerGap (depth : ℕ) : ℕ :=
  wallOddMiddleThreePower depth - wallOddMiddleTwoPower depth

/-- Common odd half-denominator of the four boundary mantissas. -/
def wallOddUpperFamilyHalfDenominator
    (lowerDepth middleDepth runLength : ℕ) : ℕ :=
  123 * wallOddMiddleThreePower middleDepth *
      wallOddUpperRunFivePower runLength * wallOddLargeThreePower lowerDepth +
    2 * (wallOddMiddleThreePower middleDepth *
        wallOddUpperRunFivePower runLength *
          wallOddUpperFamilyLargePowerGap lowerDepth +
      wallOddLargeTwoPower lowerDepth *
        (wallOddMiddleThreePower middleDepth *
            wallOddUpperRunPowerGap runLength +
          wallOddUpperRunThreePower runLength *
            wallOddUpperFamilyMiddlePowerGap middleDepth))

/-- Numerator of the secondary-wall mantissa. -/
def wallOddUpperFamilyWallNumerator
    (lowerDepth middleDepth runLength : ℕ) : ℕ :=
  wallOddMiddleThreePower middleDepth *
    (225 * wallOddUpperRunFivePower runLength *
        wallOddLargeThreePower lowerDepth +
      wallOddLargeTwoPower lowerDepth *
        (16 * wallOddUpperRunThreePower runLength +
          25 * wallOddUpperRunPowerGap runLength))

/-- Large-depth-free factor of the first odd-phase numerator. -/
def wallOddUpperFamilyFirstOddCore
    (middleDepth runLength : ℕ) : ℕ :=
  wallOddMiddleThreePower middleDepth *
      (80 * wallOddUpperRunThreePower runLength +
        125 * wallOddUpperRunPowerGap runLength) +
    18 * wallOddMiddleTwoPower middleDepth *
      wallOddUpperRunThreePower runLength

/-- Numerator of the first odd-phase mantissa. -/
def wallOddUpperFamilyFirstOddNumerator
    (lowerDepth middleDepth runLength : ℕ) : ℕ :=
  wallOddLargeThreePower lowerDepth *
    wallOddUpperFamilyFirstOddCore middleDepth runLength

/-- Half-numerator of the terminal upper-phase mantissa. -/
def wallOddUpperFamilyLastUpperCore
    (lowerDepth middleDepth runLength : ℕ) : ℕ :=
  wallOddUpperRunFivePower runLength *
      wallOddLargeThreePower lowerDepth *
        (40 * wallOddMiddleThreePower middleDepth +
          9 * wallOddMiddleTwoPower middleDepth) +
    wallOddMiddleTwoPower middleDepth *
      wallOddLargeTwoPower lowerDepth *
        wallOddUpperRunPowerGap runLength

/-- Numerator of the terminal upper-phase mantissa. -/
def wallOddUpperFamilyLastUpperNumerator
    (lowerDepth middleDepth runLength : ℕ) : ℕ :=
  2 * wallOddUpperFamilyLastUpperCore lowerDepth middleDepth runLength

/-- Numerator of the second odd-phase mantissa. -/
def wallOddUpperFamilySecondOddNumerator
    (lowerDepth middleDepth runLength : ℕ) : ℕ :=
  15 * wallOddUpperRunFivePower runLength *
      wallOddLargeThreePower lowerDepth *
        (5 * wallOddMiddleThreePower middleDepth +
          3 * wallOddMiddleTwoPower middleDepth) +
    wallOddMiddleTwoPower middleDepth *
      wallOddLargeTwoPower lowerDepth *
        (2 * wallOddUpperRunThreePower runLength +
          5 * wallOddUpperRunPowerGap runLength)

/-- Normalized mantissa at the secondary-wall phase. -/
def wallOddUpperFamilyWallMantissa
    (lowerDepth middleDepth runLength : ℕ) : ℚ :=
  wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength /
    (2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength)

/-- Normalized mantissa at the lower-depth odd phase. -/
def wallOddUpperFamilyFirstOddMantissa
    (lowerDepth middleDepth runLength : ℕ) : ℚ :=
  wallOddUpperFamilyFirstOddNumerator lowerDepth middleDepth runLength /
    wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength

/-- Normalized mantissa at the terminal upper phase. -/
def wallOddUpperFamilyLastUpperMantissa
    (lowerDepth middleDepth runLength : ℕ) : ℚ :=
  wallOddUpperFamilyLastUpperNumerator lowerDepth middleDepth runLength /
    wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength

/-- Normalized mantissa at the middle-entry odd phase. -/
def wallOddUpperFamilySecondOddMantissa
    (lowerDepth middleDepth runLength : ℕ) : ℚ :=
  wallOddUpperFamilySecondOddNumerator lowerDepth middleDepth runLength /
    wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength

private theorem wallOddUpperFamily_largeTwo_le_largeThree
    {depth : ℕ} (depth_lower : 7 ≤ depth) :
    wallOddLargeTwoPower depth ≤ wallOddLargeThreePower depth := by
  obtain ⟨offset, rfl⟩ := Nat.exists_eq_add_of_le depth_lower
  simp only [wallOddLargeTwoPower, wallOddLargeThreePower]
  have two_exponent : 7 + offset - 1 = 6 + offset := by omega
  have three_exponent : 7 + offset - 3 = 4 + offset := by omega
  rw [two_exponent, three_exponent]
  clear depth_lower two_exponent three_exponent
  induction offset with
  | zero => norm_num
  | succ offset induction =>
      rw [Nat.add_succ, Nat.add_succ, pow_succ, pow_succ]
      exact (Nat.mul_le_mul_right 2 induction).trans
        (Nat.mul_le_mul_left (3 ^ (4 + offset)) (by norm_num))

private theorem wallOddUpperFamily_middleTwo_le_middleThree (depth : ℕ) :
    wallOddMiddleTwoPower depth ≤ wallOddMiddleThreePower depth := by
  simp only [wallOddMiddleTwoPower, wallOddMiddleThreePower]
  exact Nat.pow_le_pow_left (by norm_num) _

private theorem wallOddUpperFamilyLargePowerGap_data
    {depth : ℕ} (depth_lower : 7 ≤ depth) :
    wallOddUpperFamilyLargePowerGap depth + wallOddLargeTwoPower depth =
      wallOddLargeThreePower depth :=
  Nat.sub_add_cancel
    (wallOddUpperFamily_largeTwo_le_largeThree depth_lower)

private theorem wallOddUpperFamilyMiddlePowerGap_data (depth : ℕ) :
    wallOddUpperFamilyMiddlePowerGap depth + wallOddMiddleTwoPower depth =
      wallOddMiddleThreePower depth :=
  Nat.sub_add_cancel (wallOddUpperFamily_middleTwo_le_middleThree depth)

private theorem wallOddUpperFamily_middle_bounds
    {depth : ℕ} (depth_lower : 2 ≤ depth) (depth_upper : depth ≤ 6) :
    4 * wallOddMiddleTwoPower depth < 9 * wallOddMiddleThreePower depth ∧
      10 * wallOddMiddleThreePower depth < 54 * wallOddMiddleTwoPower depth ∧
      5 * wallOddMiddleThreePower depth < 27 * wallOddMiddleTwoPower depth ∧
      9 * wallOddMiddleTwoPower depth ≤ 10 * wallOddMiddleThreePower depth ∧
      2 * wallOddMiddleTwoPower depth < 5 * wallOddMiddleThreePower depth := by
  interval_cases depth <;>
    norm_num [wallOddMiddleTwoPower, wallOddMiddleThreePower]

private theorem wallOddUpperFamily_halfDenominator_data
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    2 * wallOddMiddleTwoPower middleDepth *
          wallOddUpperRunThreePower runLength * wallOddLargeTwoPower lowerDepth <
        125 * wallOddMiddleThreePower middleDepth *
          wallOddUpperRunFivePower runLength * wallOddLargeThreePower lowerDepth ∧
      wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength +
          2 * wallOddMiddleTwoPower middleDepth *
            wallOddUpperRunThreePower runLength * wallOddLargeTwoPower lowerDepth =
        125 * wallOddMiddleThreePower middleDepth *
          wallOddUpperRunFivePower runLength * wallOddLargeThreePower lowerDepth := by
  have q_le_p := wallOddUpperFamily_largeTwo_le_largeThree lowerDepth_lower
  have e_le_r := wallOddUpperFamily_middleTwo_le_middleThree middleDepth
  have g_le_f :
      wallOddUpperRunThreePower runLength ≤ wallOddUpperRunFivePower runLength := by
    exact Nat.pow_le_pow_left (by norm_num) _
  have product_le :
      wallOddMiddleTwoPower middleDepth *
          wallOddUpperRunThreePower runLength * wallOddLargeTwoPower lowerDepth ≤
        wallOddMiddleThreePower middleDepth *
          wallOddUpperRunFivePower runLength * wallOddLargeThreePower lowerDepth :=
    Nat.mul_le_mul (Nat.mul_le_mul e_le_r g_le_f) q_le_p
  have product_pos :
      0 < wallOddMiddleThreePower middleDepth *
        wallOddUpperRunFivePower runLength * wallOddLargeThreePower lowerDepth := by
    simp [wallOddMiddleThreePower, wallOddUpperRunFivePower,
      wallOddLargeThreePower]
  have strict :
      2 * wallOddMiddleTwoPower middleDepth *
          wallOddUpperRunThreePower runLength * wallOddLargeTwoPower lowerDepth <
        125 * wallOddMiddleThreePower middleDepth *
          wallOddUpperRunFivePower runLength * wallOddLargeThreePower lowerDepth := by
    nlinarith
  refine ⟨strict, ?_⟩
  have p_gap_eq := wallOddUpperFamilyLargePowerGap_data lowerDepth_lower
  have r_gap_eq := wallOddUpperFamilyMiddlePowerGap_data middleDepth
  have f_gap_eq := wallOddUpperRunPowerGap_data runLength
  simp only [wallOddUpperFamilyHalfDenominator]
  rw [← p_gap_eq, ← r_gap_eq, ← f_gap_eq]
  ring

private theorem wallOddUpperFamily_halfDenominator_pos
    (lowerDepth middleDepth runLength : ℕ) :
    0 < wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
  have leading_pos :
      0 < 123 * wallOddMiddleThreePower middleDepth *
        wallOddUpperRunFivePower runLength * wallOddLargeThreePower lowerDepth := by
    simp [wallOddMiddleThreePower, wallOddUpperRunFivePower,
      wallOddLargeThreePower]
  simp only [wallOddUpperFamilyHalfDenominator]
  omega

private theorem wallOddUpperFamily_affine_identities
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    5 * wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength =
        9 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength +
          wallOddLargeTwoPower lowerDepth *
            wallOddUpperFamilyFirstOddCore middleDepth runLength ∧
      2 * wallOddUpperRunThreePower runLength *
            wallOddUpperFamilyLastUpperCore lowerDepth middleDepth runLength +
          wallOddUpperRunPowerGap runLength *
            wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength =
        wallOddUpperRunFivePower runLength *
          wallOddUpperFamilyFirstOddNumerator lowerDepth middleDepth runLength ∧
      wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength +
          wallOddUpperFamilySecondOddNumerator lowerDepth middleDepth runLength =
        5 * wallOddUpperFamilyLastUpperCore lowerDepth middleDepth runLength ∧
      wallOddMiddleTwoPower middleDepth *
            wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength +
          3 * wallOddMiddleThreePower middleDepth *
            wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength =
        5 * wallOddMiddleThreePower middleDepth *
          wallOddUpperFamilySecondOddNumerator lowerDepth middleDepth runLength := by
  have p_gap_eq := wallOddUpperFamilyLargePowerGap_data lowerDepth_lower
  have r_gap_eq := wallOddUpperFamilyMiddlePowerGap_data middleDepth
  have f_gap_eq := wallOddUpperRunPowerGap_data runLength
  simp only [wallOddUpperFamilyWallNumerator,
    wallOddUpperFamilyHalfDenominator,
    wallOddUpperFamilyFirstOddCore,
    wallOddUpperFamilyFirstOddNumerator,
    wallOddUpperFamilyLastUpperCore,
    wallOddUpperFamilySecondOddNumerator]
  rw [← p_gap_eq, ← r_gap_eq, ← f_gap_eq]
  constructor
  · ring
  constructor
  · ring
  constructor <;> ring

set_option maxHeartbeats 800000 in
private theorem wallOddUpperFamily_bounds_nat
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth)
    (middleDepth_upper : middleDepth ≤ 6) :
    18 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        10 * wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength ∧
      wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength <
        2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength ∧
      2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        3 * wallOddUpperFamilyFirstOddNumerator lowerDepth middleDepth runLength ∧
      wallOddUpperFamilyFirstOddNumerator lowerDepth middleDepth runLength <
        wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength ∧
      2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        3 * wallOddUpperFamilyLastUpperNumerator lowerDepth middleDepth runLength ∧
      5 * wallOddUpperFamilyLastUpperNumerator lowerDepth middleDepth runLength <
        4 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength ∧
      2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        3 * wallOddUpperFamilySecondOddNumerator lowerDepth middleDepth runLength ∧
      wallOddUpperFamilySecondOddNumerator lowerDepth middleDepth runLength <
        wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
  have identities := wallOddUpperFamily_affine_identities
    (middleDepth := middleDepth) (runLength := runLength) lowerDepth_lower
  have p_gap_eq := wallOddUpperFamilyLargePowerGap_data lowerDepth_lower
  have r_gap_eq := wallOddUpperFamilyMiddlePowerGap_data middleDepth
  have f_gap_eq := wallOddUpperRunPowerGap_data runLength
  have p_gap_eq_rat :
      (wallOddUpperFamilyLargePowerGap lowerDepth : ℚ) +
          wallOddLargeTwoPower lowerDepth =
        wallOddLargeThreePower lowerDepth := by
    exact_mod_cast p_gap_eq
  have r_gap_eq_rat :
      (wallOddUpperFamilyMiddlePowerGap middleDepth : ℚ) +
          wallOddMiddleTwoPower middleDepth =
        wallOddMiddleThreePower middleDepth := by
    exact_mod_cast r_gap_eq
  have f_gap_eq_rat :
      (wallOddUpperRunPowerGap runLength : ℚ) +
          wallOddUpperRunThreePower runLength =
        wallOddUpperRunFivePower runLength := by
    exact_mod_cast f_gap_eq
  have middle_bounds := wallOddUpperFamily_middle_bounds
    middleDepth_lower middleDepth_upper
  have p_gap_nonnegative : 0 ≤ wallOddUpperFamilyLargePowerGap lowerDepth := by
    omega
  have r_gap_nonnegative : 0 ≤ wallOddUpperFamilyMiddlePowerGap middleDepth := by
    omega
  have f_gap_nonnegative : 0 ≤ wallOddUpperRunPowerGap runLength := by omega
  have p_pos : 0 < wallOddLargeThreePower lowerDepth := by
    simp [wallOddLargeThreePower]
  have q_pos : 0 < wallOddLargeTwoPower lowerDepth := by
    simp [wallOddLargeTwoPower]
  have r_pos : 0 < wallOddMiddleThreePower middleDepth := by
    simp [wallOddMiddleThreePower]
  have e_pos : 0 < wallOddMiddleTwoPower middleDepth := by
    simp [wallOddMiddleTwoPower]
  have f_pos : 0 < wallOddUpperRunFivePower runLength := by
    simp [wallOddUpperRunFivePower]
  have g_pos : 0 < wallOddUpperRunThreePower runLength := by
    simp [wallOddUpperRunThreePower]
  have first_core_pos :
      0 < wallOddUpperFamilyFirstOddCore middleDepth runLength := by
    simp only [wallOddUpperFamilyFirstOddCore]
    positivity
  have wall_upper_gap :
      wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength +
          (25 * wallOddMiddleThreePower middleDepth *
              wallOddUpperRunFivePower runLength *
                wallOddUpperFamilyLargePowerGap lowerDepth +
            wallOddUpperRunThreePower runLength *
              wallOddLargeTwoPower lowerDepth *
                (5 * wallOddMiddleTwoPower middleDepth +
                  9 * wallOddUpperFamilyMiddlePowerGap middleDepth)) =
        2 * wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength := by
    simp only [wallOddUpperFamilyWallNumerator,
      wallOddUpperFamilyHalfDenominator]
    rw [← p_gap_eq, ← r_gap_eq, ← f_gap_eq]
    ring
  have first_upper_gap :
      wallOddUpperFamilyFirstOddNumerator lowerDepth middleDepth runLength +
          wallOddUpperRunThreePower runLength *
            (9 * wallOddUpperFamilyLargePowerGap lowerDepth *
                (3 * wallOddMiddleTwoPower middleDepth +
                  5 * wallOddUpperFamilyMiddlePowerGap middleDepth) +
              5 * wallOddLargeTwoPower lowerDepth *
                (5 * wallOddMiddleTwoPower middleDepth +
                  9 * wallOddUpperFamilyMiddlePowerGap middleDepth)) =
        wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength := by
    simp only [wallOddUpperFamilyFirstOddNumerator,
      wallOddUpperFamilyFirstOddCore,
      wallOddUpperFamilyHalfDenominator]
    rw [← p_gap_eq, ← r_gap_eq, ← f_gap_eq]
    ring
  have last_upper_gap :
      5 * wallOddUpperFamilyLastUpperCore lowerDepth middleDepth runLength +
          (5 * wallOddUpperRunFivePower runLength *
              wallOddUpperFamilyLargePowerGap lowerDepth *
                (wallOddMiddleTwoPower middleDepth +
                  10 * wallOddUpperFamilyMiddlePowerGap middleDepth) +
            wallOddLargeTwoPower lowerDepth *
              (50 * wallOddUpperRunFivePower runLength *
                  wallOddUpperFamilyMiddlePowerGap middleDepth +
                wallOddMiddleTwoPower middleDepth *
                  wallOddUpperRunThreePower runLength)) =
        2 * wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength := by
    simp only [wallOddUpperFamilyLastUpperCore,
      wallOddUpperFamilyHalfDenominator]
    rw [← p_gap_eq, ← r_gap_eq, ← f_gap_eq]
    ring
  have wall_lower :
      18 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        10 * wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength := by
    have positive :
        0 < 2 * wallOddLargeTwoPower lowerDepth *
          wallOddUpperFamilyFirstOddCore middleDepth runLength := by positivity
    nlinarith [identities.1]
  have wall_upper :
      wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength <
        2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    have positive : 0 <
        25 * wallOddMiddleThreePower middleDepth *
            wallOddUpperRunFivePower runLength *
              wallOddUpperFamilyLargePowerGap lowerDepth +
          wallOddUpperRunThreePower runLength *
            wallOddLargeTwoPower lowerDepth *
              (5 * wallOddMiddleTwoPower middleDepth +
                9 * wallOddUpperFamilyMiddlePowerGap middleDepth) := by
      positivity
    nlinarith [wall_upper_gap]
  have first_lower :
      2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        3 * wallOddUpperFamilyFirstOddNumerator lowerDepth middleDepth runLength := by
    have middle_gap_rat :
        (0 : ℚ) < 54 * (wallOddMiddleTwoPower middleDepth : ℚ) -
          10 * (wallOddMiddleThreePower middleDepth : ℚ) := by
      apply sub_pos.mpr
      exact_mod_cast middle_bounds.2.1
    have gap_identity :
        (3 : ℚ) * wallOddUpperFamilyFirstOddNumerator
              lowerDepth middleDepth runLength -
            2 * wallOddUpperFamilyHalfDenominator
              lowerDepth middleDepth runLength =
          125 * wallOddMiddleThreePower middleDepth *
              wallOddLargeThreePower lowerDepth *
                wallOddUpperRunPowerGap runLength +
            wallOddUpperRunThreePower runLength *
              (wallOddLargeThreePower lowerDepth *
                  (54 * wallOddMiddleTwoPower middleDepth -
                    10 * wallOddMiddleThreePower middleDepth) +
                4 * wallOddMiddleTwoPower middleDepth *
                  wallOddLargeTwoPower lowerDepth) := by
      simp only [wallOddUpperFamilyFirstOddNumerator,
        wallOddUpperFamilyFirstOddCore,
        wallOddUpperFamilyHalfDenominator]
      push_cast
      rw [← p_gap_eq_rat, ← r_gap_eq_rat, ← f_gap_eq_rat]
      ring
    have positive : (0 : ℚ) <
        125 * wallOddMiddleThreePower middleDepth *
            wallOddLargeThreePower lowerDepth *
              wallOddUpperRunPowerGap runLength +
          wallOddUpperRunThreePower runLength *
            (wallOddLargeThreePower lowerDepth *
                (54 * wallOddMiddleTwoPower middleDepth -
                  10 * wallOddMiddleThreePower middleDepth) +
              4 * wallOddMiddleTwoPower middleDepth *
                wallOddLargeTwoPower lowerDepth) := by
      have second_pos : (0 : ℚ) <
          wallOddUpperRunThreePower runLength *
            (wallOddLargeThreePower lowerDepth *
                (54 * wallOddMiddleTwoPower middleDepth -
                  10 * wallOddMiddleThreePower middleDepth) +
              4 * wallOddMiddleTwoPower middleDepth *
                wallOddLargeTwoPower lowerDepth) := by positivity
      positivity
    exact_mod_cast (show
      (2 : ℚ) * wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength <
        3 * wallOddUpperFamilyFirstOddNumerator
          lowerDepth middleDepth runLength by nlinarith)
  have first_upper :
      wallOddUpperFamilyFirstOddNumerator lowerDepth middleDepth runLength <
        wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    have positive : 0 < wallOddUpperRunThreePower runLength *
        (9 * wallOddUpperFamilyLargePowerGap lowerDepth *
            (3 * wallOddMiddleTwoPower middleDepth +
              5 * wallOddUpperFamilyMiddlePowerGap middleDepth) +
          5 * wallOddLargeTwoPower lowerDepth *
            (5 * wallOddMiddleTwoPower middleDepth +
              9 * wallOddUpperFamilyMiddlePowerGap middleDepth)) := by positivity
    nlinarith [first_upper_gap]
  have last_lower_core :
      wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        3 * wallOddUpperFamilyLastUpperCore lowerDepth middleDepth runLength := by
    have middle_gap_rat :
        (0 : ℚ) < 27 * (wallOddMiddleTwoPower middleDepth : ℚ) -
          5 * (wallOddMiddleThreePower middleDepth : ℚ) := by
      apply sub_pos.mpr
      exact_mod_cast middle_bounds.2.2.1
    have gap_identity :
        (3 : ℚ) * wallOddUpperFamilyLastUpperCore
              lowerDepth middleDepth runLength -
            wallOddUpperFamilyHalfDenominator
              lowerDepth middleDepth runLength =
          wallOddUpperRunFivePower runLength *
              wallOddLargeThreePower lowerDepth *
                (27 * wallOddMiddleTwoPower middleDepth -
                  5 * wallOddMiddleThreePower middleDepth) +
            wallOddMiddleTwoPower middleDepth *
              wallOddLargeTwoPower lowerDepth *
                (2 * wallOddUpperRunThreePower runLength +
                  3 * wallOddUpperRunPowerGap runLength) := by
      simp only [wallOddUpperFamilyLastUpperCore,
        wallOddUpperFamilyHalfDenominator]
      push_cast
      rw [← p_gap_eq_rat, ← r_gap_eq_rat, ← f_gap_eq_rat]
      ring
    have positive : (0 : ℚ) <
        wallOddUpperRunFivePower runLength *
            wallOddLargeThreePower lowerDepth *
              (27 * wallOddMiddleTwoPower middleDepth -
                5 * wallOddMiddleThreePower middleDepth) +
          wallOddMiddleTwoPower middleDepth *
            wallOddLargeTwoPower lowerDepth *
              (2 * wallOddUpperRunThreePower runLength +
                3 * wallOddUpperRunPowerGap runLength) := by positivity
    exact_mod_cast (show
      (wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength : ℚ) <
        3 * wallOddUpperFamilyLastUpperCore lowerDepth middleDepth runLength by
          nlinarith)
  have last_upper_core :
      5 * wallOddUpperFamilyLastUpperCore lowerDepth middleDepth runLength <
        2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    have positive : 0 <
        5 * wallOddUpperRunFivePower runLength *
            wallOddUpperFamilyLargePowerGap lowerDepth *
              (wallOddMiddleTwoPower middleDepth +
                10 * wallOddUpperFamilyMiddlePowerGap middleDepth) +
          wallOddLargeTwoPower lowerDepth *
            (50 * wallOddUpperRunFivePower runLength *
                wallOddUpperFamilyMiddlePowerGap middleDepth +
              wallOddMiddleTwoPower middleDepth *
                wallOddUpperRunThreePower runLength) := by
      have second_pos : 0 < wallOddLargeTwoPower lowerDepth *
          (50 * wallOddUpperRunFivePower runLength *
              wallOddUpperFamilyMiddlePowerGap middleDepth +
            wallOddMiddleTwoPower middleDepth *
              wallOddUpperRunThreePower runLength) := by positivity
      omega
    nlinarith [last_upper_gap]
  have last_lower :
      2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        3 * wallOddUpperFamilyLastUpperNumerator lowerDepth middleDepth runLength := by
    simp only [wallOddUpperFamilyLastUpperNumerator]
    omega
  have last_upper :
      5 * wallOddUpperFamilyLastUpperNumerator lowerDepth middleDepth runLength <
        4 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    simp only [wallOddUpperFamilyLastUpperNumerator]
    omega
  have second_lower :
      2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength <
        3 * wallOddUpperFamilySecondOddNumerator lowerDepth middleDepth runLength := by
    have relation := identities.2.2.1
    omega
  have second_upper :
      wallOddUpperFamilySecondOddNumerator lowerDepth middleDepth runLength <
        wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    have relation := identities.2.2.1
    omega
  exact ⟨wall_lower, wall_upper, first_lower, first_upper,
    last_lower, last_upper, second_lower, second_upper⟩

theorem wallOddUpperFamilyWallMantissa_normalized
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth)
    (middleDepth_upper : middleDepth ≤ 6) :
    9 / 10 < wallOddUpperFamilyWallMantissa
        lowerDepth middleDepth runLength ∧
      wallOddUpperFamilyWallMantissa lowerDepth middleDepth runLength < 1 := by
  have h_pos := wallOddUpperFamily_halfDenominator_pos
    lowerDepth middleDepth runLength
  have h_pos_rat : (0 : ℚ) <
      2 * wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    exact_mod_cast Nat.mul_pos (by norm_num : 0 < 2) h_pos
  have bounds := wallOddUpperFamily_bounds_nat (runLength := runLength)
    lowerDepth_lower middleDepth_lower middleDepth_upper
  constructor
  · rw [wallOddUpperFamilyWallMantissa, lt_div_iff₀ h_pos_rat]
    have lower_rat :
        ((18 * wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength : ℕ) : ℚ) <
            10 * wallOddUpperFamilyWallNumerator
              lowerDepth middleDepth runLength := by
      exact_mod_cast bounds.1
    norm_num at lower_rat ⊢
    nlinarith
  · rw [wallOddUpperFamilyWallMantissa, div_lt_one h_pos_rat]
    exact_mod_cast bounds.2.1

theorem wallOddUpperFamilyFirstOddMantissa_normalized
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth)
    (middleDepth_upper : middleDepth ≤ 6) :
    2 / 3 < wallOddUpperFamilyFirstOddMantissa
        lowerDepth middleDepth runLength ∧
      wallOddUpperFamilyFirstOddMantissa lowerDepth middleDepth runLength < 1 := by
  have h_pos := wallOddUpperFamily_halfDenominator_pos
    lowerDepth middleDepth runLength
  have h_pos_rat : (0 : ℚ) <
      wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    exact_mod_cast h_pos
  have bounds := wallOddUpperFamily_bounds_nat (runLength := runLength)
    lowerDepth_lower middleDepth_lower middleDepth_upper
  constructor
  · rw [wallOddUpperFamilyFirstOddMantissa, lt_div_iff₀ h_pos_rat]
    have lower_rat :
        ((2 * wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength : ℕ) : ℚ) <
            3 * wallOddUpperFamilyFirstOddNumerator
              lowerDepth middleDepth runLength := by
      exact_mod_cast bounds.2.2.1
    norm_num at lower_rat ⊢
    nlinarith
  · rw [wallOddUpperFamilyFirstOddMantissa, div_lt_one h_pos_rat]
    exact_mod_cast bounds.2.2.2.1

theorem wallOddUpperFamilyLastUpperMantissa_upperInterval
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth)
    (middleDepth_upper : middleDepth ≤ 6) :
    2 / 3 < wallOddUpperFamilyLastUpperMantissa
        lowerDepth middleDepth runLength ∧
      wallOddUpperFamilyLastUpperMantissa lowerDepth middleDepth runLength < 4 / 5 := by
  have h_pos := wallOddUpperFamily_halfDenominator_pos
    lowerDepth middleDepth runLength
  have h_pos_rat : (0 : ℚ) <
      wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    exact_mod_cast h_pos
  have bounds := wallOddUpperFamily_bounds_nat (runLength := runLength)
    lowerDepth_lower middleDepth_lower middleDepth_upper
  constructor
  · rw [wallOddUpperFamilyLastUpperMantissa, lt_div_iff₀ h_pos_rat]
    have lower_rat :
        ((2 * wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength : ℕ) : ℚ) <
            3 * wallOddUpperFamilyLastUpperNumerator
              lowerDepth middleDepth runLength := by
      exact_mod_cast bounds.2.2.2.2.1
    norm_num at lower_rat ⊢
    nlinarith
  · rw [wallOddUpperFamilyLastUpperMantissa, div_lt_iff₀ h_pos_rat]
    have upper_rat :
        ((5 * wallOddUpperFamilyLastUpperNumerator
          lowerDepth middleDepth runLength : ℕ) : ℚ) <
            4 * wallOddUpperFamilyHalfDenominator
              lowerDepth middleDepth runLength := by
      exact_mod_cast bounds.2.2.2.2.2.1
    norm_num at upper_rat ⊢
    nlinarith

theorem wallOddUpperFamilySecondOddMantissa_normalized
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth)
    (middleDepth_upper : middleDepth ≤ 6) :
    2 / 3 < wallOddUpperFamilySecondOddMantissa
        lowerDepth middleDepth runLength ∧
      wallOddUpperFamilySecondOddMantissa lowerDepth middleDepth runLength < 1 := by
  have h_pos := wallOddUpperFamily_halfDenominator_pos
    lowerDepth middleDepth runLength
  have h_pos_rat : (0 : ℚ) <
      wallOddUpperFamilyHalfDenominator lowerDepth middleDepth runLength := by
    exact_mod_cast h_pos
  have bounds := wallOddUpperFamily_bounds_nat (runLength := runLength)
    lowerDepth_lower middleDepth_lower middleDepth_upper
  constructor
  · rw [wallOddUpperFamilySecondOddMantissa, lt_div_iff₀ h_pos_rat]
    have lower_rat :
        ((2 * wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength : ℕ) : ℚ) <
            3 * wallOddUpperFamilySecondOddNumerator
              lowerDepth middleDepth runLength := by
      exact_mod_cast bounds.2.2.2.2.2.2.1
    norm_num at lower_rat ⊢
    nlinarith
  · rw [wallOddUpperFamilySecondOddMantissa, div_lt_one h_pos_rat]
    exact_mod_cast bounds.2.2.2.2.2.2.2

theorem wallOddUpperFamilyFirstOdd_eq_lower
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    wallOddUpperFamilyFirstOddMantissa lowerDepth middleDepth runLength =
      (wallOddLargeThreePower lowerDepth : ℚ) /
        wallOddLargeTwoPower lowerDepth *
          (10 * wallOddUpperFamilyWallMantissa
            lowerDepth middleDepth runLength - 9) := by
  have h_pos := wallOddUpperFamily_halfDenominator_pos
    lowerDepth middleDepth runLength
  have h_ne :
      (wallOddUpperFamilyHalfDenominator
        lowerDepth middleDepth runLength : ℚ) ≠ 0 := by
    exact_mod_cast h_pos.ne'
  have q_ne : (wallOddLargeTwoPower lowerDepth : ℚ) ≠ 0 := by
    simp [wallOddLargeTwoPower]
  have identity := (wallOddUpperFamily_affine_identities
    (middleDepth := middleDepth) (runLength := runLength) lowerDepth_lower).1
  have identity_rat :
      (5 : ℚ) * wallOddUpperFamilyWallNumerator
            lowerDepth middleDepth runLength =
        9 * wallOddUpperFamilyHalfDenominator
            lowerDepth middleDepth runLength +
          wallOddLargeTwoPower lowerDepth *
            wallOddUpperFamilyFirstOddCore middleDepth runLength := by
    exact_mod_cast identity
  rw [wallOddUpperFamilyFirstOddMantissa,
    wallOddUpperFamilyFirstOddNumerator,
    wallOddUpperFamilyWallMantissa]
  push_cast
  field_simp
  nlinarith

theorem wallOddUpperFamilyLastUpper_eq_iterate
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    wallOddUpperFamilyLastUpperMantissa lowerDepth middleDepth runLength =
      (wallOddUpperRunFivePower runLength : ℚ) /
          wallOddUpperRunThreePower runLength *
            wallOddUpperFamilyFirstOddMantissa
              lowerDepth middleDepth runLength +
        1 - (wallOddUpperRunFivePower runLength : ℚ) /
          wallOddUpperRunThreePower runLength := by
  have h_pos := wallOddUpperFamily_halfDenominator_pos
    lowerDepth middleDepth runLength
  have h_ne :
      (wallOddUpperFamilyHalfDenominator
        lowerDepth middleDepth runLength : ℚ) ≠ 0 := by
    exact_mod_cast h_pos.ne'
  have g_ne : (wallOddUpperRunThreePower runLength : ℚ) ≠ 0 := by
    simp [wallOddUpperRunThreePower]
  have identity := (wallOddUpperFamily_affine_identities
    (middleDepth := middleDepth) (runLength := runLength) lowerDepth_lower).2.1
  have identity_rat :
      (2 : ℚ) * wallOddUpperRunThreePower runLength *
            wallOddUpperFamilyLastUpperCore lowerDepth middleDepth runLength +
          wallOddUpperRunPowerGap runLength *
            wallOddUpperFamilyHalfDenominator
              lowerDepth middleDepth runLength =
        wallOddUpperRunFivePower runLength *
          wallOddUpperFamilyFirstOddNumerator
            lowerDepth middleDepth runLength := by
    exact_mod_cast identity
  have gap_eq := wallOddUpperRunPowerGap_data runLength
  have gap_eq_rat :
      (wallOddUpperRunPowerGap runLength : ℚ) +
          wallOddUpperRunThreePower runLength =
        wallOddUpperRunFivePower runLength := by
    exact_mod_cast gap_eq
  rw [wallOddUpperFamilyLastUpperMantissa,
    wallOddUpperFamilyLastUpperNumerator,
    wallOddUpperFamilyFirstOddMantissa]
  push_cast
  field_simp
  nlinarith

theorem wallOddUpperFamilySecondOdd_eq_upper
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    wallOddUpperFamilySecondOddMantissa lowerDepth middleDepth runLength =
      (5 * wallOddUpperFamilyLastUpperMantissa
        lowerDepth middleDepth runLength - 2) / 2 := by
  have h_pos := wallOddUpperFamily_halfDenominator_pos
    lowerDepth middleDepth runLength
  have h_ne :
      (wallOddUpperFamilyHalfDenominator
        lowerDepth middleDepth runLength : ℚ) ≠ 0 := by
    exact_mod_cast h_pos.ne'
  have identity := (wallOddUpperFamily_affine_identities
    (middleDepth := middleDepth) (runLength := runLength) lowerDepth_lower).2.2.1
  have identity_rat :
      (wallOddUpperFamilyHalfDenominator
          lowerDepth middleDepth runLength : ℚ) +
        wallOddUpperFamilySecondOddNumerator
          lowerDepth middleDepth runLength =
      5 * wallOddUpperFamilyLastUpperCore
        lowerDepth middleDepth runLength := by
    exact_mod_cast identity
  rw [wallOddUpperFamilySecondOddMantissa,
    wallOddUpperFamilyLastUpperMantissa,
    wallOddUpperFamilyLastUpperNumerator]
  push_cast
  field_simp
  nlinarith

theorem wallOddUpperFamilyWall_eq_middle
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    wallOddUpperFamilyWallMantissa lowerDepth middleDepth runLength =
      (wallOddMiddleThreePower middleDepth : ℚ) /
          (2 * wallOddMiddleTwoPower middleDepth) *
        (5 * wallOddUpperFamilySecondOddMantissa
          lowerDepth middleDepth runLength - 3) := by
  have h_pos := wallOddUpperFamily_halfDenominator_pos
    lowerDepth middleDepth runLength
  have h_ne :
      (wallOddUpperFamilyHalfDenominator
        lowerDepth middleDepth runLength : ℚ) ≠ 0 := by
    exact_mod_cast h_pos.ne'
  have e_ne : (wallOddMiddleTwoPower middleDepth : ℚ) ≠ 0 := by
    simp [wallOddMiddleTwoPower]
  have identity := (wallOddUpperFamily_affine_identities
    (middleDepth := middleDepth) (runLength := runLength) lowerDepth_lower).2.2.2
  have identity_rat :
      (wallOddMiddleTwoPower middleDepth : ℚ) *
            wallOddUpperFamilyWallNumerator lowerDepth middleDepth runLength +
          3 * wallOddMiddleThreePower middleDepth *
            wallOddUpperFamilyHalfDenominator
              lowerDepth middleDepth runLength =
        5 * wallOddMiddleThreePower middleDepth *
          wallOddUpperFamilySecondOddNumerator
            lowerDepth middleDepth runLength := by
    exact_mod_cast identity
  rw [wallOddUpperFamilyWallMantissa,
    wallOddUpperFamilySecondOddMantissa]
  field_simp
  nlinarith

/-- Mantissa at one indexed phase of the zero-wait upper run. -/
def wallOddUpperFamilyUpperMantissa
    (lowerDepth middleDepth runLength index : ℕ) : ℚ :=
  1 - (5 / 3 : ℚ) ^ index *
    (1 - wallOddUpperFamilyFirstOddMantissa
      lowerDepth middleDepth runLength)

theorem wallOddUpperFamilyUpperMantissa_zero
    (lowerDepth middleDepth runLength : ℕ) :
    wallOddUpperFamilyUpperMantissa
      lowerDepth middleDepth runLength 0 =
        wallOddUpperFamilyFirstOddMantissa
          lowerDepth middleDepth runLength := by
  simp [wallOddUpperFamilyUpperMantissa]

theorem wallOddUpperFamilyUpperMantissa_succ
    (lowerDepth middleDepth runLength index : ℕ) :
    wallOddUpperFamilyUpperMantissa
        lowerDepth middleDepth runLength (index + 1) =
      (5 * wallOddUpperFamilyUpperMantissa
        lowerDepth middleDepth runLength index - 2) / 3 := by
  simp only [wallOddUpperFamilyUpperMantissa, pow_add]
  norm_num
  ring

private theorem wallOddUpperRun_powerRatio (runLength : ℕ) :
    (wallOddUpperRunFivePower runLength : ℚ) /
        wallOddUpperRunThreePower runLength =
      (5 / 3 : ℚ) ^ runLength := by
  simp only [wallOddUpperRunFivePower, wallOddUpperRunThreePower,
    Nat.cast_pow, Nat.cast_ofNat, div_pow]

theorem wallOddUpperFamilyUpperMantissa_last
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    wallOddUpperFamilyUpperMantissa
        lowerDepth middleDepth runLength runLength =
      wallOddUpperFamilyLastUpperMantissa
        lowerDepth middleDepth runLength := by
  rw [wallOddUpperFamilyUpperMantissa,
    ← wallOddUpperRun_powerRatio runLength,
    wallOddUpperFamilyLastUpper_eq_iterate lowerDepth_lower]
  ring

private theorem wallOddUpperFamilyUpperMantissa_eq_from_last
    {lowerDepth middleDepth runLength index : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) (index_le : index ≤ runLength) :
    wallOddUpperFamilyUpperMantissa lowerDepth middleDepth runLength index =
      1 - (3 / 5 : ℚ) ^ (runLength - index) *
        (1 - wallOddUpperFamilyLastUpperMantissa
          lowerDepth middleDepth runLength) := by
  have scale_identity :
      (3 / 5 : ℚ) ^ (runLength - index) *
          (5 / 3 : ℚ) ^ runLength =
        (5 / 3 : ℚ) ^ index := by
    obtain ⟨offset, rfl⟩ := Nat.exists_eq_add_of_le index_le
    simp only [Nat.add_sub_cancel_left, pow_add, div_pow]
    field_simp
  rw [wallOddUpperFamilyUpperMantissa,
    wallOddUpperFamilyLastUpper_eq_iterate lowerDepth_lower]
  rw [wallOddUpperRun_powerRatio]
  linear_combination
    (1 - wallOddUpperFamilyFirstOddMantissa
      lowerDepth middleDepth runLength) * scale_identity

theorem wallOddUpperFamilyUpperMantissa_normalized
    {lowerDepth middleDepth runLength index : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth)
    (middleDepth_upper : middleDepth ≤ 6)
    (index_le : index ≤ runLength) :
    2 / 3 < wallOddUpperFamilyUpperMantissa
        lowerDepth middleDepth runLength index ∧
      wallOddUpperFamilyUpperMantissa
        lowerDepth middleDepth runLength index < 1 := by
  have last_bounds := wallOddUpperFamilyLastUpperMantissa_upperInterval
    (runLength := runLength) lowerDepth_lower middleDepth_lower middleDepth_upper
  have representation := wallOddUpperFamilyUpperMantissa_eq_from_last
    (middleDepth := middleDepth) lowerDepth_lower index_le
  have power_pos : 0 < (3 / 5 : ℚ) ^ (runLength - index) := by positivity
  have power_le : (3 / 5 : ℚ) ^ (runLength - index) ≤ 1 :=
    pow_le_one₀ (by norm_num) (by norm_num)
  rw [representation]
  constructor
  · have one_sub_last : 0 <
        1 - wallOddUpperFamilyLastUpperMantissa
          lowerDepth middleDepth runLength := by linarith
    have scaled_le :
        (3 / 5 : ℚ) ^ (runLength - index) *
            (1 - wallOddUpperFamilyLastUpperMantissa
              lowerDepth middleDepth runLength) ≤
          1 * (1 - wallOddUpperFamilyLastUpperMantissa
            lowerDepth middleDepth runLength) :=
      mul_le_mul_of_nonneg_right power_le one_sub_last.le
    linarith
  · have one_sub_last : 0 <
        1 - wallOddUpperFamilyLastUpperMantissa
          lowerDepth middleDepth runLength := by linarith
    exact sub_lt_self 1 (mul_pos power_pos one_sub_last)

theorem wallOddUpperFamilyUpperMantissa_above_fourFifths
    {lowerDepth middleDepth runLength index : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth)
    (middleDepth_upper : middleDepth ≤ 6)
    (index_lt : index < runLength) :
    4 / 5 < wallOddUpperFamilyUpperMantissa
      lowerDepth middleDepth runLength index := by
  have last_bounds := wallOddUpperFamilyLastUpperMantissa_upperInterval
    (runLength := runLength) lowerDepth_lower middleDepth_lower middleDepth_upper
  have representation := wallOddUpperFamilyUpperMantissa_eq_from_last
    (middleDepth := middleDepth) lowerDepth_lower index_lt.le
  have exponent_pos : 0 < runLength - index := Nat.sub_pos_of_lt index_lt
  obtain ⟨offset, exponent_eq⟩ := Nat.exists_eq_succ_of_ne_zero exponent_pos.ne'
  have tail_power_le : (3 / 5 : ℚ) ^ offset ≤ 1 :=
    pow_le_one₀ (by norm_num) (by norm_num)
  have power_le : (3 / 5 : ℚ) ^ (runLength - index) ≤ 3 / 5 := by
    rw [exponent_eq, pow_succ]
    nlinarith [mul_le_mul_of_nonneg_right tail_power_le (by norm_num : (0 : ℚ) ≤ 3 / 5)]
  have one_sub_last :
      0 < 1 - wallOddUpperFamilyLastUpperMantissa
        lowerDepth middleDepth runLength := by linarith
  have last_gap :
      1 - wallOddUpperFamilyLastUpperMantissa
        lowerDepth middleDepth runLength < 1 / 3 := by linarith
  rw [representation]
  have scaled_lt :
      (3 / 5 : ℚ) ^ (runLength - index) *
          (1 - wallOddUpperFamilyLastUpperMantissa
            lowerDepth middleDepth runLength) <
        (3 / 5) * (1 / 3) := by
    calc
      _ ≤ (3 / 5) *
          (1 - wallOddUpperFamilyLastUpperMantissa
            lowerDepth middleDepth runLength) :=
        mul_le_mul_of_nonneg_right power_le one_sub_last.le
      _ < (3 / 5) * (1 / 3) :=
        mul_lt_mul_of_pos_left last_gap (by norm_num)
  norm_num at scaled_lt ⊢
  linarith

theorem realTrapBandPoint_wallOddUpperFamilyFirstOdd_eq_lower
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    realTrapBandPoint lowerDepth
        (wallOddUpperFamilyFirstOddMantissa
          lowerDepth middleDepth runLength) =
      2 * wallOddUpperFamilyWallMantissa
        lowerDepth middleDepth runLength / 9 := by
  have scale_identity :
      (3 / 10 : ℚ) * (2 / 3) ^ lowerDepth *
          ((wallOddLargeThreePower lowerDepth : ℚ) /
            wallOddLargeTwoPower lowerDepth) =
        1 / 45 := by
    obtain ⟨offset, rfl⟩ := Nat.exists_eq_add_of_le lowerDepth_lower
    simp only [wallOddLargeThreePower, wallOddLargeTwoPower]
    have three_exponent : 7 + offset - 3 = 4 + offset := by omega
    have two_exponent : 7 + offset - 1 = 6 + offset := by omega
    rw [three_exponent, two_exponent, pow_add, pow_add, pow_add, div_pow]
    norm_num
    simp only [div_pow]
    field_simp
    ring
  rw [wallOddUpperFamilyFirstOdd_eq_lower lowerDepth_lower]
  simp only [realTrapBandPoint]
  calc
    1 / 5 + 3 / 10 * (2 / 3) ^ lowerDepth *
          ((wallOddLargeThreePower lowerDepth : ℚ) /
            wallOddLargeTwoPower lowerDepth *
              (10 * wallOddUpperFamilyWallMantissa
                lowerDepth middleDepth runLength - 9)) =
        1 / 5 +
          (3 / 10 * (2 / 3) ^ lowerDepth *
            ((wallOddLargeThreePower lowerDepth : ℚ) /
              wallOddLargeTwoPower lowerDepth)) *
                (10 * wallOddUpperFamilyWallMantissa
                  lowerDepth middleDepth runLength - 9) := by ring
    _ = 1 / 5 + 1 / 45 *
          (10 * wallOddUpperFamilyWallMantissa
            lowerDepth middleDepth runLength - 9) := by rw [scale_identity]
    _ = 2 * wallOddUpperFamilyWallMantissa
          lowerDepth middleDepth runLength / 9 := by ring

theorem realTrapBandPoint_wallOddUpperFamilyUpper_succ_eq_upper
    (lowerDepth middleDepth runLength index : ℕ) :
    realTrapBandPoint 0
        (wallOddUpperFamilyUpperMantissa
          lowerDepth middleDepth runLength (index + 1)) =
      wallOddUpperFamilyUpperMantissa
        lowerDepth middleDepth runLength index / 2 := by
  rw [realTrapBandPoint, wallOddUpperFamilyUpperMantissa_succ]
  norm_num
  ring

theorem realTrapBandPoint_wallOddUpperFamilySecondOdd_eq_upper
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth) :
    realTrapBandPoint 1
        (wallOddUpperFamilySecondOddMantissa
          lowerDepth middleDepth runLength) =
      wallOddUpperFamilyLastUpperMantissa
        lowerDepth middleDepth runLength / 2 := by
  rw [realTrapBandPoint,
    wallOddUpperFamilySecondOdd_eq_upper lowerDepth_lower]
  norm_num
  ring

theorem realTrapBandPoint_wallOddUpperFamilyWall_eq_middle
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth) :
    realTrapBandPoint middleDepth
        (wallOddUpperFamilyWallMantissa
          lowerDepth middleDepth runLength) =
      wallOddUpperFamilySecondOddMantissa
        lowerDepth middleDepth runLength / 3 := by
  have scale_identity :
      (3 / 10 : ℚ) * (2 / 3) ^ middleDepth *
          ((wallOddMiddleThreePower middleDepth : ℚ) /
            (2 * wallOddMiddleTwoPower middleDepth)) =
        1 / 15 := by
    obtain ⟨offset, rfl⟩ := Nat.exists_eq_add_of_le middleDepth_lower
    simp only [wallOddMiddleThreePower, wallOddMiddleTwoPower]
    have exponent : 2 + offset - 2 = offset := by omega
    rw [exponent, pow_add, div_pow]
    norm_num
    simp only [div_pow]
    field_simp
    ring
  rw [wallOddUpperFamilyWall_eq_middle lowerDepth_lower]
  simp only [realTrapBandPoint]
  calc
    1 / 5 + 3 / 10 * (2 / 3) ^ middleDepth *
          ((wallOddMiddleThreePower middleDepth : ℚ) /
              (2 * wallOddMiddleTwoPower middleDepth) *
            (5 * wallOddUpperFamilySecondOddMantissa
              lowerDepth middleDepth runLength - 3)) =
        1 / 5 +
          (3 / 10 * (2 / 3) ^ middleDepth *
            ((wallOddMiddleThreePower middleDepth : ℚ) /
              (2 * wallOddMiddleTwoPower middleDepth))) *
                (5 * wallOddUpperFamilySecondOddMantissa
                  lowerDepth middleDepth runLength - 3) := by ring
    _ = 1 / 5 + 1 / 15 *
          (5 * wallOddUpperFamilySecondOddMantissa
            lowerDepth middleDepth runLength - 3) := by rw [scale_identity]
    _ = wallOddUpperFamilySecondOddMantissa
          lowerDepth middleDepth runLength / 3 := by ring

theorem shellRun_replicate_zero (count : ℕ) (state : ℚ) :
    shellRun (List.replicate count 0) state =
      1 / 2 + (3 / 5 : ℚ) ^ count * (state - 1 / 2) := by
  induction count generalizing state with
  | zero =>
      change state = 1 / 2 + (3 / 5 : ℚ) ^ 0 * (state - 1 / 2)
      norm_num
  | succ count induction =>
      rw [List.replicate_succ, shellRun_cons, induction]
      simp only [shellStep, pow_zero, mul_one, pow_succ]
      ring

/-- Chronological shell schedule of the guarded upper-run cycle. -/
def wallOddUpperFamilySchedule
    (lowerDepth middleDepth runLength : ℕ) : List ℕ :=
  List.replicate (runLength + 1) 0 ++ [lowerDepth, middleDepth - 2]

theorem wallOddUpperFamily_zeroPrefix
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth) :
    shellRun (List.replicate (runLength + 1) 0)
        (realTrapBandPoint middleDepth
          (wallOddUpperFamilyWallMantissa
            lowerDepth middleDepth runLength)) =
      wallOddUpperFamilyFirstOddMantissa
        lowerDepth middleDepth runLength / 2 := by
  have inverse_power :
      (3 / 5 : ℚ) ^ runLength * (5 / 3 : ℚ) ^ runLength = 1 := by
    rw [← mul_pow]
    norm_num
  rw [shellRun_replicate_zero,
    realTrapBandPoint_wallOddUpperFamilyWall_eq_middle
      lowerDepth_lower middleDepth_lower,
    wallOddUpperFamilySecondOdd_eq_upper lowerDepth_lower,
    wallOddUpperFamilyLastUpper_eq_iterate lowerDepth_lower,
    wallOddUpperRun_powerRatio]
  rw [pow_succ]
  ring_nf at inverse_power ⊢
  have scaled_inverse :
      wallOddUpperFamilyFirstOddMantissa
            lowerDepth middleDepth runLength *
          (3 / 5 : ℚ) ^ runLength * (5 / 3 : ℚ) ^ runLength =
        wallOddUpperFamilyFirstOddMantissa
          lowerDepth middleDepth runLength := by
    calc
      _ = wallOddUpperFamilyFirstOddMantissa
            lowerDepth middleDepth runLength *
          ((3 / 5 : ℚ) ^ runLength * (5 / 3 : ℚ) ^ runLength) := by ring
      _ = _ := by rw [inverse_power]; ring
  nlinarith [inverse_power, scaled_inverse]

theorem wallOddUpperFamily_cycle
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth) :
    shellRun (wallOddUpperFamilySchedule
        lowerDepth middleDepth runLength)
        (realTrapBandPoint middleDepth
          (wallOddUpperFamilyWallMantissa
            lowerDepth middleDepth runLength)) =
      realTrapBandPoint middleDepth
        (wallOddUpperFamilyWallMantissa
          lowerDepth middleDepth runLength) := by
  rw [wallOddUpperFamilySchedule, shellRun_append,
    wallOddUpperFamily_zeroPrefix lowerDepth_lower middleDepth_lower,
    shellRun_cons, shellStep_upperPredecessor,
    shellRun_cons,
    realTrapBandPoint_wallOddUpperFamilyFirstOdd_eq_lower lowerDepth_lower]
  have closing := shellStep_lowerPredecessor (middleDepth - 2)
    (wallOddUpperFamilyWallMantissa lowerDepth middleDepth runLength)
  rw [Nat.sub_add_cancel middleDepth_lower] at closing
  exact closing

theorem wallOddUpperFamily_middleEntryStep
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth) :
    shellStep 0
        (realTrapBandPoint middleDepth
          (wallOddUpperFamilyWallMantissa
            lowerDepth middleDepth runLength)) =
      realTrapBandPoint 1
        (wallOddUpperFamilySecondOddMantissa
          lowerDepth middleDepth runLength) := by
  rw [realTrapBandPoint_wallOddUpperFamilyWall_eq_middle
    lowerDepth_lower middleDepth_lower]
  simpa using shellStep_middlePredecessor 0
    (wallOddUpperFamilySecondOddMantissa
      lowerDepth middleDepth runLength)

theorem wallOddUpperFamily_upperStep
    (lowerDepth middleDepth runLength index : ℕ) :
    shellStep 0
        (realTrapBandPoint 0
          (wallOddUpperFamilyUpperMantissa
            lowerDepth middleDepth runLength (index + 1))) =
      realTrapBandPoint 0
        (wallOddUpperFamilyUpperMantissa
          lowerDepth middleDepth runLength index) := by
  rw [realTrapBandPoint_wallOddUpperFamilyUpper_succ_eq_upper]
  simpa using shellStep_upperPredecessor 0
    (wallOddUpperFamilyUpperMantissa
      lowerDepth middleDepth runLength index)

theorem wallOddUpperFamily_lowerClosingStep
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth) :
    shellStep (middleDepth - 2)
        (realTrapBandPoint lowerDepth
          (wallOddUpperFamilyFirstOddMantissa
            lowerDepth middleDepth runLength)) =
      realTrapBandPoint middleDepth
        (wallOddUpperFamilyWallMantissa
          lowerDepth middleDepth runLength) := by
  rw [realTrapBandPoint_wallOddUpperFamilyFirstOdd_eq_lower lowerDepth_lower]
  have closing := shellStep_lowerPredecessor (middleDepth - 2)
    (wallOddUpperFamilyWallMantissa lowerDepth middleDepth runLength)
  rw [Nat.sub_add_cancel middleDepth_lower] at closing
  exact closing

private theorem shellRun_fixed_fiveUnit
    {waits : List ℕ} (waits_ne : waits ≠ []) {state : ℚ}
    (fixed : shellRun waits state = state) :
    IsUnit 5 state := by
  have periodic_fixed :
      shellRun waits (shellPeriodicPoint waits) = shellPeriodicPoint waits :=
    (shellPeriodicCycle waits_ne).2.1
  have length_ne : waits.length ≠ ([] : List ℕ).length := by
    have length_positive : 0 < waits.length := List.length_pos_of_ne_nil waits_ne
    simp only [List.length_nil]
    omega
  have slope_ne : shellSlope waits ≠ 1 := by
    have unequal := shellSlope_ne_of_length_ne length_ne
    simpa [shellSlope] using unequal
  have displacement :=
    shellRun_sub_shellRun waits state (shellPeriodicPoint waits)
  rw [fixed, periodic_fixed] at displacement
  have factor_ne : 1 - shellSlope waits ≠ 0 :=
    sub_ne_zero.mpr slope_ne.symm
  have state_eq : state = shellPeriodicPoint waits := by
    apply sub_eq_zero.mp
    apply (mul_eq_zero.mp ?_).resolve_left factor_ne
    nlinarith
  rw [state_eq]
  exact (shellPeriodicCycle waits_ne).1

theorem wallOddUpperFamily_shellPrefixesUnit
    {lowerDepth middleDepth runLength : ℕ}
    (lowerDepth_lower : 7 ≤ lowerDepth)
    (middleDepth_lower : 2 ≤ middleDepth) :
    ∀ front back,
      wallOddUpperFamilySchedule lowerDepth middleDepth runLength =
          front ++ back →
        IsUnit 5
          (shellRun front
            (realTrapBandPoint middleDepth
              (wallOddUpperFamilyWallMantissa
                lowerDepth middleDepth runLength))) := by
  let schedule := wallOddUpperFamilySchedule
    lowerDepth middleDepth runLength
  let state := realTrapBandPoint middleDepth
    (wallOddUpperFamilyWallMantissa lowerDepth middleDepth runLength)
  have schedule_ne : schedule ≠ [] := by
    simp [schedule, wallOddUpperFamilySchedule]
  have fixed : shellRun schedule state = state :=
    wallOddUpperFamily_cycle lowerDepth_lower middleDepth_lower
  apply (shellPrefixesUnit_iff schedule state).2
  rw [fixed]
  exact shellRun_fixed_fiveUnit schedule_ne fixed

end MatrixMortality.MixedPrimeDebt
