import MatrixMortality.ParabolicFirstBZeroOuter
import MatrixMortality.ParabolicFirstBZeroReductionCertificate0
import MatrixMortality.ParabolicFirstBZeroReductionCertificate1
import MatrixMortality.ParabolicFirstBZeroReductionCertificate2
import MatrixMortality.ParabolicFirstBZeroReductionCertificate3
import MatrixMortality.ParabolicFirstBZeroReductionCertificate4
import MatrixMortality.ParabolicFirstBZeroReductionCertificate5
import MatrixMortality.ParabolicFirstBZeroReductionCertificate6
import MatrixMortality.ParabolicFirstBZeroReductionCertificate7
import MatrixMortality.ParabolicFirstBZeroReductionCertificate8
import MatrixMortality.ParabolicFirstBZeroReductionCertificate9
import MatrixMortality.ParabolicFirstBZeroReductionCertificate10
import MatrixMortality.ParabolicFirstBZeroReductionCertificate11
import MatrixMortality.ParabolicFirstBZeroReductionCertificate12
import MatrixMortality.ParabolicFirstBZeroReductionCertificate13
import MatrixMortality.ParabolicFirstBZeroReductionCertificate14
import MatrixMortality.ParabolicFirstBZeroReductionCertificate15
import MatrixMortality.ParabolicFirstBZeroReductionCertificate16

/-!
# Leading-`b` tail reduction shard 17

This file is generated by `scripts/generate-parabolic-first-b-zero-reduction.py`.
-/

namespace MatrixMortality.ParabolicBlade

set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7082
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7082)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7082 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7082)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7082) :
    FirstBZeroTailCandidate 203 7082 j z := by
  by_cases position_small : j < 3
  · have position_bound : j ≤ 2 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7082
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7082 * z =
        firstBTwoTailZNumerator a d 203 7082 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7082 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7082) (firstBLateTailABase 0 7082)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7082 (-1) (firstBLateTailALower 0 0 7082)
        (firstBLateTailABase 0 7082) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7082 z (-1)
        (firstBLateTailALower 0 0 7082) (firstBLateTailABase 0 7082) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 7082
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7082 * z =
        firstBTwoTailZNumerator a d 203 7082 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest 7082 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 7082) (firstBLateTailABase 0 7082)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7082 (-1) (firstBLateTailALower 0 1 7082)
        (firstBLateTailABase 0 7082) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7082 z (-1)
        (firstBLateTailALower 0 1 7082) (firstBLateTailABase 0 7082) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) 7082
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7082 * z =
        firstBTwoTailZNumerator a d 203 7082 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 2 rest 7082 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7082) (firstBLateTailABase 0 7082)
        (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 7082 4 6 1
          (firstBLateTailALower 0 2 7082) (firstBLateTailABase 0 7082) (firstBTwoTailDLower 2)
            (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 7082 4 6 z 1
        (firstBLateTailALower 0 2 7082) (firstBLateTailABase 0 7082) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
      refine ⟨45, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 3 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7082
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7082 * z =
      firstBTwoTailZNumerator a d 203 7082 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 3 j rest 7082 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 3 7082) (firstBLateTailABase 0 7082) 39
      (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7082 0 1 1 (firstBLateTailALower 0 3 7082)
      (firstBLateTailABase 0 7082) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7082 0 z 1
      (firstBLateTailALower 0 3 7082) (firstBLateTailABase 0 7082) 39 (firstBTwoTailDUpper 3)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_7083_7086
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 7083 ≤ y) (y_upper : y ≤ 7086)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (7083 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 7086 := by exact_mod_cast y_upper
  by_cases position_small : j < 3
  · have position_bound : j ≤ 2 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 4 5 1 (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 4 z 1
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
  · have position_bound : 3 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 3 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 3 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
      (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 3)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7087
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7087)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7087 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7087)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7087) :
    FirstBZeroTailCandidate 203 7087 j z := by
  by_cases position_small : j < 3
  · have position_bound : j ≤ 2 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7087
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7087 * z =
        firstBTwoTailZNumerator a d 203 7087 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7087 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7087) (firstBLateTailABase 0 7087)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7087 (-1) (firstBLateTailALower 0 0 7087)
        (firstBLateTailABase 0 7087) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7087 z (-1)
        (firstBLateTailALower 0 0 7087) (firstBLateTailABase 0 7087) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 7087
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7087 * z =
        firstBTwoTailZNumerator a d 203 7087 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest 7087 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 7087) (firstBLateTailABase 0 7087)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7087 (-1) (firstBLateTailALower 0 1 7087)
        (firstBLateTailABase 0 7087) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7087 z (-1)
        (firstBLateTailALower 0 1 7087) (firstBLateTailABase 0 7087) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) 7087
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7087 * z =
        firstBTwoTailZNumerator a d 203 7087 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 2 rest 7087 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7087) (firstBLateTailABase 0 7087)
        (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 7087 3 5 1
          (firstBLateTailALower 0 2 7087) (firstBLateTailABase 0 7087) (firstBTwoTailDLower 2)
            (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 7087 3 5 z 1
        (firstBLateTailALower 0 2 7087) (firstBLateTailABase 0 7087) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
      refine ⟨46, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 3 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7087
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7087 * z =
      firstBTwoTailZNumerator a d 203 7087 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 3 j rest 7087 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 3 7087) (firstBLateTailABase 0 7087) 39
      (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7087 0 1 1 (firstBLateTailALower 0 3 7087)
      (firstBLateTailABase 0 7087) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7087 0 z 1
      (firstBLateTailALower 0 3 7087) (firstBLateTailABase 0 7087) 39 (firstBTwoTailDUpper 3)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_7088_7094
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 7088 ≤ y) (y_upper : y ≤ 7094)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (7088 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 7094 := by exact_mod_cast y_upper
  by_cases position_small : j < 3
  · have position_bound : j ≤ 2 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 3 4 1 (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 3 z 1
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
  · have position_bound : 3 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 3 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 3 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
      (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 3)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7095
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7095)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7095 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7095)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7095) :
    FirstBZeroTailCandidate 203 7095 j z := by
  by_cases position_small : j < 3
  · have position_bound : j ≤ 2 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7095
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7095 * z =
        firstBTwoTailZNumerator a d 203 7095 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7095 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7095) (firstBLateTailABase 0 7095)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7095 (-1) (firstBLateTailALower 0 0 7095)
        (firstBLateTailABase 0 7095) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7095 z (-1)
        (firstBLateTailALower 0 0 7095) (firstBLateTailABase 0 7095) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 7095
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7095 * z =
        firstBTwoTailZNumerator a d 203 7095 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest 7095 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 7095) (firstBLateTailABase 0 7095)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7095 (-1) (firstBLateTailALower 0 1 7095)
        (firstBLateTailABase 0 7095) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7095 z (-1)
        (firstBLateTailALower 0 1 7095) (firstBLateTailABase 0 7095) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) 7095
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7095 * z =
        firstBTwoTailZNumerator a d 203 7095 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 2 rest 7095 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7095) (firstBLateTailABase 0 7095)
        (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 7095 2 4 1
          (firstBLateTailALower 0 2 7095) (firstBLateTailABase 0 7095) (firstBTwoTailDLower 2)
            (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 7095 2 4 z 1
        (firstBLateTailALower 0 2 7095) (firstBLateTailABase 0 7095) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
      refine ⟨47, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 3 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7095
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7095 * z =
      firstBTwoTailZNumerator a d 203 7095 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 3 j rest 7095 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 3 7095) (firstBLateTailABase 0 7095) 39
      (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7095 0 1 1 (firstBLateTailALower 0 3 7095)
      (firstBLateTailABase 0 7095) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7095 0 z 1
      (firstBLateTailALower 0 3 7095) (firstBLateTailABase 0 7095) 39 (firstBTwoTailDUpper 3)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_7096_7111
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 7096 ≤ y) (y_upper : y ≤ 7111)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (7096 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 7111 := by exact_mod_cast y_upper
  by_cases position_small : j < 3
  · have position_bound : j ≤ 2 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 2 3 1 (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 2 z 1
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
  · have position_bound : 3 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 3 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 3 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
      (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 3)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_7112_7157
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 7112 ≤ y) (y_upper : y ≤ 7157)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (7112 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 7157 := by exact_mod_cast y_upper
  by_cases position_small : j < 3
  · have position_bound : j ≤ 2 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 1 2 1 (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 1 z 1
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
  · have position_bound : 3 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 3 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 3 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
      (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 3)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7158
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7158)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7158 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7158)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7158) :
    FirstBZeroTailCandidate 203 7158 j z := by
  by_cases position_small : j < 3
  · have position_bound : j ≤ 2 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7158
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7158 * z =
        firstBTwoTailZNumerator a d 203 7158 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7158 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7158) (firstBLateTailABase 0 7158)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7158 (-1) (firstBLateTailALower 0 0 7158)
        (firstBLateTailABase 0 7158) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7158 z (-1)
        (firstBLateTailALower 0 0 7158) (firstBLateTailABase 0 7158) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 7158
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7158 * z =
        firstBTwoTailZNumerator a d 203 7158 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest 7158 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 7158) (firstBLateTailABase 0 7158)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7158 (-1) (firstBLateTailALower 0 1 7158)
        (firstBLateTailABase 0 7158) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7158 z (-1)
        (firstBLateTailALower 0 1 7158) (firstBLateTailABase 0 7158) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) 7158
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7158 * z =
        firstBTwoTailZNumerator a d 203 7158 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 2 rest 7158 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7158) (firstBLateTailABase 0 7158)
        (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 7158 0 2 1
          (firstBLateTailALower 0 2 7158) (firstBLateTailABase 0 7158) (firstBTwoTailDLower 2)
            (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 7158 0 2 z 1
        (firstBLateTailALower 0 2 7158) (firstBLateTailABase 0 7158) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
      refine ⟨48, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 3 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7158
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7158 * z =
      firstBTwoTailZNumerator a d 203 7158 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 3 j rest 7158 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 3 7158) (firstBLateTailABase 0 7158) 39
      (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7158 0 1 1 (firstBLateTailALower 0 3 7158)
      (firstBLateTailABase 0 7158) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7158 0 z 1
      (firstBLateTailALower 0 3 7158) (firstBLateTailABase 0 7158) 39 (firstBTwoTailDUpper 3)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_7159_7294
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 7159 ≤ y) (y_upper : y ≤ 7294)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (7159 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 7294 := by exact_mod_cast y_upper
  by_cases position_small : j < 2
  · have position_bound : j ≤ 1 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
  · have position_bound : 2 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 2 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 2 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
      (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 2)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7295
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7295)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7295 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7295)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7295) :
    FirstBZeroTailCandidate 203 7295 j z := by
  by_cases position_small : j < 2
  · have position_bound : j ≤ 1 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7295
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7295 * z =
        firstBTwoTailZNumerator a d 203 7295 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7295 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7295) (firstBLateTailABase 0 7295)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7295 (-1) (firstBLateTailALower 0 0 7295)
        (firstBLateTailABase 0 7295) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7295 z (-1)
        (firstBLateTailALower 0 0 7295) (firstBLateTailABase 0 7295) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · refine ⟨49, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 2 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7295
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7295 * z =
      firstBTwoTailZNumerator a d 203 7295 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 2 j rest 7295 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7295) (firstBLateTailABase 0 7295) 39
      (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7295 0 1 1 (firstBLateTailALower 0 2 7295)
      (firstBLateTailABase 0 7295) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7295 0 z 1
      (firstBLateTailALower 0 2 7295) (firstBLateTailABase 0 7295) 39 (firstBTwoTailDUpper 2)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7296
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7296)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7296 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7296)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7296) :
    FirstBZeroTailCandidate 203 7296 j z := by
  by_cases position_small : j < 2
  · have position_bound : j ≤ 1 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7296
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7296 * z =
        firstBTwoTailZNumerator a d 203 7296 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7296 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7296) (firstBLateTailABase 0 7296)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7296 (-1) (firstBLateTailALower 0 0 7296)
        (firstBLateTailABase 0 7296) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7296 z (-1)
        (firstBLateTailALower 0 0 7296) (firstBLateTailABase 0 7296) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · refine ⟨50, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 2 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7296
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7296 * z =
      firstBTwoTailZNumerator a d 203 7296 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 2 j rest 7296 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7296) (firstBLateTailABase 0 7296) 39
      (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7296 0 1 1 (firstBLateTailALower 0 2 7296)
      (firstBLateTailABase 0 7296) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7296 0 z 1
      (firstBLateTailALower 0 2 7296) (firstBLateTailABase 0 7296) 39 (firstBTwoTailDUpper 2)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7297
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7297)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7297 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7297)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7297) :
    FirstBZeroTailCandidate 203 7297 j z := by
  by_cases position_small : j < 2
  · have position_bound : j ≤ 1 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7297
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7297 * z =
        firstBTwoTailZNumerator a d 203 7297 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7297 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7297) (firstBLateTailABase 0 7297)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7297 (-1) (firstBLateTailALower 0 0 7297)
        (firstBLateTailABase 0 7297) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7297 z (-1)
        (firstBLateTailALower 0 0 7297) (firstBLateTailABase 0 7297) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 7297
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7297 * z =
        firstBTwoTailZNumerator a d 203 7297 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 1 rest 7297 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 7297) (firstBLateTailABase 0 7297)
        (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 7297 46 159 1
          (firstBLateTailALower 0 1 7297) (firstBLateTailABase 0 7297) (firstBTwoTailDLower 1)
            (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 7297 46 159 z 1
        (firstBLateTailALower 0 1 7297) (firstBLateTailABase 0 7297) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
      refine ⟨51, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 2 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7297
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7297 * z =
      firstBTwoTailZNumerator a d 203 7297 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 2 j rest 7297 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7297) (firstBLateTailABase 0 7297) 39
      (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7297 0 1 1 (firstBLateTailALower 0 2 7297)
      (firstBLateTailABase 0 7297) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7297 0 z 1
      (firstBLateTailALower 0 2 7297) (firstBLateTailABase 0 7297) 39 (firstBTwoTailDUpper 2)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7298
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7298)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7298 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7298)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7298) :
    FirstBZeroTailCandidate 203 7298 j z := by
  by_cases position_small : j < 2
  · have position_bound : j ≤ 1 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7298
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7298 * z =
        firstBTwoTailZNumerator a d 203 7298 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7298 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7298) (firstBLateTailABase 0 7298)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7298 (-1) (firstBLateTailALower 0 0 7298)
        (firstBLateTailABase 0 7298) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7298 z (-1)
        (firstBLateTailALower 0 0 7298) (firstBLateTailABase 0 7298) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 7298
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7298 * z =
        firstBTwoTailZNumerator a d 203 7298 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 1 rest 7298 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 7298) (firstBLateTailABase 0 7298)
        (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 7298 32 66 1
          (firstBLateTailALower 0 1 7298) (firstBLateTailABase 0 7298) (firstBTwoTailDLower 1)
            (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 7298 32 66 z 1
        (firstBLateTailALower 0 1 7298) (firstBLateTailABase 0 7298) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
      refine ⟨52, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 2 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7298
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7298 * z =
      firstBTwoTailZNumerator a d 203 7298 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 2 j rest 7298 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7298) (firstBLateTailABase 0 7298) 39
      (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7298 0 1 1 (firstBLateTailALower 0 2 7298)
      (firstBLateTailABase 0 7298) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7298 0 z 1
      (firstBLateTailALower 0 2 7298) (firstBLateTailABase 0 7298) 39 (firstBTwoTailDUpper 2)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7299
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7299)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7299 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7299)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7299) :
    FirstBZeroTailCandidate 203 7299 j z := by
  by_cases position_small : j < 2
  · have position_bound : j ≤ 1 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7299
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7299 * z =
        firstBTwoTailZNumerator a d 203 7299 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7299 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7299) (firstBLateTailABase 0 7299)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7299 (-1) (firstBLateTailALower 0 0 7299)
        (firstBLateTailABase 0 7299) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7299 z (-1)
        (firstBLateTailALower 0 0 7299) (firstBLateTailABase 0 7299) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 7299
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7299 * z =
        firstBTwoTailZNumerator a d 203 7299 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 1 rest 7299 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 7299) (firstBLateTailABase 0 7299)
        (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 7299 25 42 1
          (firstBLateTailALower 0 1 7299) (firstBLateTailABase 0 7299) (firstBTwoTailDLower 1)
            (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 7299 25 42 z 1
        (firstBLateTailALower 0 1 7299) (firstBLateTailABase 0 7299) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
      refine ⟨53, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 2 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7299
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7299 * z =
      firstBTwoTailZNumerator a d 203 7299 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 2 j rest 7299 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7299) (firstBLateTailABase 0 7299) 39
      (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7299 0 1 1 (firstBLateTailALower 0 2 7299)
      (firstBLateTailABase 0 7299) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7299 0 z 1
      (firstBLateTailALower 0 2 7299) (firstBLateTailABase 0 7299) 39 (firstBTwoTailDUpper 2)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_7300
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7300)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7300 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 7300)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 7300) :
    FirstBZeroTailCandidate 203 7300 j z := by
  by_cases position_small : j < 2
  · have position_bound : j ≤ 1 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 7300
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7300 * z =
        firstBTwoTailZNumerator a d 203 7300 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 7300 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 7300) (firstBLateTailABase 0 7300)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 7300 (-1) (firstBLateTailALower 0 0 7300)
        (firstBLateTailABase 0 7300) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 7300 z (-1)
        (firstBLateTailALower 0 0 7300) (firstBLateTailABase 0 7300) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 7300
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 7300 * z =
        firstBTwoTailZNumerator a d 203 7300 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 1 rest 7300 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 7300) (firstBLateTailABase 0 7300)
        (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 7300 20 30 1
          (firstBLateTailALower 0 1 7300) (firstBLateTailABase 0 7300) (firstBTwoTailDLower 1)
            (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 7300 20 30 z 1
        (firstBLateTailALower 0 1 7300) (firstBLateTailABase 0 7300) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
      refine ⟨54, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 2 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 7300
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 7300 * z =
      firstBTwoTailZNumerator a d 203 7300 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 2 j rest 7300 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 2 7300) (firstBLateTailABase 0 7300) 39
      (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 7300 0 1 1 (firstBLateTailALower 0 2 7300)
      (firstBLateTailABase 0 7300) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 7300 0 z 1
      (firstBLateTailALower 0 2 7300) (firstBLateTailABase 0 7300) 39 (firstBTwoTailDUpper 2)
      a d rectangle corners root_eq

end MatrixMortality.ParabolicBlade
