import MatrixMortality.ParabolicFirstBZeroCore

/-!
# Leading-`b` suffix certificate shard 2

This file is generated by
`scripts/generate-parabolic-first-b-zero-suffix.py`.
-/

namespace MatrixMortality.ParabolicBlade

private abbrev SCore := FirstBOneOuterSuffixCore
private abbrev killN := firstBOneOuterSuffixCore_false_of_nonpositive
private abbrev killG := firstBOneOuterSuffixCore_false_of_global
private abbrev killK := firstBOneOuterSuffixCore_false_of_gap
private abbrev kill0 := firstBOneOuterSuffixCore_false_of_nil
private abbrev stepB := firstBOneOuterSuffixCore_cons_b
private abbrev stepC := firstBOneOuterSuffixCore_cons_c
private abbrev hRoot := firstBZeroSuffixH
private abbrev aRoot := firstBZeroScaleCoefficient
private abbrev corr := firstBOneOuterCorrection
private abbrev qRoot := firstBOneOuterQ
private abbrev jRoot := firstBOneOuterJ

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_202_0_1845_6_7
    (body : List TagLetter) (z : Nat) (z_lower : 6 ≤ z)
    (z_upper : z ≤ 7)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 202 1845 z)
      (firstBOneOuterJ 202 1845 z)
      (firstBOneOuterCorrection 202 1845 z)) : False := by
  let H_root : ℤ := hRoot 0 202 1845 z
  let J : ℤ := jRoot 202 1845 z
  let B : ℤ := corr 202 1845 z
  change SCore body H_root J B at core
  have z_lower_int : (6 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 7 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_202_1_1870_0_0
    (body : List TagLetter) (z : Nat) (z_lower : 0 ≤ z)
    (z_upper : z ≤ 0)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 202 1870 z)
      (firstBOneOuterJ 202 1870 z)
      (firstBOneOuterCorrection 202 1870 z)) : False := by
  let H_root : ℤ := hRoot 1 202 1870 z
  let J : ℤ := jRoot 202 1870 z
  let B : ℤ := corr 202 1870 z
  change SCore body H_root J B at core
  have z_lower_int : (0 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 0 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 1 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_202_0_1923_0_0
    (body : List TagLetter) (z : Nat) (z_lower : 0 ≤ z)
    (z_upper : z ≤ 0)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 202 1923 z)
      (firstBOneOuterJ 202 1923 z)
      (firstBOneOuterCorrection 202 1923 z)) : False := by
  let H_root : ℤ := hRoot 0 202 1923 z
  let J : ℤ := jRoot 202 1923 z
  let B : ℤ := corr 202 1923 z
  change SCore body H_root J B at core
  have z_lower_int : (0 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 0 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 0 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_8_6950_1117_1117
    (body : List TagLetter) (z : Nat) (z_lower : 1117 ≤ z)
    (z_upper : z ≤ 1117)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 8 203 6950 z)
      (firstBOneOuterJ 203 6950 z)
      (firstBOneOuterCorrection 203 6950 z)) : False := by
  let H_root : ℤ := hRoot 8 203 6950 z
  let J : ℤ := jRoot 203 6950 z
  let B : ℤ := corr 203 6950 z
  change SCore body H_root J B at core
  have z_lower_int : (1117 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 1117 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  cases tail2 with
                  | nil =>
                      apply kill0 H_cc J B
                      · intro equality
                        norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_cc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_ccb : ℤ := 243 * H_cc - 39 * J
                          have core_ccb : SCore tail3 H_ccb J B := by
                            dsimp [H_ccb]
                            exact stepB tail3 H_cc J B core_cc
                          apply killN tail3 H_ccb J B
                            J_positive B_positive
                          · norm_num [H_ccb, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccb
                      | c =>
                          let H_ccc : ℤ := 3 * H_cc
                          have core_ccc : SCore tail3 H_ccc J B := by
                            dsimp [H_ccc]
                            exact stepC tail3 H_cc J B core_cc
                          apply killK 1 tail3 H_ccc J B
                            J_positive B_positive
                          · norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_8_6950_1118_1119
    (body : List TagLetter) (z : Nat) (z_lower : 1118 ≤ z)
    (z_upper : z ≤ 1119)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 8 203 6950 z)
      (firstBOneOuterJ 203 6950 z)
      (firstBOneOuterCorrection 203 6950 z)) : False := by
  let H_root : ℤ := hRoot 8 203 6950 z
  let J : ℤ := jRoot 203 6950 z
  let B : ℤ := corr 203 6950 z
  change SCore body H_root J B at core
  have z_lower_int : (1118 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 1119 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killG tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_8_6950_1120_1124
    (body : List TagLetter) (z : Nat) (z_lower : 1120 ≤ z)
    (z_upper : z ≤ 1124)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 8 203 6950 z)
      (firstBOneOuterJ 203 6950 z)
      (firstBOneOuterCorrection 203 6950 z)) : False := by
  let H_root : ℤ := hRoot 8 203 6950 z
  let J : ℤ := jRoot 203 6950 z
  let B : ℤ := corr 203 6950 z
  change SCore body H_root J B at core
  have z_lower_int : (1120 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 1124 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_8_6950_1125_1125
    (body : List TagLetter) (z : Nat) (z_lower : 1125 ≤ z)
    (z_upper : z ≤ 1125)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 8 203 6950 z)
      (firstBOneOuterJ 203 6950 z)
      (firstBOneOuterCorrection 203 6950 z)) : False := by
  let H_root : ℤ := hRoot 8 203 6950 z
  let J : ℤ := jRoot 203 6950 z
  let B : ℤ := corr 203 6950 z
  change SCore body H_root J B at core
  have z_lower_int : (1125 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 1125 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_7_6951_128_128
    (body : List TagLetter) (z : Nat) (z_lower : 128 ≤ z)
    (z_upper : z ≤ 128)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 7 203 6951 z)
      (firstBOneOuterJ 203 6951 z)
      (firstBOneOuterCorrection 203 6951 z)) : False := by
  let H_root : ℤ := hRoot 7 203 6951 z
  let J : ℤ := jRoot 203 6951 z
  let B : ℤ := corr 203 6951 z
  change SCore body H_root J B at core
  have z_lower_int : (128 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 128 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_6_6952_114_114
    (body : List TagLetter) (z : Nat) (z_lower : 114 ≤ z)
    (z_upper : z ≤ 114)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 6 203 6952 z)
      (firstBOneOuterJ 203 6952 z)
      (firstBOneOuterCorrection 203 6952 z)) : False := by
  let H_root : ℤ := hRoot 6 203 6952 z
  let J : ℤ := jRoot 203 6952 z
  let B : ℤ := corr 203 6952 z
  change SCore body H_root J B at core
  have z_lower_int : (114 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 114 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_5_6954_573_574
    (body : List TagLetter) (z : Nat) (z_lower : 573 ≤ z)
    (z_upper : z ≤ 574)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 5 203 6954 z)
      (firstBOneOuterJ 203 6954 z)
      (firstBOneOuterCorrection 203 6954 z)) : False := by
  let H_root : ℤ := hRoot 5 203 6954 z
  let J : ℤ := jRoot 203 6954 z
  let B : ℤ := corr 203 6954 z
  change SCore body H_root J B at core
  have z_lower_int : (573 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 574 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  cases tail2 with
                  | nil =>
                      apply kill0 H_cc J B
                      · intro equality
                        norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_cc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_ccb : ℤ := 243 * H_cc - 39 * J
                          have core_ccb : SCore tail3 H_ccb J B := by
                            dsimp [H_ccb]
                            exact stepB tail3 H_cc J B core_cc
                          apply killN tail3 H_ccb J B
                            J_positive B_positive
                          · norm_num [H_ccb, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccb
                      | c =>
                          let H_ccc : ℤ := 3 * H_cc
                          have core_ccc : SCore tail3 H_ccc J B := by
                            dsimp [H_ccc]
                            exact stepC tail3 H_cc J B core_cc
                          cases tail3 with
                          | nil =>
                              apply kill0 H_ccc J B
                              · intro equality
                                norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                                  jRoot] at equality
                                nlinarith
                              · exact core_ccc
                          | cons letter tail4 =>
                              cases letter with
                              | b =>
                                  let H_cccb : ℤ := 243 * H_ccc - 39 * J
                                  have core_cccb : SCore tail4 H_cccb J B := by
                                    dsimp [H_cccb]
                                    exact stepB tail4 H_ccc J B core_ccc
                                  apply killN tail4 H_cccb J B
                                    J_positive B_positive
                                  · norm_num [H_cccb, H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                    corr, qRoot, jRoot]
                                    nlinarith
                                  · exact core_cccb
                              | c =>
                                  let H_cccc : ℤ := 3 * H_ccc
                                  have core_cccc : SCore tail4 H_cccc J B := by
                                    dsimp [H_cccc]
                                    exact stepC tail4 H_ccc J B core_ccc
                                  cases tail4 with
                                  | nil =>
                                      apply kill0 H_cccc J B
                                      · intro equality
                                        norm_num [H_cccc, H_ccc, H_cc, H_c, B, J, H_root, hRoot,
                                          aRoot, corr, qRoot, jRoot] at equality
                                        nlinarith
                                      · exact core_cccc
                                  | cons letter tail5 =>
                                      cases letter with
                                      | b =>
                                          let H_ccccb : ℤ := 243 * H_cccc - 39 * J
                                          have core_ccccb : SCore tail5 H_ccccb J B := by
                                            dsimp [H_ccccb]
                                            exact stepB tail5 H_cccc J B core_cccc
                                          apply killG tail5 H_ccccb J B
                                            J_positive B_positive
                                          · norm_num [H_ccccb, H_cccc, H_ccc, H_cc, H_c, B, J,
                                            H_root, hRoot, aRoot, corr, qRoot, jRoot]
                                            nlinarith
                                          · exact core_ccccb
                                      | c =>
                                          let H_ccccc : ℤ := 3 * H_cccc
                                          have core_ccccc : SCore tail5 H_ccccc J B := by
                                            dsimp [H_ccccc]
                                            exact stepC tail5 H_cccc J B core_cccc
                                          apply killG tail5 H_ccccc J B
                                            J_positive B_positive
                                          · norm_num [H_ccccc, H_cccc, H_ccc, H_cc, H_c, B, J,
                                            H_root, hRoot, aRoot, corr, qRoot, jRoot]
                                            nlinarith
                                          · exact core_ccccc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_5_6954_575_578
    (body : List TagLetter) (z : Nat) (z_lower : 575 ≤ z)
    (z_upper : z ≤ 578)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 5 203 6954 z)
      (firstBOneOuterJ 203 6954 z)
      (firstBOneOuterCorrection 203 6954 z)) : False := by
  let H_root : ℤ := hRoot 5 203 6954 z
  let J : ℤ := jRoot 203 6954 z
  let B : ℤ := corr 203 6954 z
  change SCore body H_root J B at core
  have z_lower_int : (575 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 578 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  cases tail2 with
                  | nil =>
                      apply kill0 H_cc J B
                      · intro equality
                        norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_cc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_ccb : ℤ := 243 * H_cc - 39 * J
                          have core_ccb : SCore tail3 H_ccb J B := by
                            dsimp [H_ccb]
                            exact stepB tail3 H_cc J B core_cc
                          apply killN tail3 H_ccb J B
                            J_positive B_positive
                          · norm_num [H_ccb, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccb
                      | c =>
                          let H_ccc : ℤ := 3 * H_cc
                          have core_ccc : SCore tail3 H_ccc J B := by
                            dsimp [H_ccc]
                            exact stepC tail3 H_cc J B core_cc
                          apply killG tail3 H_ccc J B
                            J_positive B_positive
                          · norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_5_6954_579_591
    (body : List TagLetter) (z : Nat) (z_lower : 579 ≤ z)
    (z_upper : z ≤ 591)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 5 203 6954 z)
      (firstBOneOuterJ 203 6954 z)
      (firstBOneOuterCorrection 203 6954 z)) : False := by
  let H_root : ℤ := hRoot 5 203 6954 z
  let J : ℤ := jRoot 203 6954 z
  let B : ℤ := corr 203 6954 z
  change SCore body H_root J B at core
  have z_lower_int : (579 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 591 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  cases tail2 with
                  | nil =>
                      apply kill0 H_cc J B
                      · intro equality
                        norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_cc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_ccb : ℤ := 243 * H_cc - 39 * J
                          have core_ccb : SCore tail3 H_ccb J B := by
                            dsimp [H_ccb]
                            exact stepB tail3 H_cc J B core_cc
                          apply killG tail3 H_ccb J B
                            J_positive B_positive
                          · norm_num [H_ccb, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccb
                      | c =>
                          let H_ccc : ℤ := 3 * H_cc
                          have core_ccc : SCore tail3 H_ccc J B := by
                            dsimp [H_ccc]
                            exact stepC tail3 H_cc J B core_cc
                          apply killG tail3 H_ccc J B
                            J_positive B_positive
                          · norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_5_6954_592_632
    (body : List TagLetter) (z : Nat) (z_lower : 592 ≤ z)
    (z_upper : z ≤ 632)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 5 203 6954 z)
      (firstBOneOuterJ 203 6954 z)
      (firstBOneOuterCorrection 203 6954 z)) : False := by
  let H_root : ℤ := hRoot 5 203 6954 z
  let J : ℤ := jRoot 203 6954 z
  let B : ℤ := corr 203 6954 z
  change SCore body H_root J B at core
  have z_lower_int : (592 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 632 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killG tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killG tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_5_6954_633_640
    (body : List TagLetter) (z : Nat) (z_lower : 633 ≤ z)
    (z_upper : z ≤ 640)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 5 203 6954 z)
      (firstBOneOuterJ 203 6954 z)
      (firstBOneOuterCorrection 203 6954 z)) : False := by
  let H_root : ℤ := hRoot 5 203 6954 z
  let J : ℤ := jRoot 203 6954 z
  let B : ℤ := corr 203 6954 z
  change SCore body H_root J B at core
  have z_lower_int : (633 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 640 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_5_6955_86_86
    (body : List TagLetter) (z : Nat) (z_lower : 86 ≤ z)
    (z_upper : z ≤ 86)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 5 203 6955 z)
      (firstBOneOuterJ 203 6955 z)
      (firstBOneOuterCorrection 203 6955 z)) : False := by
  let H_root : ℤ := hRoot 5 203 6955 z
  let J : ℤ := jRoot 203 6955 z
  let B : ℤ := corr 203 6955 z
  change SCore body H_root J B at core
  have z_lower_int : (86 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 86 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killK 0 tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_5_6955_87_87
    (body : List TagLetter) (z : Nat) (z_lower : 87 ≤ z)
    (z_upper : z ≤ 87)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 5 203 6955 z)
      (firstBOneOuterJ 203 6955 z)
      (firstBOneOuterCorrection 203 6955 z)) : False := by
  let H_root : ℤ := hRoot 5 203 6955 z
  let J : ℤ := jRoot 203 6955 z
  let B : ℤ := corr 203 6955 z
  change SCore body H_root J B at core
  have z_lower_int : (87 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 87 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_5_6961_14_14
    (body : List TagLetter) (z : Nat) (z_lower : 14 ≤ z)
    (z_upper : z ≤ 14)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 5 203 6961 z)
      (firstBOneOuterJ 203 6961 z)
      (firstBOneOuterCorrection 203 6961 z)) : False := by
  let H_root : ℤ := hRoot 5 203 6961 z
  let J : ℤ := jRoot 203 6961 z
  let B : ℤ := corr 203 6961 z
  change SCore body H_root J B at core
  have z_lower_int : (14 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 14 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killG tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killG tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_4_6962_0_2993
    (body : List TagLetter) (z : Nat) (z_lower : 0 ≤ z)
    (z_upper : z ≤ 2993)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 4 203 6962 z)
      (firstBOneOuterJ 203 6962 z)
      (firstBOneOuterCorrection 203 6962 z)) : False := by
  let H_root : ℤ := hRoot 4 203 6962 z
  let J : ℤ := jRoot 203 6962 z
  let B : ℤ := corr 203 6962 z
  change SCore body H_root J B at core
  have z_lower_int : (0 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 2993 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killN body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_4_6962_2994_2995
    (body : List TagLetter) (z : Nat) (z_lower : 2994 ≤ z)
    (z_upper : z ≤ 2995)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 4 203 6962 z)
      (firstBOneOuterJ 203 6962 z)
      (firstBOneOuterCorrection 203 6962 z)) : False := by
  let H_root : ℤ := hRoot 4 203 6962 z
  let J : ℤ := jRoot 203 6962 z
  let B : ℤ := corr 203 6962 z
  change SCore body H_root J B at core
  have z_lower_int : (2994 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 2995 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  cases tail2 with
                  | nil =>
                      apply kill0 H_cc J B
                      · intro equality
                        norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_cc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_ccb : ℤ := 243 * H_cc - 39 * J
                          have core_ccb : SCore tail3 H_ccb J B := by
                            dsimp [H_ccb]
                            exact stepB tail3 H_cc J B core_cc
                          apply killN tail3 H_ccb J B
                            J_positive B_positive
                          · norm_num [H_ccb, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccb
                      | c =>
                          let H_ccc : ℤ := 3 * H_cc
                          have core_ccc : SCore tail3 H_ccc J B := by
                            dsimp [H_ccc]
                            exact stepC tail3 H_cc J B core_cc
                          cases tail3 with
                          | nil =>
                              apply kill0 H_ccc J B
                              · intro equality
                                norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                                  jRoot] at equality
                                nlinarith
                              · exact core_ccc
                          | cons letter tail4 =>
                              cases letter with
                              | b =>
                                  let H_cccb : ℤ := 243 * H_ccc - 39 * J
                                  have core_cccb : SCore tail4 H_cccb J B := by
                                    dsimp [H_cccb]
                                    exact stepB tail4 H_ccc J B core_ccc
                                  apply killN tail4 H_cccb J B
                                    J_positive B_positive
                                  · norm_num [H_cccb, H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                    corr, qRoot, jRoot]
                                    nlinarith
                                  · exact core_cccb
                              | c =>
                                  let H_cccc : ℤ := 3 * H_ccc
                                  have core_cccc : SCore tail4 H_cccc J B := by
                                    dsimp [H_cccc]
                                    exact stepC tail4 H_ccc J B core_ccc
                                  cases tail4 with
                                  | nil =>
                                      apply kill0 H_cccc J B
                                      · intro equality
                                        norm_num [H_cccc, H_ccc, H_cc, H_c, B, J, H_root, hRoot,
                                          aRoot, corr, qRoot, jRoot] at equality
                                        nlinarith
                                      · exact core_cccc
                                  | cons letter tail5 =>
                                      cases letter with
                                      | b =>
                                          let H_ccccb : ℤ := 243 * H_cccc - 39 * J
                                          have core_ccccb : SCore tail5 H_ccccb J B := by
                                            dsimp [H_ccccb]
                                            exact stepB tail5 H_cccc J B core_cccc
                                          apply killN tail5 H_ccccb J B
                                            J_positive B_positive
                                          · norm_num [H_ccccb, H_cccc, H_ccc, H_cc, H_c, B, J,
                                            H_root, hRoot, aRoot, corr, qRoot, jRoot]
                                            nlinarith
                                          · exact core_ccccb
                                      | c =>
                                          let H_ccccc : ℤ := 3 * H_cccc
                                          have core_ccccc : SCore tail5 H_ccccc J B := by
                                            dsimp [H_ccccc]
                                            exact stepC tail5 H_cccc J B core_cccc
                                          cases tail5 with
                                          | nil =>
                                              apply kill0 H_ccccc J B
                                              · intro equality
                                                norm_num [H_ccccc, H_cccc, H_ccc, H_cc, H_c, B, J,
                                                  H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                                                  equality
                                                nlinarith
                                              · exact core_ccccc
                                          | cons letter tail6 =>
                                              cases letter with
                                              | b =>
                                                  let H_cccccb : ℤ := 243 * H_ccccc - 39 * J
                                                  have core_cccccb : SCore tail6 H_cccccb J B := by
                                                    dsimp [H_cccccb]
                                                    exact stepB tail6 H_ccccc J B core_ccccc
                                                  apply killN tail6 H_cccccb J B
                                                    J_positive B_positive
                                                  · norm_num [H_cccccb, H_ccccc, H_cccc, H_ccc,
                                                    H_cc, H_c, B, J, H_root, hRoot, aRoot, corr,
                                                    qRoot, jRoot]
                                                    nlinarith
                                                  · exact core_cccccb
                                              | c =>
                                                  let H_cccccc : ℤ := 3 * H_ccccc
                                                  have core_cccccc : SCore tail6 H_cccccc J B := by
                                                    dsimp [H_cccccc]
                                                    exact stepC tail6 H_ccccc J B core_ccccc
                                                  cases tail6 with
                                                  | nil =>
                                                      apply kill0 H_cccccc J B
                                                      · intro equality
                                                        norm_num [H_cccccc, H_ccccc, H_cccc, H_ccc,
                                                          H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                                          corr, qRoot, jRoot] at equality
                                                        nlinarith
                                                      · exact core_cccccc
                                                  | cons letter tail7 =>
                                                      cases letter with
                                                      | b =>
                                                          let H_ccccccb : ℤ := 243 * H_cccccc - 39 *
                                                            J
                                                          have core_ccccccb : SCore tail7 H_ccccccb
                                                            J B := by
                                                            dsimp [H_ccccccb]
                                                            exact stepB tail7 H_cccccc J B
                                                              core_cccccc
                                                          apply killN tail7 H_ccccccb J B
                                                            J_positive B_positive
                                                          · norm_num [H_ccccccb, H_cccccc, H_ccccc,
                                                            H_cccc, H_ccc, H_cc, H_c, B, J, H_root,
                                                            hRoot, aRoot, corr, qRoot, jRoot]
                                                            nlinarith
                                                          · exact core_ccccccb
                                                      | c =>
                                                          let H_ccccccc : ℤ := 3 * H_cccccc
                                                          have core_ccccccc : SCore tail7 H_ccccccc
                                                            J B := by
                                                            dsimp [H_ccccccc]
                                                            exact stepC tail7 H_cccccc J B
                                                              core_cccccc
                                                          cases tail7 with
                                                          | nil =>
                                                              apply kill0 H_ccccccc J B
                                                              · intro equality
                                                                norm_num [H_ccccccc, H_cccccc,
                                                                  H_ccccc, H_cccc, H_ccc, H_cc, H_c,
                                                                  B, J, H_root, hRoot, aRoot, corr,
                                                                  qRoot, jRoot] at equality
                                                                nlinarith
                                                              · exact core_ccccccc
                                                          | cons letter tail8 =>
                                                              cases letter with
                                                              | b =>
                                                                  let H_cccccccb : ℤ := 243 *
                                                                    H_ccccccc - 39 * J
                                                                  have core_cccccccb : SCore tail8
                                                                    H_cccccccb J B := by
                                                                    dsimp [H_cccccccb]
                                                                    exact stepB tail8 H_ccccccc J B
                                                                      core_ccccccc
                                                                  apply killN tail8 H_cccccccb J B
                                                                    J_positive B_positive
                                                                  · norm_num [H_cccccccb, H_ccccccc,
                                                                    H_cccccc, H_ccccc, H_cccc,
                                                                    H_ccc, H_cc, H_c, B, J, H_root,
                                                                    hRoot, aRoot, corr, qRoot,
                                                                    jRoot]
                                                                    nlinarith
                                                                  · exact core_cccccccb
                                                              | c =>
                                                                  let H_cccccccc : ℤ := 3 *
                                                                    H_ccccccc
                                                                  have core_cccccccc : SCore tail8
                                                                    H_cccccccc J B := by
                                                                    dsimp [H_cccccccc]
                                                                    exact stepC tail8 H_ccccccc J B
                                                                      core_ccccccc
                                                                  apply killG tail8 H_cccccccc J B
                                                                    J_positive B_positive
                                                                  · norm_num [H_cccccccc, H_ccccccc,
                                                                    H_cccccc, H_ccccc, H_cccc,
                                                                    H_ccc, H_cc, H_c, B, J, H_root,
                                                                    hRoot, aRoot, corr, qRoot,
                                                                    jRoot]
                                                                    nlinarith
                                                                  · exact core_cccccccc

end MatrixMortality.ParabolicBlade
