import MatrixMortality.ParabolicFirstBZeroCore

/-!
# Leading-`b` suffix certificate shard 10

This file is generated by
`scripts/generate-parabolic-first-b-zero-suffix.py`.
-/

namespace MatrixMortality.ParabolicBlade

private abbrev SCore := FirstBOneOuterSuffixCore
private abbrev killN := firstBOneOuterSuffixCore_false_of_nonpositive
private abbrev killG := firstBOneOuterSuffixCore_false_of_global
private abbrev killK := firstBOneOuterSuffixCore_false_of_gap
private abbrev kill0 := firstBOneOuterSuffixCore_false_of_nil
private abbrev stepB := firstBOneOuterSuffixCore_cons_b
private abbrev stepC := firstBOneOuterSuffixCore_cons_c
private abbrev hRoot := firstBZeroSuffixH
private abbrev aRoot := firstBZeroScaleCoefficient
private abbrev corr := firstBOneOuterCorrection
private abbrev qRoot := firstBOneOuterQ
private abbrev jRoot := firstBOneOuterJ

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7313_6_6
    (body : List TagLetter) (z : Nat) (z_lower : 6 ≤ z)
    (z_upper : z ≤ 6)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7313 z)
      (firstBOneOuterJ 203 7313 z)
      (firstBOneOuterCorrection 203 7313 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7313 z
  let J : ℤ := jRoot 203 7313 z
  let B : ℤ := corr 203 7313 z
  change SCore body H_root J B at core
  have z_lower_int : (6 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 6 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killK 0 tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7314_6_6
    (body : List TagLetter) (z : Nat) (z_lower : 6 ≤ z)
    (z_upper : z ≤ 6)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7314 z)
      (firstBOneOuterJ 203 7314 z)
      (firstBOneOuterCorrection 203 7314 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7314 z
  let J : ℤ := jRoot 203 7314 z
  let B : ℤ := corr 203 7314 z
  change SCore body H_root J B at core
  have z_lower_int : (6 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 6 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 0 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7317_5_5
    (body : List TagLetter) (z : Nat) (z_lower : 5 ≤ z)
    (z_upper : z ≤ 5)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7317 z)
      (firstBOneOuterJ 203 7317 z)
      (firstBOneOuterCorrection 203 7317 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7317 z
  let J : ℤ := jRoot 203 7317 z
  let B : ℤ := corr 203 7317 z
  change SCore body H_root J B at core
  have z_lower_int : (5 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 5 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killG tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killG tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7318_5_5
    (body : List TagLetter) (z : Nat) (z_lower : 5 ≤ z)
    (z_upper : z ≤ 5)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7318 z)
      (firstBOneOuterJ 203 7318 z)
      (firstBOneOuterCorrection 203 7318 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7318 z
  let J : ℤ := jRoot 203 7318 z
  let B : ℤ := corr 203 7318 z
  change SCore body H_root J B at core
  have z_lower_int : (5 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 5 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7322_4_4
    (body : List TagLetter) (z : Nat) (z_lower : 4 ≤ z)
    (z_upper : z ≤ 4)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7322 z)
      (firstBOneOuterJ 203 7322 z)
      (firstBOneOuterCorrection 203 7322 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7322 z
  let J : ℤ := jRoot 203 7322 z
  let B : ℤ := corr 203 7322 z
  change SCore body H_root J B at core
  have z_lower_int : (4 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 4 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killK 1 tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7323_4_4
    (body : List TagLetter) (z : Nat) (z_lower : 4 ≤ z)
    (z_upper : z ≤ 4)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7323 z)
      (firstBOneOuterJ 203 7323 z)
      (firstBOneOuterCorrection 203 7323 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7323 z
  let J : ℤ := jRoot 203 7323 z
  let B : ℤ := corr 203 7323 z
  change SCore body H_root J B at core
  have z_lower_int : (4 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 4 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 0 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7331_3_3
    (body : List TagLetter) (z : Nat) (z_lower : 3 ≤ z)
    (z_upper : z ≤ 3)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7331 z)
      (firstBOneOuterJ 203 7331 z)
      (firstBOneOuterCorrection 203 7331 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7331 z
  let J : ℤ := jRoot 203 7331 z
  let B : ℤ := corr 203 7331 z
  change SCore body H_root J B at core
  have z_lower_int : (3 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 3 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killK 0 tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7332_3_3
    (body : List TagLetter) (z : Nat) (z_lower : 3 ≤ z)
    (z_upper : z ≤ 3)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7332 z)
      (firstBOneOuterJ 203 7332 z)
      (firstBOneOuterCorrection 203 7332 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7332 z
  let J : ℤ := jRoot 203 7332 z
  let B : ℤ := corr 203 7332 z
  change SCore body H_root J B at core
  have z_lower_int : (3 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 3 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 0 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7349_2_2
    (body : List TagLetter) (z : Nat) (z_lower : 2 ≤ z)
    (z_upper : z ≤ 2)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7349 z)
      (firstBOneOuterJ 203 7349 z)
      (firstBOneOuterCorrection 203 7349 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7349 z
  let J : ℤ := jRoot 203 7349 z
  let B : ℤ := corr 203 7349 z
  change SCore body H_root J B at core
  have z_lower_int : (2 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 2 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 0 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7398_1_1
    (body : List TagLetter) (z : Nat) (z_lower : 1 ≤ z)
    (z_upper : z ≤ 1)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7398 z)
      (firstBOneOuterJ 203 7398 z)
      (firstBOneOuterCorrection 203 7398 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7398 z
  let J : ℤ := jRoot 203 7398 z
  let B : ℤ := corr 203 7398 z
  change SCore body H_root J B at core
  have z_lower_int : (1 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 1 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 1 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_1_7399_1_1
    (body : List TagLetter) (z : Nat) (z_lower : 1 ≤ z)
    (z_upper : z ≤ 1)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 1 203 7399 z)
      (firstBOneOuterJ 203 7399 z)
      (firstBOneOuterCorrection 203 7399 z)) : False := by
  let H_root : ℤ := hRoot 1 203 7399 z
  let J : ℤ := jRoot 203 7399 z
  let B : ℤ := corr 203 7399 z
  change SCore body H_root J B at core
  have z_lower_int : (1 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 1 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 0 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8095_0_547
    (body : List TagLetter) (z : Nat) (z_lower : 0 ≤ z)
    (z_upper : z ≤ 547)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8095 z)
      (firstBOneOuterJ 203 8095 z)
      (firstBOneOuterCorrection 203 8095 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8095 z
  let J : ℤ := jRoot 203 8095 z
  let B : ℤ := corr 203 8095 z
  change SCore body H_root J B at core
  have z_lower_int : (0 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 547 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killN body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8095_548_548
    (body : List TagLetter) (z : Nat) (z_lower : 548 ≤ z)
    (z_upper : z ≤ 548)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8095 z)
      (firstBOneOuterJ 203 8095 z)
      (firstBOneOuterCorrection 203 8095 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8095 z
  let J : ℤ := jRoot 203 8095 z
  let B : ℤ := corr 203 8095 z
  change SCore body H_root J B at core
  have z_lower_int : (548 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 548 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  cases tail2 with
                  | nil =>
                      apply kill0 H_cc J B
                      · intro equality
                        norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_cc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_ccb : ℤ := 243 * H_cc - 39 * J
                          have core_ccb : SCore tail3 H_ccb J B := by
                            dsimp [H_ccb]
                            exact stepB tail3 H_cc J B core_cc
                          apply killN tail3 H_ccb J B
                            J_positive B_positive
                          · norm_num [H_ccb, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccb
                      | c =>
                          let H_ccc : ℤ := 3 * H_cc
                          have core_ccc : SCore tail3 H_ccc J B := by
                            dsimp [H_ccc]
                            exact stepC tail3 H_cc J B core_cc
                          cases tail3 with
                          | nil =>
                              apply kill0 H_ccc J B
                              · intro equality
                                norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                                  jRoot] at equality
                                nlinarith
                              · exact core_ccc
                          | cons letter tail4 =>
                              cases letter with
                              | b =>
                                  let H_cccb : ℤ := 243 * H_ccc - 39 * J
                                  have core_cccb : SCore tail4 H_cccb J B := by
                                    dsimp [H_cccb]
                                    exact stepB tail4 H_ccc J B core_ccc
                                  apply killN tail4 H_cccb J B
                                    J_positive B_positive
                                  · norm_num [H_cccb, H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                    corr, qRoot, jRoot]
                                    nlinarith
                                  · exact core_cccb
                              | c =>
                                  let H_cccc : ℤ := 3 * H_ccc
                                  have core_cccc : SCore tail4 H_cccc J B := by
                                    dsimp [H_cccc]
                                    exact stepC tail4 H_ccc J B core_ccc
                                  cases tail4 with
                                  | nil =>
                                      apply kill0 H_cccc J B
                                      · intro equality
                                        norm_num [H_cccc, H_ccc, H_cc, H_c, B, J, H_root, hRoot,
                                          aRoot, corr, qRoot, jRoot] at equality
                                        nlinarith
                                      · exact core_cccc
                                  | cons letter tail5 =>
                                      cases letter with
                                      | b =>
                                          let H_ccccb : ℤ := 243 * H_cccc - 39 * J
                                          have core_ccccb : SCore tail5 H_ccccb J B := by
                                            dsimp [H_ccccb]
                                            exact stepB tail5 H_cccc J B core_cccc
                                          apply killN tail5 H_ccccb J B
                                            J_positive B_positive
                                          · norm_num [H_ccccb, H_cccc, H_ccc, H_cc, H_c, B, J,
                                            H_root, hRoot, aRoot, corr, qRoot, jRoot]
                                            nlinarith
                                          · exact core_ccccb
                                      | c =>
                                          let H_ccccc : ℤ := 3 * H_cccc
                                          have core_ccccc : SCore tail5 H_ccccc J B := by
                                            dsimp [H_ccccc]
                                            exact stepC tail5 H_cccc J B core_cccc
                                          cases tail5 with
                                          | nil =>
                                              apply kill0 H_ccccc J B
                                              · intro equality
                                                norm_num [H_ccccc, H_cccc, H_ccc, H_cc, H_c, B, J,
                                                  H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                                                  equality
                                                nlinarith
                                              · exact core_ccccc
                                          | cons letter tail6 =>
                                              cases letter with
                                              | b =>
                                                  let H_cccccb : ℤ := 243 * H_ccccc - 39 * J
                                                  have core_cccccb : SCore tail6 H_cccccb J B := by
                                                    dsimp [H_cccccb]
                                                    exact stepB tail6 H_ccccc J B core_ccccc
                                                  apply killN tail6 H_cccccb J B
                                                    J_positive B_positive
                                                  · norm_num [H_cccccb, H_ccccc, H_cccc, H_ccc,
                                                    H_cc, H_c, B, J, H_root, hRoot, aRoot, corr,
                                                    qRoot, jRoot]
                                                    nlinarith
                                                  · exact core_cccccb
                                              | c =>
                                                  let H_cccccc : ℤ := 3 * H_ccccc
                                                  have core_cccccc : SCore tail6 H_cccccc J B := by
                                                    dsimp [H_cccccc]
                                                    exact stepC tail6 H_ccccc J B core_ccccc
                                                  cases tail6 with
                                                  | nil =>
                                                      apply kill0 H_cccccc J B
                                                      · intro equality
                                                        norm_num [H_cccccc, H_ccccc, H_cccc, H_ccc,
                                                          H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                                          corr, qRoot, jRoot] at equality
                                                        nlinarith
                                                      · exact core_cccccc
                                                  | cons letter tail7 =>
                                                      cases letter with
                                                      | b =>
                                                          let H_ccccccb : ℤ := 243 * H_cccccc - 39 *
                                                            J
                                                          have core_ccccccb : SCore tail7 H_ccccccb
                                                            J B := by
                                                            dsimp [H_ccccccb]
                                                            exact stepB tail7 H_cccccc J B
                                                              core_cccccc
                                                          apply killN tail7 H_ccccccb J B
                                                            J_positive B_positive
                                                          · norm_num [H_ccccccb, H_cccccc, H_ccccc,
                                                            H_cccc, H_ccc, H_cc, H_c, B, J, H_root,
                                                            hRoot, aRoot, corr, qRoot, jRoot]
                                                            nlinarith
                                                          · exact core_ccccccb
                                                      | c =>
                                                          let H_ccccccc : ℤ := 3 * H_cccccc
                                                          have core_ccccccc : SCore tail7 H_ccccccc
                                                            J B := by
                                                            dsimp [H_ccccccc]
                                                            exact stepC tail7 H_cccccc J B
                                                              core_cccccc
                                                          cases tail7 with
                                                          | nil =>
                                                              apply kill0 H_ccccccc J B
                                                              · intro equality
                                                                norm_num [H_ccccccc, H_cccccc,
                                                                  H_ccccc, H_cccc, H_ccc, H_cc, H_c,
                                                                  B, J, H_root, hRoot, aRoot, corr,
                                                                  qRoot, jRoot] at equality
                                                                nlinarith
                                                              · exact core_ccccccc
                                                          | cons letter tail8 =>
                                                              cases letter with
                                                              | b =>
                                                                  let H_cccccccb : ℤ := 243 *
                                                                    H_ccccccc - 39 * J
                                                                  have core_cccccccb : SCore tail8
                                                                    H_cccccccb J B := by
                                                                    dsimp [H_cccccccb]
                                                                    exact stepB tail8 H_ccccccc J B
                                                                      core_ccccccc
                                                                  apply killN tail8 H_cccccccb J B
                                                                    J_positive B_positive
                                                                  · norm_num [H_cccccccb, H_ccccccc,
                                                                    H_cccccc, H_ccccc, H_cccc,
                                                                    H_ccc, H_cc, H_c, B, J, H_root,
                                                                    hRoot, aRoot, corr, qRoot,
                                                                    jRoot]
                                                                    nlinarith
                                                                  · exact core_cccccccb
                                                              | c =>
                                                                  let H_cccccccc : ℤ := 3 *
                                                                    H_ccccccc
                                                                  have core_cccccccc : SCore tail8
                                                                    H_cccccccc J B := by
                                                                    dsimp [H_cccccccc]
                                                                    exact stepC tail8 H_ccccccc J B
                                                                      core_ccccccc
                                                                  cases tail8 with
                                                                  | nil =>
                                                                      apply kill0 H_cccccccc J B
                                                                      · intro equality
                                                                        norm_num [H_cccccccc,
                                                                          H_ccccccc, H_cccccc,
                                                                          H_ccccc, H_cccc, H_ccc,
                                                                          H_cc, H_c, B, J, H_root,
                                                                          hRoot, aRoot, corr, qRoot,
                                                                          jRoot] at equality
                                                                        nlinarith
                                                                      · exact core_cccccccc
                                                                  | cons letter tail9 =>
                                                                      cases letter with
                                                                      | b =>
                                                                          let H_ccccccccb : ℤ := 243
                                                                            * H_cccccccc - 39 * J
                                                                          have core_ccccccccb :
                                                                            SCore tail9 H_ccccccccb
                                                                            J B := by
                                                                            dsimp [H_ccccccccb]
                                                                            exact stepB tail9
                                                                              H_cccccccc J B
                                                                              core_cccccccc
                                                                          apply killN tail9
                                                                            H_ccccccccb J B
                                                                            J_positive B_positive
                                                                          · norm_num [H_ccccccccb,
                                                                            H_cccccccc, H_ccccccc,
                                                                            H_cccccc, H_ccccc,
                                                                            H_cccc, H_ccc, H_cc,
                                                                            H_c, B, J, H_root,
                                                                            hRoot, aRoot, corr,
                                                                            qRoot, jRoot]
                                                                            nlinarith
                                                                          · exact core_ccccccccb
                                                                      | c =>
                                                                          let H_ccccccccc : ℤ := 3 *
                                                                            H_cccccccc
                                                                          have core_ccccccccc :
                                                                            SCore tail9 H_ccccccccc
                                                                            J B := by
                                                                            dsimp [H_ccccccccc]
                                                                            exact stepC tail9
                                                                              H_cccccccc J B
                                                                              core_cccccccc
                                                                          cases tail9 with
                                                                          | nil =>
                                                                              apply kill0
                                                                                H_ccccccccc J B
                                                                              · intro equality
                                                                                norm_num
                                                                                  [H_ccccccccc,
                                                                                  H_cccccccc,
                                                                                  H_ccccccc,
                                                                                  H_cccccc, H_ccccc,
                                                                                  H_cccc, H_ccc,
                                                                                  H_cc, H_c, B, J,
                                                                                  H_root, hRoot,
                                                                                  aRoot, corr,
                                                                                  qRoot, jRoot] at
                                                                                  equality
                                                                                nlinarith
                                                                              · exact core_ccccccccc
                                                                          | cons letter tail10 =>
                                                                              cases letter with
                                                                              | b =>
                                                                                  let H_cccccccccb :
                                                                                    ℤ := 243 *
                                                                                    H_ccccccccc - 39
                                                                                    * J
                                                                                  have
                                                                                    core_cccccccccb
                                                                                    : SCore tail10
                                                                                    H_cccccccccb J B
                                                                                    := by
                                                                                    dsimp
                                                                                      [H_cccccccccb]
                                                                                    exact stepB
                                                                                      tail10
                                                                                      H_ccccccccc J
                                                                                      B
                                                                                      core_ccccccccc
                                                                                  apply killN tail10
                                                                                    H_cccccccccb J B
                                                                                    J_positive
                                                                                      B_positive
                                                                                  · norm_num
                                                                                    [H_cccccccccb,
                                                                                    H_ccccccccc,
                                                                                    H_cccccccc,
                                                                                    H_ccccccc,
                                                                                    H_cccccc,
                                                                                    H_ccccc, H_cccc,
                                                                                    H_ccc, H_cc,
                                                                                    H_c, B, J,
                                                                                    H_root, hRoot,
                                                                                    aRoot, corr,
                                                                                    qRoot, jRoot]
                                                                                    nlinarith
                                                                                  · exact
                                                                                    core_cccccccccb
                                                                              | c =>
                                                                                  let H_cccccccccc :
                                                                                    ℤ := 3 *
                                                                                    H_ccccccccc
                                                                                  have
                                                                                    core_cccccccccc
                                                                                    : SCore tail10
                                                                                    H_cccccccccc J B
                                                                                    := by
                                                                                    dsimp
                                                                                      [H_cccccccccc]
                                                                                    exact stepC
                                                                                      tail10
                                                                                      H_ccccccccc J
                                                                                      B
                                                                                      core_ccccccccc
                                                                                  apply killK 1
                                                                                    tail10
                                                                                    H_cccccccccc J B
                                                                                    J_positive
                                                                                      B_positive
                                                                                  · norm_num
                                                                                    [H_cccccccccc,
                                                                                    H_ccccccccc,
                                                                                    H_cccccccc,
                                                                                    H_ccccccc,
                                                                                    H_cccccc,
                                                                                    H_ccccc, H_cccc,
                                                                                    H_ccc, H_cc,
                                                                                    H_c, B, J,
                                                                                    H_root, hRoot,
                                                                                    aRoot, corr,
                                                                                    qRoot, jRoot]
                                                                                    nlinarith
                                                                                  · norm_num
                                                                                    [H_cccccccccc,
                                                                                    H_ccccccccc,
                                                                                    H_cccccccc,
                                                                                    H_ccccccc,
                                                                                    H_cccccc,
                                                                                    H_ccccc, H_cccc,
                                                                                    H_ccc, H_cc,
                                                                                    H_c, B, J,
                                                                                    H_root, hRoot,
                                                                                    aRoot, corr,
                                                                                    qRoot, jRoot]
                                                                                    nlinarith
                                                                                  · exact
                                                                                    core_cccccccccc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8095_549_549
    (body : List TagLetter) (z : Nat) (z_lower : 549 ≤ z)
    (z_upper : z ≤ 549)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8095 z)
      (firstBOneOuterJ 203 8095 z)
      (firstBOneOuterCorrection 203 8095 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8095 z
  let J : ℤ := jRoot 203 8095 z
  let B : ℤ := corr 203 8095 z
  change SCore body H_root J B at core
  have z_lower_int : (549 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 549 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  cases tail2 with
                  | nil =>
                      apply kill0 H_cc J B
                      · intro equality
                        norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_cc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_ccb : ℤ := 243 * H_cc - 39 * J
                          have core_ccb : SCore tail3 H_ccb J B := by
                            dsimp [H_ccb]
                            exact stepB tail3 H_cc J B core_cc
                          apply killN tail3 H_ccb J B
                            J_positive B_positive
                          · norm_num [H_ccb, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccb
                      | c =>
                          let H_ccc : ℤ := 3 * H_cc
                          have core_ccc : SCore tail3 H_ccc J B := by
                            dsimp [H_ccc]
                            exact stepC tail3 H_cc J B core_cc
                          cases tail3 with
                          | nil =>
                              apply kill0 H_ccc J B
                              · intro equality
                                norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                                  jRoot] at equality
                                nlinarith
                              · exact core_ccc
                          | cons letter tail4 =>
                              cases letter with
                              | b =>
                                  let H_cccb : ℤ := 243 * H_ccc - 39 * J
                                  have core_cccb : SCore tail4 H_cccb J B := by
                                    dsimp [H_cccb]
                                    exact stepB tail4 H_ccc J B core_ccc
                                  apply killN tail4 H_cccb J B
                                    J_positive B_positive
                                  · norm_num [H_cccb, H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                    corr, qRoot, jRoot]
                                    nlinarith
                                  · exact core_cccb
                              | c =>
                                  let H_cccc : ℤ := 3 * H_ccc
                                  have core_cccc : SCore tail4 H_cccc J B := by
                                    dsimp [H_cccc]
                                    exact stepC tail4 H_ccc J B core_ccc
                                  cases tail4 with
                                  | nil =>
                                      apply kill0 H_cccc J B
                                      · intro equality
                                        norm_num [H_cccc, H_ccc, H_cc, H_c, B, J, H_root, hRoot,
                                          aRoot, corr, qRoot, jRoot] at equality
                                        nlinarith
                                      · exact core_cccc
                                  | cons letter tail5 =>
                                      cases letter with
                                      | b =>
                                          let H_ccccb : ℤ := 243 * H_cccc - 39 * J
                                          have core_ccccb : SCore tail5 H_ccccb J B := by
                                            dsimp [H_ccccb]
                                            exact stepB tail5 H_cccc J B core_cccc
                                          apply killN tail5 H_ccccb J B
                                            J_positive B_positive
                                          · norm_num [H_ccccb, H_cccc, H_ccc, H_cc, H_c, B, J,
                                            H_root, hRoot, aRoot, corr, qRoot, jRoot]
                                            nlinarith
                                          · exact core_ccccb
                                      | c =>
                                          let H_ccccc : ℤ := 3 * H_cccc
                                          have core_ccccc : SCore tail5 H_ccccc J B := by
                                            dsimp [H_ccccc]
                                            exact stepC tail5 H_cccc J B core_cccc
                                          cases tail5 with
                                          | nil =>
                                              apply kill0 H_ccccc J B
                                              · intro equality
                                                norm_num [H_ccccc, H_cccc, H_ccc, H_cc, H_c, B, J,
                                                  H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                                                  equality
                                                nlinarith
                                              · exact core_ccccc
                                          | cons letter tail6 =>
                                              cases letter with
                                              | b =>
                                                  let H_cccccb : ℤ := 243 * H_ccccc - 39 * J
                                                  have core_cccccb : SCore tail6 H_cccccb J B := by
                                                    dsimp [H_cccccb]
                                                    exact stepB tail6 H_ccccc J B core_ccccc
                                                  apply killN tail6 H_cccccb J B
                                                    J_positive B_positive
                                                  · norm_num [H_cccccb, H_ccccc, H_cccc, H_ccc,
                                                    H_cc, H_c, B, J, H_root, hRoot, aRoot, corr,
                                                    qRoot, jRoot]
                                                    nlinarith
                                                  · exact core_cccccb
                                              | c =>
                                                  let H_cccccc : ℤ := 3 * H_ccccc
                                                  have core_cccccc : SCore tail6 H_cccccc J B := by
                                                    dsimp [H_cccccc]
                                                    exact stepC tail6 H_ccccc J B core_ccccc
                                                  cases tail6 with
                                                  | nil =>
                                                      apply kill0 H_cccccc J B
                                                      · intro equality
                                                        norm_num [H_cccccc, H_ccccc, H_cccc, H_ccc,
                                                          H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                                          corr, qRoot, jRoot] at equality
                                                        nlinarith
                                                      · exact core_cccccc
                                                  | cons letter tail7 =>
                                                      cases letter with
                                                      | b =>
                                                          let H_ccccccb : ℤ := 243 * H_cccccc - 39 *
                                                            J
                                                          have core_ccccccb : SCore tail7 H_ccccccb
                                                            J B := by
                                                            dsimp [H_ccccccb]
                                                            exact stepB tail7 H_cccccc J B
                                                              core_cccccc
                                                          apply killN tail7 H_ccccccb J B
                                                            J_positive B_positive
                                                          · norm_num [H_ccccccb, H_cccccc, H_ccccc,
                                                            H_cccc, H_ccc, H_cc, H_c, B, J, H_root,
                                                            hRoot, aRoot, corr, qRoot, jRoot]
                                                            nlinarith
                                                          · exact core_ccccccb
                                                      | c =>
                                                          let H_ccccccc : ℤ := 3 * H_cccccc
                                                          have core_ccccccc : SCore tail7 H_ccccccc
                                                            J B := by
                                                            dsimp [H_ccccccc]
                                                            exact stepC tail7 H_cccccc J B
                                                              core_cccccc
                                                          cases tail7 with
                                                          | nil =>
                                                              apply kill0 H_ccccccc J B
                                                              · intro equality
                                                                norm_num [H_ccccccc, H_cccccc,
                                                                  H_ccccc, H_cccc, H_ccc, H_cc, H_c,
                                                                  B, J, H_root, hRoot, aRoot, corr,
                                                                  qRoot, jRoot] at equality
                                                                nlinarith
                                                              · exact core_ccccccc
                                                          | cons letter tail8 =>
                                                              cases letter with
                                                              | b =>
                                                                  let H_cccccccb : ℤ := 243 *
                                                                    H_ccccccc - 39 * J
                                                                  have core_cccccccb : SCore tail8
                                                                    H_cccccccb J B := by
                                                                    dsimp [H_cccccccb]
                                                                    exact stepB tail8 H_ccccccc J B
                                                                      core_ccccccc
                                                                  apply killN tail8 H_cccccccb J B
                                                                    J_positive B_positive
                                                                  · norm_num [H_cccccccb, H_ccccccc,
                                                                    H_cccccc, H_ccccc, H_cccc,
                                                                    H_ccc, H_cc, H_c, B, J, H_root,
                                                                    hRoot, aRoot, corr, qRoot,
                                                                    jRoot]
                                                                    nlinarith
                                                                  · exact core_cccccccb
                                                              | c =>
                                                                  let H_cccccccc : ℤ := 3 *
                                                                    H_ccccccc
                                                                  have core_cccccccc : SCore tail8
                                                                    H_cccccccc J B := by
                                                                    dsimp [H_cccccccc]
                                                                    exact stepC tail8 H_ccccccc J B
                                                                      core_ccccccc
                                                                  apply killK 0 tail8 H_cccccccc J B
                                                                    J_positive B_positive
                                                                  · norm_num [H_cccccccc, H_ccccccc,
                                                                    H_cccccc, H_ccccc, H_cccc,
                                                                    H_ccc, H_cc, H_c, B, J, H_root,
                                                                    hRoot, aRoot, corr, qRoot,
                                                                    jRoot]
                                                                    nlinarith
                                                                  · norm_num [H_cccccccc, H_ccccccc,
                                                                    H_cccccc, H_ccccc, H_cccc,
                                                                    H_ccc, H_cc, H_c, B, J, H_root,
                                                                    hRoot, aRoot, corr, qRoot,
                                                                    jRoot]
                                                                    nlinarith
                                                                  · exact core_cccccccc

end MatrixMortality.ParabolicBlade
