import MatrixMortality.ParabolicFirstBOneInnerCertificateJ0A
import MatrixMortality.ParabolicFirstBOneInnerCertificateJ0B
import MatrixMortality.ParabolicFirstBOneInnerCertificateJ0C
import MatrixMortality.ParabolicFirstBOneInnerCertificateJ0D
import MatrixMortality.ParabolicFirstBOneInnerCertificateJ0E
import MatrixMortality.ParabolicFirstBOneInnerCertificateJ1
import MatrixMortality.ParabolicFirstBOneInnerCertificateJ23

/-!
# Exact large-inner suffix certificate at outer wait 211

This file is generated by `scripts/generate-parabolic-first-b-one-inner.py`.
The generator proves that 155 affine chambers close in a 231-node suffix tree of
depth at most three. Imported shards recheck every emitted sign and grammar branch
in Lean.
-/

namespace MatrixMortality.ParabolicBlade

/-- The four affine chambers left by the analytic large-inner reduction. -/
def FirstBOneX211LargeInnerCandidate (j y : Nat) : Prop :=
  (j = 0 ∧ 39701 ≤ y ∧ y ≤ 39830) ∨
    (j = 1 ∧ 26337 ≤ y ∧ y ≤ 26355) ∨
    (j = 2 ∧ 23671 ≤ y ∧ y ≤ 23675) ∨
    (j = 3 ∧ 22898 ≤ y ∧ y ≤ 22898)

private theorem largeInner_j0_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 0 y z) :
    39701 ≤ y ∧ y ≤ 39830 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 39700 := by omega
    have rectangle :
        (0 : ℤ) ≤ (39700 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (39831 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 39831) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j1_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 1 y z) :
    26337 ≤ y ∧ y ≤ 26355 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 26336 := by omega
    have rectangle :
        (0 : ℤ) ≤ (26336 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (26356 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 26356) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j2_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 2 y z) :
    23671 ≤ y ∧ y ≤ 23675 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 23670 := by omega
    have rectangle :
        (0 : ℤ) ≤ (23670 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (23676 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 23676) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j3_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 3 y z) :
    22898 ≤ y ∧ y ≤ 22898 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 22897 := by omega
    have rectangle :
        (0 : ℤ) ≤ (22897 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (22899 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 22899) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j4_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 4 y z) :
    22651 ≤ y ∧ y ≤ 22650 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 22650 := by omega
    have rectangle :
        (0 : ℤ) ≤ (22650 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (22651 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 22651) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j5_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 5 y z) :
    22570 ≤ y ∧ y ≤ 22569 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 22569 := by omega
    have rectangle :
        (0 : ℤ) ≤ (22569 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (22570 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 22570) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j6_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 6 y z) :
    22543 ≤ y ∧ y ≤ 22542 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 22542 := by omega
    have rectangle :
        (0 : ℤ) ≤ (22542 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (22543 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 22543) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j7_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 7 y z) :
    22534 ≤ y ∧ y ≤ 22533 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 22533 := by omega
    have rectangle :
        (0 : ℤ) ≤ (22533 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (22534 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 22534) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j8_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 8 y z) :
    22531 ≤ y ∧ y ≤ 22530 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 22530 := by omega
    have rectangle :
        (0 : ℤ) ≤ (22530 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (22531 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 22531) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j9_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 9 y z) :
    22530 ≤ y ∧ y ≤ 22529 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  constructor
  · by_contra y_not_large
    have y_small_int : (y : ℤ) ≤ 22529 := by omega
    have rectangle :
        (0 : ℤ) ≤ (22529 - (y : ℤ)) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_small_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith
  · by_contra y_not_small
    have y_large_int : (22530 : ℤ) ≤ y := by omega
    have rectangle :
        (0 : ℤ) ≤ ((y : ℤ) - 22530) * ((z : ℤ) - 1594323) :=
      mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
    norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A,
      firstBOneX211B, firstBOneX211Q, firstBOneX211J] at envelope
    ring_nf at envelope
    nlinarith

private theorem largeInner_j10_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 10 y z) :
    y ≤ 22528 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  by_contra y_not_small
  have y_large_int : (22529 : ℤ) ≤ y := by omega
  have rectangle :
      (0 : ℤ) ≤ ((y : ℤ) - 22529) * ((z : ℤ) - 1594323) :=
    mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
  norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A, firstBOneX211B,
    firstBOneX211Q, firstBOneX211J] at envelope
  ring_nf at envelope
  nlinarith

private theorem largeInner_j11_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 11 y z) :
    y ≤ 22528 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  by_contra y_not_small
  have y_large_int : (22529 : ℤ) ≤ y := by omega
  have rectangle :
      (0 : ℤ) ≤ ((y : ℤ) - 22529) * ((z : ℤ) - 1594323) :=
    mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
  norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A, firstBOneX211B,
    firstBOneX211Q, firstBOneX211J] at envelope
  ring_nf at envelope
  nlinarith

private theorem largeInner_j12_bounds
    (y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope 12 y z) :
    y ≤ 22528 := by
  have z_large_int : (1594323 : ℤ) ≤ z := by exact_mod_cast z_large
  by_contra y_not_small
  have y_large_int : (22529 : ℤ) ≤ y := by omega
  have rectangle :
      (0 : ℤ) ≤ ((y : ℤ) - 22529) * ((z : ℤ) - 1594323) :=
    mul_nonneg (sub_nonneg.mpr y_large_int) (sub_nonneg.mpr z_large_int)
  norm_num [FirstBOneX211LargeInnerEnvelope, firstBOneX211SuffixH, firstBOneX211A, firstBOneX211B,
    firstBOneX211Q, firstBOneX211J] at envelope
  ring_nf at envelope
  nlinarith

/-- The large-inner envelope leaves exactly four finite first-`b`/middle-wait strips. -/
theorem firstBOneX211LargeInnerCandidate_of_envelope
    (j y z : Nat) (y_upper : y ≤ 51767) (z_large : 3 ^ 13 ≤ z)
    (envelope : FirstBOneX211LargeInnerEnvelope j y z) :
    FirstBOneX211LargeInnerCandidate j y := by
  have y_lower := firstBOneX211_y_lower_of_large_inner_envelope j y z envelope
  have position_bound :=
    firstBOneX211_position_lt_thirteen_of_large_inner_envelope
      j y z y_lower y_upper z_large envelope
  have position_le : j ≤ 12 := by omega
  interval_cases j
  · have bounds := largeInner_j0_bounds y z z_large envelope
    exact Or.inl ⟨rfl, bounds.1, bounds.2⟩
  · have bounds := largeInner_j1_bounds y z z_large envelope
    exact Or.inr (Or.inl ⟨rfl, bounds.1, bounds.2⟩)
  · have bounds := largeInner_j2_bounds y z z_large envelope
    exact Or.inr (Or.inr (Or.inl ⟨rfl, bounds.1, bounds.2⟩))
  · have bounds := largeInner_j3_bounds y z z_large envelope
    exact Or.inr (Or.inr (Or.inr ⟨rfl, bounds.1, bounds.2⟩))
  · have bounds := largeInner_j4_bounds y z z_large envelope
    omega
  · have bounds := largeInner_j5_bounds y z z_large envelope
    omega
  · have bounds := largeInner_j6_bounds y z z_large envelope
    omega
  · have bounds := largeInner_j7_bounds y z z_large envelope
    omega
  · have bounds := largeInner_j8_bounds y z z_large envelope
    omega
  · have bounds := largeInner_j9_bounds y z z_large envelope
    omega
  · have upper := largeInner_j10_bounds y z z_large envelope
    omega
  · have upper := largeInner_j11_bounds y z z_large envelope
    omega
  · have upper := largeInner_j12_bounds y z z_large envelope
    omega

/-- Every candidate suffix core is impossible throughout the large-inner ray. -/
theorem firstBOneX211SuffixCore_false_of_large_inner_candidate
    (body : List TagLetter) (j y z : Nat) (z_large : 3 ^ 13 ≤ z)
    (candidate : FirstBOneX211LargeInnerCandidate j y)
    (core : FirstBOneX211SuffixCore body (firstBOneX211SuffixH j y z)
      (firstBOneX211J y z) (firstBOneX211B y z)) : False := by
  unfold FirstBOneX211LargeInnerCandidate at candidate
  rcases candidate with first | second | third | fourth
  · rcases first with ⟨rfl, y_lower, y_upper⟩
    have chamber :
        (39701 ≤ y ∧ y ≤ 39726) ∨
          (39727 ≤ y ∧ y ≤ 39752) ∨
          (39753 ≤ y ∧ y ≤ 39778) ∨
          (39779 ≤ y ∧ y ≤ 39804) ∨
          (39805 ≤ y ∧ y ≤ 39830) := by
      omega
    rcases chamber with first | second | third | fourth | fifth
    · exact firstBOneX211SuffixCore_false_j0a body y z
        first.1 first.2 z_large core
    · exact firstBOneX211SuffixCore_false_j0b body y z
        second.1 second.2 z_large core
    · exact firstBOneX211SuffixCore_false_j0c body y z
        third.1 third.2 z_large core
    · exact firstBOneX211SuffixCore_false_j0d body y z
        fourth.1 fourth.2 z_large core
    · exact firstBOneX211SuffixCore_false_j0e body y z
        fifth.1 fifth.2 z_large core
  · rcases second with ⟨rfl, y_lower, y_upper⟩
    exact firstBOneX211SuffixCore_false_j1 body y z
      y_lower y_upper z_large core
  · rcases third with ⟨rfl, y_lower, y_upper⟩
    exact firstBOneX211SuffixCore_false_j2 body y z
      y_lower y_upper z_large core
  · rcases fourth with ⟨rfl, y_lower, y_upper⟩
    exact firstBOneX211SuffixCore_false_j3 body y z
      y_lower y_upper z_large core

end MatrixMortality.ParabolicBlade
