import MatrixMortality.ParabolicFirstBOneOuterCertificateCore

/-!
# Exact initial-cb tail certificate shard 2

This exact certificate shard is generated by
`scripts/generate-parabolic-first-b-one-outer.py`.
-/

namespace MatrixMortality.ParabolicBlade

-- BEGIN GENERATED FIRST-B-ONE-OUTER TAIL CERTIFICATE

private theorem firstBOneOuter_root_210_796
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 796)
          (firstBOneOuterD tail) 210 796 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 796)
          (firstBOneOuterD tail) 210 796) :
    FirstBOneOuterCandidate 210 j 796 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 796
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 796 * z =
    firstBTwoTailZNumerator a d 210 796 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 ∨ j = 4 ∨ j = 5 ∨ j = 6 ∨ j = 7 ∨ 8 ≤ j := by omega
  rcases j_cases with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 796 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 796) (firstBOneOuterAUpper 796)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 796 (-1)
        (firstBOneOuterALower 0 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 796 z (-1)
      (firstBOneOuterALower 0 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 796 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 796) (firstBOneOuterAUpper 796)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 796 (-1)
        (firstBOneOuterALower 1 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 796 z (-1)
      (firstBOneOuterALower 1 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 2 rest 796 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 796) (firstBOneOuterAUpper 796)
      (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 796 (-1)
        (firstBOneOuterALower 2 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 796 z (-1)
      (firstBOneOuterALower 2 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 3 rest 796 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 3 796) (firstBOneOuterAUpper 796)
      (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 796 (-1)
        (firstBOneOuterALower 3 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 796 z (-1)
      (firstBOneOuterALower 3 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 4 rest 796 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 4 796) (firstBOneOuterAUpper 796)
      (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 796 (-1)
        (firstBOneOuterALower 4 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 796 z (-1)
      (firstBOneOuterALower 4 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 5 rest 796 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 5 796) (firstBOneOuterAUpper 796)
      (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 796 35 36 1
        (firstBOneOuterALower 5 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 796 35 z 1
      (firstBOneOuterALower 5 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 6 rest 796 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 6 796) (firstBOneOuterAUpper 796)
      (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 796 25 26 1
        (firstBOneOuterALower 6 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 796 25 z 1
      (firstBOneOuterALower 6 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 7 rest 796 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 7 796) (firstBOneOuterAUpper 796)
      (firstBTwoTailDLower 7) (firstBTwoTailDUpper 7) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 796 23 24 1
        (firstBOneOuterALower 7 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 7)
          (firstBTwoTailDUpper 7) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 796 23 z 1
      (firstBOneOuterALower 7 796) (firstBOneOuterAUpper 796) (firstBTwoTailDLower 7)
        (firstBTwoTailDUpper 7) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 8 j rest 796 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 8 796) (firstBOneOuterAUpper 796)
      39 (firstBTwoTailDUpper 8) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 796 22 23 1
        (firstBOneOuterALower 8 796) (firstBOneOuterAUpper 796) 39 (firstBTwoTailDUpper 8) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 796 22 z 1
      (firstBOneOuterALower 8 796) (firstBOneOuterAUpper 796) 39 (firstBTwoTailDUpper 8) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_797
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 797)
          (firstBOneOuterD tail) 210 797 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 797)
          (firstBOneOuterD tail) 210 797) :
    FirstBOneOuterCandidate 210 j 797 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 797
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 797 * z =
    firstBTwoTailZNumerator a d 210 797 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 ∨ j = 4 ∨ 5 ≤ j := by omega
  rcases j_cases with rfl | rfl | rfl | rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 797 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 797) (firstBOneOuterAUpper 797)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 797 (-1)
        (firstBOneOuterALower 0 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 797 z (-1)
      (firstBOneOuterALower 0 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 797 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 797) (firstBOneOuterAUpper 797)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 797 (-1)
        (firstBOneOuterALower 1 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 797 z (-1)
      (firstBOneOuterALower 1 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 2 rest 797 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 797) (firstBOneOuterAUpper 797)
      (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 797 (-1)
        (firstBOneOuterALower 2 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 797 z (-1)
      (firstBOneOuterALower 2 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 3 rest 797 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 3 797) (firstBOneOuterAUpper 797)
      (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 797 6 7 1
        (firstBOneOuterALower 3 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 797 6 z 1
      (firstBOneOuterALower 3 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 4 rest 797 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 4 797) (firstBOneOuterAUpper 797)
      (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 797 4 5 1
        (firstBOneOuterALower 4 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 797 4 z 1
      (firstBOneOuterALower 4 797) (firstBOneOuterAUpper 797) (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 5 j rest 797 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 5 797) (firstBOneOuterAUpper 797)
      39 (firstBTwoTailDUpper 5) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 797 3 4 1
        (firstBOneOuterALower 5 797) (firstBOneOuterAUpper 797) 39 (firstBTwoTailDUpper 5) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 797 3 z 1
      (firstBOneOuterALower 5 797) (firstBOneOuterAUpper 797) 39 (firstBTwoTailDUpper 5) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_798
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 798)
          (firstBOneOuterD tail) 210 798 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 798)
          (firstBOneOuterD tail) 210 798) :
    FirstBOneOuterCandidate 210 j 798 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 798
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 798 * z =
    firstBTwoTailZNumerator a d 210 798 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 ∨ 4 ≤ j := by omega
  rcases j_cases with rfl | rfl | rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 798 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 798) (firstBOneOuterAUpper 798)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 798 (-1)
        (firstBOneOuterALower 0 798) (firstBOneOuterAUpper 798) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 798 z (-1)
      (firstBOneOuterALower 0 798) (firstBOneOuterAUpper 798) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 798 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 798) (firstBOneOuterAUpper 798)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 798 (-1)
        (firstBOneOuterALower 1 798) (firstBOneOuterAUpper 798) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 798 z (-1)
      (firstBOneOuterALower 1 798) (firstBOneOuterAUpper 798) (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 2 rest 798 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 798) (firstBOneOuterAUpper 798)
      (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 798 8 9 1
        (firstBOneOuterALower 2 798) (firstBOneOuterAUpper 798) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 798 8 z 1
      (firstBOneOuterALower 2 798) (firstBOneOuterAUpper 798) (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 3 rest 798 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 3 798) (firstBOneOuterAUpper 798)
      (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 798 2 3 1
        (firstBOneOuterALower 3 798) (firstBOneOuterAUpper 798) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 798 2 z 1
      (firstBOneOuterALower 3 798) (firstBOneOuterAUpper 798) (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 4 j rest 798 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 4 798) (firstBOneOuterAUpper 798)
      39 (firstBTwoTailDUpper 4) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 798 1 2 1
        (firstBOneOuterALower 4 798) (firstBOneOuterAUpper 798) 39 (firstBTwoTailDUpper 4) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 798 1 z 1
      (firstBOneOuterALower 4 798) (firstBOneOuterAUpper 798) 39 (firstBTwoTailDUpper 4) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_799
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 799)
          (firstBOneOuterD tail) 210 799 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 799)
          (firstBOneOuterD tail) 210 799) :
    FirstBOneOuterCandidate 210 j 799 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 799
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 799 * z =
    firstBTwoTailZNumerator a d 210 799 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ j = 2 ∨ 3 ≤ j := by omega
  rcases j_cases with rfl | rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 799 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 799) (firstBOneOuterAUpper 799)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 799 (-1)
        (firstBOneOuterALower 0 799) (firstBOneOuterAUpper 799) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 799 z (-1)
      (firstBOneOuterALower 0 799) (firstBOneOuterAUpper 799) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 799 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 799) (firstBOneOuterAUpper 799)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 799 (-1)
        (firstBOneOuterALower 1 799) (firstBOneOuterAUpper 799) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 799 z (-1)
      (firstBOneOuterALower 1 799) (firstBOneOuterAUpper 799) (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 2 rest 799 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 799) (firstBOneOuterAUpper 799)
      (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 799 2 3 1
        (firstBOneOuterALower 2 799) (firstBOneOuterAUpper 799) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 799 2 z 1
      (firstBOneOuterALower 2 799) (firstBOneOuterAUpper 799) (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 3 j rest 799 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 3 799) (firstBOneOuterAUpper 799)
      39 (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 799 1 2 1
        (firstBOneOuterALower 3 799) (firstBOneOuterAUpper 799) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 799 1 z 1
      (firstBOneOuterALower 3 799) (firstBOneOuterAUpper 799) 39 (firstBTwoTailDUpper 3) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_800
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 800)
          (firstBOneOuterD tail) 210 800 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 800)
          (firstBOneOuterD tail) 210 800) :
    FirstBOneOuterCandidate 210 j 800 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 800
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 800 * z =
    firstBTwoTailZNumerator a d 210 800 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ j = 2 ∨ j = 3 ∨ 4 ≤ j := by omega
  rcases j_cases with rfl | rfl | rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 800 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 800) (firstBOneOuterAUpper 800)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 800 (-1)
        (firstBOneOuterALower 0 800) (firstBOneOuterAUpper 800) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 800 z (-1)
      (firstBOneOuterALower 0 800) (firstBOneOuterAUpper 800) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 800 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 800) (firstBOneOuterAUpper 800)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 800 (-1)
        (firstBOneOuterALower 1 800) (firstBOneOuterAUpper 800) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 800 z (-1)
      (firstBOneOuterALower 1 800) (firstBOneOuterAUpper 800) (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 2 rest 800 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 800) (firstBOneOuterAUpper 800)
      (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 800 1 2 1
        (firstBOneOuterALower 2 800) (firstBOneOuterAUpper 800) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 800 1 z 1
      (firstBOneOuterALower 2 800) (firstBOneOuterAUpper 800) (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 3 rest 800 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 3 800) (firstBOneOuterAUpper 800)
      (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 800 1 2 1
        (firstBOneOuterALower 3 800) (firstBOneOuterAUpper 800) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 800 1 z 1
      (firstBOneOuterALower 3 800) (firstBOneOuterAUpper 800) (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 4 j rest 800 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 4 800) (firstBOneOuterAUpper 800)
      39 (firstBTwoTailDUpper 4) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 800 0 1 1
        (firstBOneOuterALower 4 800) (firstBOneOuterAUpper 800) 39 (firstBTwoTailDUpper 4) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 800 0 z 1
      (firstBOneOuterALower 4 800) (firstBOneOuterAUpper 800) 39 (firstBTwoTailDUpper 4) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_801
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 801)
          (firstBOneOuterD tail) 210 801 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 801)
          (firstBOneOuterD tail) 210 801) :
    FirstBOneOuterCandidate 210 j 801 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 801
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 801 * z =
    firstBTwoTailZNumerator a d 210 801 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ j = 2 ∨ 3 ≤ j := by omega
  rcases j_cases with rfl | rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 801 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 801) (firstBOneOuterAUpper 801)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 801 (-1)
        (firstBOneOuterALower 0 801) (firstBOneOuterAUpper 801) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 801 z (-1)
      (firstBOneOuterALower 0 801) (firstBOneOuterAUpper 801) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 801 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 801) (firstBOneOuterAUpper 801)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have numerator_positive :
        0 < firstBTwoTailZNumerator a d 210 801 := by
      have positive := firstBTwoTail_affine_rectangle_pos
        (-54089353) 58899993321372 0
        (firstBOneOuterALower 1 801) (firstBOneOuterAUpper 801) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) a d rectangle
        (by norm_num [firstBOneOuterALower, firstBOneOuterAUpper, firstBTwoTailDLower,
          firstBTwoTailDUpper])
        (by norm_num [firstBOneOuterALower, firstBOneOuterAUpper, firstBTwoTailDLower,
          firstBTwoTailDUpper])
        (by norm_num [firstBOneOuterALower, firstBOneOuterAUpper, firstBTwoTailDLower,
          firstBTwoTailDUpper])
        (by norm_num [firstBOneOuterALower, firstBOneOuterAUpper, firstBTwoTailDLower,
          firstBTwoTailDUpper])
      have identity : firstBTwoTailZNumerator a d 210 801 =
          (-54089353) * a + 58899993321372 * d + 0 := by
        norm_num [firstBTwoTailZNumerator]
        ring
      rw [identity]
      exact positive
    have lower_margin_positive :
        0 < firstBTwoTailZNumerator a d 210 801 -
          379 * firstBTwoTailZDenominator a d 210 801 := by
      have positive := firstBTwoTail_affine_rectangle_pos
        (-221971337397) 238925070721086660 0
        (firstBOneOuterALower 1 801) (firstBOneOuterAUpper 801) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) a d rectangle
        (by norm_num [firstBOneOuterALower, firstBOneOuterAUpper, firstBTwoTailDLower,
          firstBTwoTailDUpper])
        (by norm_num [firstBOneOuterALower, firstBOneOuterAUpper, firstBTwoTailDLower,
          firstBTwoTailDUpper])
        (by norm_num [firstBOneOuterALower, firstBOneOuterAUpper, firstBTwoTailDLower,
          firstBTwoTailDUpper])
        (by norm_num [firstBOneOuterALower, firstBOneOuterAUpper, firstBTwoTailDLower,
          firstBTwoTailDUpper])
      have identity :
          firstBTwoTailZNumerator a d 210 801 -
              379 * firstBTwoTailZDenominator a d 210 801 =
            (-221971337397) * a + 238925070721086660 * d + 0 := by
        norm_num [firstBTwoTailZNumerator, firstBTwoTailZDenominator]
        ring
      rw [identity]
      exact positive
    have product_positive :
        0 < firstBTwoTailZDenominator a d 210 801 * (z : ℚ) := by
      rw [root_eq]
      exact numerator_positive
    have denominator_positive :
        0 < firstBTwoTailZDenominator a d 210 801 := by
      rcases mul_pos_iff.mp product_positive with positive | negative
      · exact positive.1
      · exact (not_lt_of_ge (by positivity : (0 : ℚ) ≤ z) negative.2).elim
    have factored :
        firstBTwoTailZNumerator a d 210 801 -
            379 * firstBTwoTailZDenominator a d 210 801 =
          firstBTwoTailZDenominator a d 210 801 * ((z : ℚ) - 379) := by
      rw [← root_eq]
      ring
    rw [factored] at lower_margin_positive
    have offset_positive : (0 : ℚ) < z - 379 := by
      rcases mul_pos_iff.mp lower_margin_positive with positive | negative
      · exact positive.2
      · exact (not_lt_of_ge denominator_positive.le negative.1).elim
    have z_lower : 380 ≤ z := by
      have z_strict : 379 < z := by exact_mod_cast (by linarith : (379 : ℚ) < z)
      omega
    unfold FirstBOneOuterCandidate
    omega
  · have rectangle := firstBOneOuter_exact_rectangle 2 rest 801 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 801) (firstBOneOuterAUpper 801)
      (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 801 1 2 1
        (firstBOneOuterALower 2 801) (firstBOneOuterAUpper 801) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 801 1 z 1
      (firstBOneOuterALower 2 801) (firstBOneOuterAUpper 801) (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 3 j rest 801 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 3 801) (firstBOneOuterAUpper 801)
      39 (firstBTwoTailDUpper 3) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 801 0 1 1
        (firstBOneOuterALower 3 801) (firstBOneOuterAUpper 801) 39 (firstBTwoTailDUpper 3) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 801 0 z 1
      (firstBOneOuterALower 3 801) (firstBOneOuterAUpper 801) 39 (firstBTwoTailDUpper 3) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_802
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 802)
          (firstBOneOuterD tail) 210 802 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 802)
          (firstBOneOuterD tail) 210 802) :
    FirstBOneOuterCandidate 210 j 802 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 802
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 802 * z =
    firstBTwoTailZNumerator a d 210 802 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ 2 ≤ j := by omega
  rcases j_cases with rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 802 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 802) (firstBOneOuterAUpper 802)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 802 (-1)
        (firstBOneOuterALower 0 802) (firstBOneOuterAUpper 802) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 802 z (-1)
      (firstBOneOuterALower 0 802) (firstBOneOuterAUpper 802) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 802 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 802) (firstBOneOuterAUpper 802)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 802 3 5 1
        (firstBOneOuterALower 1 802) (firstBOneOuterAUpper 802) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    have interval := firstBTwoTailZ_mem_open_interval 210 802 3 5
      z 1 (firstBOneOuterALower 1 802) (firstBOneOuterAUpper 802) (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
    unfold FirstBOneOuterCandidate
    omega
  · have rectangle := firstBOneOuter_envelope_rectangle 2 j rest 802 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 802) (firstBOneOuterAUpper 802)
      39 (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 802 0 1 1
        (firstBOneOuterALower 2 802) (firstBOneOuterAUpper 802) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 802 0 z 1
      (firstBOneOuterALower 2 802) (firstBOneOuterAUpper 802) 39 (firstBTwoTailDUpper 2) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_803
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 803)
          (firstBOneOuterD tail) 210 803 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 803)
          (firstBOneOuterD tail) 210 803) :
    FirstBOneOuterCandidate 210 j 803 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 803
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 803 * z =
    firstBTwoTailZNumerator a d 210 803 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ 2 ≤ j := by omega
  rcases j_cases with rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 803 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 803) (firstBOneOuterAUpper 803)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 803 (-1)
        (firstBOneOuterALower 0 803) (firstBOneOuterAUpper 803) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 803 z (-1)
      (firstBOneOuterALower 0 803) (firstBOneOuterAUpper 803) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 803 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 803) (firstBOneOuterAUpper 803)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 803 1 2 1
        (firstBOneOuterALower 1 803) (firstBOneOuterAUpper 803) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 803 1 z 1
      (firstBOneOuterALower 1 803) (firstBOneOuterAUpper 803) (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 2 j rest 803 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 803) (firstBOneOuterAUpper 803)
      39 (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 803 0 1 1
        (firstBOneOuterALower 2 803) (firstBOneOuterAUpper 803) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 803 0 z 1
      (firstBOneOuterALower 2 803) (firstBOneOuterAUpper 803) 39 (firstBTwoTailDUpper 2) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_804
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 804)
          (firstBOneOuterD tail) 210 804 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 804)
          (firstBOneOuterD tail) 210 804) :
    FirstBOneOuterCandidate 210 j 804 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 804
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 804 * z =
    firstBTwoTailZNumerator a d 210 804 at root_eq
  have j_cases : j = 0 ∨ j = 1 ∨ 2 ≤ j := by omega
  rcases j_cases with rfl | rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 804 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 804) (firstBOneOuterAUpper 804)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 804 (-1)
        (firstBOneOuterALower 0 804) (firstBOneOuterAUpper 804) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 804 z (-1)
      (firstBOneOuterALower 0 804) (firstBOneOuterAUpper 804) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_exact_rectangle 1 rest 804 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 804) (firstBOneOuterAUpper 804)
      (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 804 1 2 1
        (firstBOneOuterALower 1 804) (firstBOneOuterAUpper 804) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 804 1 z 1
      (firstBOneOuterALower 1 804) (firstBOneOuterAUpper 804) (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 2 j rest 804 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 2 804) (firstBOneOuterAUpper 804)
      39 (firstBTwoTailDUpper 2) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 804 0 1 1
        (firstBOneOuterALower 2 804) (firstBOneOuterAUpper 804) 39 (firstBTwoTailDUpper 2) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 804 0 z 1
      (firstBOneOuterALower 2 804) (firstBOneOuterAUpper 804) 39 (firstBTwoTailDUpper 2) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_805
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 805)
          (firstBOneOuterD tail) 210 805 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 805)
          (firstBOneOuterD tail) 210 805) :
    FirstBOneOuterCandidate 210 j 805 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 805
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 805 * z =
    firstBTwoTailZNumerator a d 210 805 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 805 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 805) (firstBOneOuterAUpper 805)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 805 (-1)
        (firstBOneOuterALower 0 805) (firstBOneOuterAUpper 805) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 805 z (-1)
      (firstBOneOuterALower 0 805) (firstBOneOuterAUpper 805) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 805 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 805) (firstBOneOuterAUpper 805)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 805 0 1 1
        (firstBOneOuterALower 1 805) (firstBOneOuterAUpper 805) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 805 0 z 1
      (firstBOneOuterALower 1 805) (firstBOneOuterAUpper 805) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_806
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 806)
          (firstBOneOuterD tail) 210 806 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 806)
          (firstBOneOuterD tail) 210 806) :
    FirstBOneOuterCandidate 210 j 806 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 806
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 806 * z =
    firstBTwoTailZNumerator a d 210 806 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 806 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 806) (firstBOneOuterAUpper 806)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 806 (-1)
        (firstBOneOuterALower 0 806) (firstBOneOuterAUpper 806) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 806 z (-1)
      (firstBOneOuterALower 0 806) (firstBOneOuterAUpper 806) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 806 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 806) (firstBOneOuterAUpper 806)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 806 0 1 1
        (firstBOneOuterALower 1 806) (firstBOneOuterAUpper 806) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 806 0 z 1
      (firstBOneOuterALower 1 806) (firstBOneOuterAUpper 806) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_807
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 807)
          (firstBOneOuterD tail) 210 807 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 807)
          (firstBOneOuterD tail) 210 807) :
    FirstBOneOuterCandidate 210 j 807 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 807
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 807 * z =
    firstBTwoTailZNumerator a d 210 807 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 807 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 807) (firstBOneOuterAUpper 807)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 807 (-1)
        (firstBOneOuterALower 0 807) (firstBOneOuterAUpper 807) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 807 z (-1)
      (firstBOneOuterALower 0 807) (firstBOneOuterAUpper 807) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 807 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 807) (firstBOneOuterAUpper 807)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 807 0 1 1
        (firstBOneOuterALower 1 807) (firstBOneOuterAUpper 807) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 807 0 z 1
      (firstBOneOuterALower 1 807) (firstBOneOuterAUpper 807) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_808
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 808)
          (firstBOneOuterD tail) 210 808 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 808)
          (firstBOneOuterD tail) 210 808) :
    FirstBOneOuterCandidate 210 j 808 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 808
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 808 * z =
    firstBTwoTailZNumerator a d 210 808 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 808 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 808) (firstBOneOuterAUpper 808)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 808 (-1)
        (firstBOneOuterALower 0 808) (firstBOneOuterAUpper 808) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 808 z (-1)
      (firstBOneOuterALower 0 808) (firstBOneOuterAUpper 808) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 808 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 808) (firstBOneOuterAUpper 808)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 808 0 1 1
        (firstBOneOuterALower 1 808) (firstBOneOuterAUpper 808) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 808 0 z 1
      (firstBOneOuterALower 1 808) (firstBOneOuterAUpper 808) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_809
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 809)
          (firstBOneOuterD tail) 210 809 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 809)
          (firstBOneOuterD tail) 210 809) :
    FirstBOneOuterCandidate 210 j 809 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 809
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 809 * z =
    firstBTwoTailZNumerator a d 210 809 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 809 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 809) (firstBOneOuterAUpper 809)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 809 (-1)
        (firstBOneOuterALower 0 809) (firstBOneOuterAUpper 809) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 809 z (-1)
      (firstBOneOuterALower 0 809) (firstBOneOuterAUpper 809) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 809 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 809) (firstBOneOuterAUpper 809)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 809 0 1 1
        (firstBOneOuterALower 1 809) (firstBOneOuterAUpper 809) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 809 0 z 1
      (firstBOneOuterALower 1 809) (firstBOneOuterAUpper 809) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_810
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 810)
          (firstBOneOuterD tail) 210 810 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 810)
          (firstBOneOuterD tail) 210 810) :
    FirstBOneOuterCandidate 210 j 810 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 810
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 810 * z =
    firstBTwoTailZNumerator a d 210 810 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 810 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 810) (firstBOneOuterAUpper 810)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 810 (-1)
        (firstBOneOuterALower 0 810) (firstBOneOuterAUpper 810) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 810 z (-1)
      (firstBOneOuterALower 0 810) (firstBOneOuterAUpper 810) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 810 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 810) (firstBOneOuterAUpper 810)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 810 0 1 1
        (firstBOneOuterALower 1 810) (firstBOneOuterAUpper 810) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 810 0 z 1
      (firstBOneOuterALower 1 810) (firstBOneOuterAUpper 810) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_811
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 811)
          (firstBOneOuterD tail) 210 811 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 811)
          (firstBOneOuterD tail) 210 811) :
    FirstBOneOuterCandidate 210 j 811 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 811
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 811 * z =
    firstBTwoTailZNumerator a d 210 811 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 811 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 811) (firstBOneOuterAUpper 811)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 210 811 (-1)
        (firstBOneOuterALower 0 811) (firstBOneOuterAUpper 811) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_negative 210 811 z (-1)
      (firstBOneOuterALower 0 811) (firstBOneOuterAUpper 811) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 811 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 811) (firstBOneOuterAUpper 811)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 811 0 1 1
        (firstBOneOuterALower 1 811) (firstBOneOuterAUpper 811) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 811 0 z 1
      (firstBOneOuterALower 1 811) (firstBOneOuterAUpper 811) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_812
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 812)
          (firstBOneOuterD tail) 210 812 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 812)
          (firstBOneOuterD tail) 210 812) :
    FirstBOneOuterCandidate 210 j 812 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 812
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 812 * z =
    firstBTwoTailZNumerator a d 210 812 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 812 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 812) (firstBOneOuterAUpper 812)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 812 8 10 1
        (firstBOneOuterALower 0 812) (firstBOneOuterAUpper 812) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    have interval := firstBTwoTailZ_mem_open_interval 210 812 8 10
      z 1 (firstBOneOuterALower 0 812) (firstBOneOuterAUpper 812) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0)
      a d rectangle corners root_eq
    unfold FirstBOneOuterCandidate
    omega
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 812 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 812) (firstBOneOuterAUpper 812)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 812 0 1 1
        (firstBOneOuterALower 1 812) (firstBOneOuterAUpper 812) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 812 0 z 1
      (firstBOneOuterALower 1 812) (firstBOneOuterAUpper 812) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_813
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 813)
          (firstBOneOuterD tail) 210 813 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 813)
          (firstBOneOuterD tail) 210 813) :
    FirstBOneOuterCandidate 210 j 813 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 813
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 813 * z =
    firstBTwoTailZNumerator a d 210 813 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 813 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 813) (firstBOneOuterAUpper 813)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 813 2 3 1
        (firstBOneOuterALower 0 813) (firstBOneOuterAUpper 813) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 813 2 z 1
      (firstBOneOuterALower 0 813) (firstBOneOuterAUpper 813) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 813 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 813) (firstBOneOuterAUpper 813)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 813 0 1 1
        (firstBOneOuterALower 1 813) (firstBOneOuterAUpper 813) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 813 0 z 1
      (firstBOneOuterALower 1 813) (firstBOneOuterAUpper 813) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_814
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 814)
          (firstBOneOuterD tail) 210 814 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 814)
          (firstBOneOuterD tail) 210 814) :
    FirstBOneOuterCandidate 210 j 814 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 814
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 814 * z =
    firstBTwoTailZNumerator a d 210 814 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 814 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 814) (firstBOneOuterAUpper 814)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 814 1 2 1
        (firstBOneOuterALower 0 814) (firstBOneOuterAUpper 814) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 814 1 z 1
      (firstBOneOuterALower 0 814) (firstBOneOuterAUpper 814) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 814 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 814) (firstBOneOuterAUpper 814)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 814 0 1 1
        (firstBOneOuterALower 1 814) (firstBOneOuterAUpper 814) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 814 0 z 1
      (firstBOneOuterALower 1 814) (firstBOneOuterAUpper 814) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_815
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 815)
          (firstBOneOuterD tail) 210 815 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 815)
          (firstBOneOuterD tail) 210 815) :
    FirstBOneOuterCandidate 210 j 815 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 815
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 815 * z =
    firstBTwoTailZNumerator a d 210 815 at root_eq
  have j_cases : j = 0 ∨ 1 ≤ j := by omega
  rcases j_cases with rfl | k_le_j
  · have rectangle := firstBOneOuter_exact_rectangle 0 rest 815 (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 0 815) (firstBOneOuterAUpper 815)
      (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 815 1 2 1
        (firstBOneOuterALower 0 815) (firstBOneOuterAUpper 815) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 815 1 z 1
      (firstBOneOuterALower 0 815) (firstBOneOuterAUpper 815) (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d rectangle corners root_eq).elim
  · have rectangle := firstBOneOuter_envelope_rectangle 1 j rest 815 k_le_j (by omega)
    change FirstBTwoTailRectangle
      (firstBOneOuterALower 1 815) (firstBOneOuterAUpper 815)
      39 (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 210 815 0 1 1
        (firstBOneOuterALower 1 815) (firstBOneOuterAUpper 815) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
        firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
        firstBTwoTailZDenominator, firstBTwoTailZNumerator]
    exact (firstBTwoTailZ_no_nat_of_gap 210 815 0 z 1
      (firstBOneOuterALower 1 815) (firstBOneOuterAUpper 815) 39 (firstBTwoTailDUpper 1) a d
        rectangle corners root_eq).elim

private theorem firstBOneOuter_root_210_816
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail 816)
          (firstBOneOuterD tail) 210 816 * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail 816)
          (firstBOneOuterD tail) 210 816) :
    FirstBOneOuterCandidate 210 j 816 z := by
  let tail := List.replicate j .c ++ .b :: rest
  let a := firstBOneOuterA tail 816
  let d := firstBOneOuterD tail
  change firstBTwoTailZDenominator a d 210 816 * z =
    firstBTwoTailZNumerator a d 210 816 at root_eq
  have k_le_j : 0 ≤ j := Nat.zero_le j
  have rectangle := firstBOneOuter_envelope_rectangle 0 j rest 816 k_le_j (by omega)
  change FirstBTwoTailRectangle
    (firstBOneOuterALower 0 816) (firstBOneOuterAUpper 816)
    39 (firstBTwoTailDUpper 0) a d at rectangle
  have corners : FirstBTwoTailOpenCorners 210 816 0 1 1
      (firstBOneOuterALower 0 816) (firstBOneOuterAUpper 816) 39 (firstBTwoTailDUpper 0) := by
    norm_num [FirstBTwoTailOpenCorners, firstBOneOuterALower,
      firstBOneOuterAUpper, firstBTwoTailDLower, firstBTwoTailDUpper,
      firstBTwoTailZDenominator, firstBTwoTailZNumerator]
  exact (firstBTwoTailZ_no_nat_of_gap 210 816 0 z 1
    (firstBOneOuterALower 0 816) (firstBOneOuterAUpper 816) 39 (firstBTwoTailDUpper 0) a d rectangle
      corners root_eq).elim

/-- Exact tail classification on certificate shard 2. -/
theorem firstBOneOuter_candidate_shard_2
    (j : Nat) (rest : List TagLetter) (x y z : Nat)
    (candidate : FirstBOneOuterRootCandidate x y)
    (chamber_range : x = 210 ∧ y ≤ 816)
    (root_eq :
      let tail := List.replicate j .c ++ .b :: rest
      firstBTwoTailZDenominator (firstBOneOuterA tail y)
          (firstBOneOuterD tail) x y * z =
        firstBTwoTailZNumerator (firstBOneOuterA tail y)
          (firstBOneOuterD tail) x y) :
    FirstBOneOuterCandidate x j y z := by
  unfold FirstBOneOuterRootCandidate at candidate
  rcases candidate with c134 | c146 | c169 | c171 | c180 | c184 | c189 | c192 | c194 | c195 | c198 |
    c200 | c201 | c202 | c203 | c204 | c205 | c206 | c207 | c208 | c209 | c210
  · rcases c134 with ⟨rfl, rfl⟩
    omega
  · rcases c146 with ⟨rfl, rfl⟩
    omega
  · rcases c169 with ⟨rfl, rfl⟩
    omega
  · rcases c171 with ⟨rfl, rfl⟩
    omega
  · rcases c180 with ⟨rfl, rfl⟩
    omega
  · rcases c184 with ⟨rfl, rfl⟩
    omega
  · rcases c189 with ⟨rfl, rfl⟩
    omega
  · rcases c192 with ⟨rfl, rfl⟩
    omega
  · rcases c194 with ⟨rfl, rfl⟩
    omega
  · rcases c195 with ⟨rfl, rfl⟩
    omega
  · rcases c198 with ⟨rfl, rfl⟩
    omega
  · rcases c200 with ⟨rfl, rfl⟩
    omega
  · rcases c201 with ⟨rfl, rfl⟩
    omega
  · rcases c202 with ⟨rfl, y_lower, y_upper⟩
    omega
  · rcases c203 with ⟨rfl, rfl⟩
    omega
  · rcases c204 with ⟨rfl, rfl⟩
    omega
  · rcases c205 with ⟨rfl, y_lower, y_upper⟩
    omega
  · rcases c206 with ⟨rfl, y_lower, y_upper⟩
    omega
  · rcases c207 with ⟨rfl, y_lower, y_upper⟩
    omega
  · rcases c208 with ⟨rfl, y_lower, y_upper⟩
    omega
  · rcases c209 with ⟨rfl, y_lower, y_upper⟩
    omega
  · rcases c210 with ⟨rfl, y_lower, y_upper⟩
    interval_cases y
    · exact firstBOneOuter_root_210_796 j rest z root_eq
    · exact firstBOneOuter_root_210_797 j rest z root_eq
    · exact firstBOneOuter_root_210_798 j rest z root_eq
    · exact firstBOneOuter_root_210_799 j rest z root_eq
    · exact firstBOneOuter_root_210_800 j rest z root_eq
    · exact firstBOneOuter_root_210_801 j rest z root_eq
    · exact firstBOneOuter_root_210_802 j rest z root_eq
    · exact firstBOneOuter_root_210_803 j rest z root_eq
    · exact firstBOneOuter_root_210_804 j rest z root_eq
    · exact firstBOneOuter_root_210_805 j rest z root_eq
    · exact firstBOneOuter_root_210_806 j rest z root_eq
    · exact firstBOneOuter_root_210_807 j rest z root_eq
    · exact firstBOneOuter_root_210_808 j rest z root_eq
    · exact firstBOneOuter_root_210_809 j rest z root_eq
    · exact firstBOneOuter_root_210_810 j rest z root_eq
    · exact firstBOneOuter_root_210_811 j rest z root_eq
    · exact firstBOneOuter_root_210_812 j rest z root_eq
    · exact firstBOneOuter_root_210_813 j rest z root_eq
    · exact firstBOneOuter_root_210_814 j rest z root_eq
    · exact firstBOneOuter_root_210_815 j rest z root_eq
    · exact firstBOneOuter_root_210_816 j rest z root_eq
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega
    · omega

-- END GENERATED FIRST-B-ONE-OUTER TAIL CERTIFICATE

end MatrixMortality.ParabolicBlade
