import MatrixMortality.ParabolicFirstBZeroOuter
import MatrixMortality.ParabolicFirstBZeroReductionCertificate0
import MatrixMortality.ParabolicFirstBZeroReductionCertificate1
import MatrixMortality.ParabolicFirstBZeroReductionCertificate2
import MatrixMortality.ParabolicFirstBZeroReductionCertificate3
import MatrixMortality.ParabolicFirstBZeroReductionCertificate4
import MatrixMortality.ParabolicFirstBZeroReductionCertificate5
import MatrixMortality.ParabolicFirstBZeroReductionCertificate6
import MatrixMortality.ParabolicFirstBZeroReductionCertificate7
import MatrixMortality.ParabolicFirstBZeroReductionCertificate8
import MatrixMortality.ParabolicFirstBZeroReductionCertificate9
import MatrixMortality.ParabolicFirstBZeroReductionCertificate10
import MatrixMortality.ParabolicFirstBZeroReductionCertificate11
import MatrixMortality.ParabolicFirstBZeroReductionCertificate12
import MatrixMortality.ParabolicFirstBZeroReductionCertificate13
import MatrixMortality.ParabolicFirstBZeroReductionCertificate14
import MatrixMortality.ParabolicFirstBZeroReductionCertificate15
import MatrixMortality.ParabolicFirstBZeroReductionCertificate16
import MatrixMortality.ParabolicFirstBZeroReductionCertificate17
import MatrixMortality.ParabolicFirstBZeroReductionCertificate18
import MatrixMortality.ParabolicFirstBZeroReductionCertificate19
import MatrixMortality.ParabolicFirstBZeroReductionCertificate20
import MatrixMortality.ParabolicFirstBZeroReductionCertificate21

/-!
# Leading-`b` tail reduction shard 22

This file is generated by `scripts/generate-parabolic-first-b-zero-reduction.py`.
-/

namespace MatrixMortality.ParabolicBlade

set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8163
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8163)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8163 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8163)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8163) :
    FirstBZeroTailCandidate 203 8163 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8163
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8163 * z =
        firstBTwoTailZNumerator a d 203 8163 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8163 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8163) (firstBLateTailABase 0 8163)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8163 1 3 1
          (firstBLateTailALower 0 0 8163) (firstBLateTailABase 0 8163) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8163 1 3 z 1
        (firstBLateTailALower 0 0 8163) (firstBLateTailABase 0 8163) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨124, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8163
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8163 * z =
      firstBTwoTailZNumerator a d 203 8163 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8163 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8163) (firstBLateTailABase 0 8163) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8163 0 1 1 (firstBLateTailALower 0 1 8163)
      (firstBLateTailABase 0 8163) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8163 0 z 1
      (firstBLateTailALower 0 1 8163) (firstBLateTailABase 0 8163) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8164
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8164)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8164 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8164)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8164) :
    FirstBZeroTailCandidate 203 8164 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8164
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8164 * z =
        firstBTwoTailZNumerator a d 203 8164 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8164 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8164) (firstBLateTailABase 0 8164)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8164 1 3 1
          (firstBLateTailALower 0 0 8164) (firstBLateTailABase 0 8164) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8164 1 3 z 1
        (firstBLateTailALower 0 0 8164) (firstBLateTailABase 0 8164) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨125, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8164
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8164 * z =
      firstBTwoTailZNumerator a d 203 8164 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8164 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8164) (firstBLateTailABase 0 8164) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8164 0 1 1 (firstBLateTailALower 0 1 8164)
      (firstBLateTailABase 0 8164) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8164 0 z 1
      (firstBLateTailALower 0 1 8164) (firstBLateTailABase 0 8164) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8165
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8165)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8165 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8165)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8165) :
    FirstBZeroTailCandidate 203 8165 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8165
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8165 * z =
        firstBTwoTailZNumerator a d 203 8165 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8165 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8165) (firstBLateTailABase 0 8165)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8165 1 3 1
          (firstBLateTailALower 0 0 8165) (firstBLateTailABase 0 8165) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8165 1 3 z 1
        (firstBLateTailALower 0 0 8165) (firstBLateTailABase 0 8165) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨126, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8165
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8165 * z =
      firstBTwoTailZNumerator a d 203 8165 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8165 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8165) (firstBLateTailABase 0 8165) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8165 0 1 1 (firstBLateTailALower 0 1 8165)
      (firstBLateTailABase 0 8165) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8165 0 z 1
      (firstBLateTailALower 0 1 8165) (firstBLateTailABase 0 8165) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8166
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8166)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8166 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8166)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8166) :
    FirstBZeroTailCandidate 203 8166 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8166
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8166 * z =
        firstBTwoTailZNumerator a d 203 8166 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8166 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8166) (firstBLateTailABase 0 8166)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8166 1 3 1
          (firstBLateTailALower 0 0 8166) (firstBLateTailABase 0 8166) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8166 1 3 z 1
        (firstBLateTailALower 0 0 8166) (firstBLateTailABase 0 8166) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨127, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8166
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8166 * z =
      firstBTwoTailZNumerator a d 203 8166 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8166 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8166) (firstBLateTailABase 0 8166) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8166 0 1 1 (firstBLateTailALower 0 1 8166)
      (firstBLateTailABase 0 8166) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8166 0 z 1
      (firstBLateTailALower 0 1 8166) (firstBLateTailABase 0 8166) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_8167_8221
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 8167 ≤ y) (y_upper : y ≤ 8221)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (8167 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 8221 := by exact_mod_cast y_upper
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 1 2 1 (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 1 z 1
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
  · have position_bound : 1 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 1 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
      (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8222
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8222)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8222 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8222)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8222) :
    FirstBZeroTailCandidate 203 8222 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8222
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8222 * z =
        firstBTwoTailZNumerator a d 203 8222 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8222 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8222) (firstBLateTailABase 0 8222)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8222 0 2 1
          (firstBLateTailALower 0 0 8222) (firstBLateTailABase 0 8222) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8222 0 2 z 1
        (firstBLateTailALower 0 0 8222) (firstBLateTailABase 0 8222) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨128, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8222
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8222 * z =
      firstBTwoTailZNumerator a d 203 8222 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8222 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8222) (firstBLateTailABase 0 8222) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8222 0 1 1 (firstBLateTailALower 0 1 8222)
      (firstBLateTailABase 0 8222) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8222 0 z 1
      (firstBLateTailALower 0 1 8222) (firstBLateTailABase 0 8222) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8223
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8223)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8223 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8223)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8223) :
    FirstBZeroTailCandidate 203 8223 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8223
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8223 * z =
        firstBTwoTailZNumerator a d 203 8223 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8223 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8223) (firstBLateTailABase 0 8223)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8223 0 2 1
          (firstBLateTailALower 0 0 8223) (firstBLateTailABase 0 8223) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8223 0 2 z 1
        (firstBLateTailALower 0 0 8223) (firstBLateTailABase 0 8223) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨129, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8223
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8223 * z =
      firstBTwoTailZNumerator a d 203 8223 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8223 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8223) (firstBLateTailABase 0 8223) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8223 0 1 1 (firstBLateTailALower 0 1 8223)
      (firstBLateTailABase 0 8223) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8223 0 z 1
      (firstBLateTailALower 0 1 8223) (firstBLateTailABase 0 8223) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8224
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8224)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8224 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8224)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8224) :
    FirstBZeroTailCandidate 203 8224 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8224
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8224 * z =
        firstBTwoTailZNumerator a d 203 8224 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8224 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8224) (firstBLateTailABase 0 8224)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8224 0 2 1
          (firstBLateTailALower 0 0 8224) (firstBLateTailABase 0 8224) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8224 0 2 z 1
        (firstBLateTailALower 0 0 8224) (firstBLateTailABase 0 8224) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨130, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8224
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8224 * z =
      firstBTwoTailZNumerator a d 203 8224 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8224 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8224) (firstBLateTailABase 0 8224) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8224 0 1 1 (firstBLateTailALower 0 1 8224)
      (firstBLateTailABase 0 8224) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8224 0 z 1
      (firstBLateTailALower 0 1 8224) (firstBLateTailABase 0 8224) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8225
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8225)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8225 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8225)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8225) :
    FirstBZeroTailCandidate 203 8225 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8225
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8225 * z =
        firstBTwoTailZNumerator a d 203 8225 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8225 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8225) (firstBLateTailABase 0 8225)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8225 0 2 1
          (firstBLateTailALower 0 0 8225) (firstBLateTailABase 0 8225) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8225 0 2 z 1
        (firstBLateTailALower 0 0 8225) (firstBLateTailABase 0 8225) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨131, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8225
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8225 * z =
      firstBTwoTailZNumerator a d 203 8225 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8225 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8225) (firstBLateTailABase 0 8225) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8225 0 1 1 (firstBLateTailALower 0 1 8225)
      (firstBLateTailABase 0 8225) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8225 0 z 1
      (firstBLateTailALower 0 1 8225) (firstBLateTailABase 0 8225) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8226
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8226)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8226 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8226)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8226) :
    FirstBZeroTailCandidate 203 8226 j z := by
  by_cases position_small : j < 1
  · have position_bound : j ≤ 0 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8226
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8226 * z =
        firstBTwoTailZNumerator a d 203 8226 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8226 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8226) (firstBLateTailABase 0 8226)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8226 0 2 1
          (firstBLateTailALower 0 0 8226) (firstBLateTailABase 0 8226) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8226 0 2 z 1
        (firstBLateTailALower 0 0 8226) (firstBLateTailABase 0 8226) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨132, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
  · have position_bound : 1 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8226
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8226 * z =
      firstBTwoTailZNumerator a d 203 8226 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 1 j rest 8226 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8226) (firstBLateTailABase 0 8226) 39
      (firstBTwoTailDUpper 1) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 8226 0 1 1 (firstBLateTailALower 0 1 8226)
      (firstBLateTailABase 0 8226) 39 (firstBTwoTailDUpper 1) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 8226 0 z 1
      (firstBLateTailALower 0 1 8226) (firstBLateTailABase 0 8226) 39 (firstBTwoTailDUpper 1)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_8227
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8227)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8227 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 8227)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 8227) :
    FirstBZeroTailCandidate 203 8227 j z := by
  by_cases position_small : j < 8
  · have position_bound : j ≤ 7 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 8227
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8227 * z =
        firstBTwoTailZNumerator a d 203 8227 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 0 rest 8227 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 8227) (firstBLateTailABase 0 8227)
        (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 8227 0 2 1
          (firstBLateTailALower 0 0 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 0)
            (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 8227 0 2 z 1
        (firstBLateTailALower 0 0 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
      refine ⟨133, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 8227
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8227 * z =
        firstBTwoTailZNumerator a d 203 8227 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest 8227 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 8227) (firstBLateTailABase 0 8227)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 8227 0 1 1 (firstBLateTailALower 0 1 8227)
        (firstBLateTailABase 0 8227) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 8227 0 z 1
        (firstBLateTailALower 0 1 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) 8227
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8227 * z =
        firstBTwoTailZNumerator a d 203 8227 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest 8227 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 8227) (firstBLateTailABase 0 8227)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 8227 0 1 1 (firstBLateTailALower 0 2 8227)
        (firstBLateTailABase 0 8227) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 8227 0 z 1
        (firstBLateTailALower 0 2 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) 8227
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8227 * z =
        firstBTwoTailZNumerator a d 203 8227 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest 8227 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 8227) (firstBLateTailABase 0 8227)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 8227 0 1 1 (firstBLateTailALower 0 3 8227)
        (firstBLateTailABase 0 8227) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 8227 0 z 1
        (firstBLateTailALower 0 3 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) 8227
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8227 * z =
        firstBTwoTailZNumerator a d 203 8227 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest 8227 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 8227) (firstBLateTailABase 0 8227)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 8227 0 1 1 (firstBLateTailALower 0 4 8227)
        (firstBLateTailABase 0 8227) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 8227 0 z 1
        (firstBLateTailALower 0 4 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) 8227
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8227 * z =
        firstBTwoTailZNumerator a d 203 8227 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 5 rest 8227 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 8227) (firstBLateTailABase 0 8227)
        (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 8227 0 1 1 (firstBLateTailALower 0 5 8227)
        (firstBLateTailABase 0 8227) (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 8227 0 z 1
        (firstBLateTailALower 0 5 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 6 .c ++ .b :: rest) 8227
      let d := firstBTwoTailD
        (List.replicate 6 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8227 * z =
        firstBTwoTailZNumerator a d 203 8227 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 6 rest 8227 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 6 8227) (firstBLateTailABase 0 8227)
        (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 8227 0 1 1 (firstBLateTailALower 0 6 8227)
        (firstBLateTailABase 0 8227) (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 8227 0 z 1
        (firstBLateTailALower 0 6 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 7 .c ++ .b :: rest) 8227
      let d := firstBTwoTailD
        (List.replicate 7 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 8227 * z =
        firstBTwoTailZNumerator a d 203 8227 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 7 rest 8227 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 7 8227) (firstBLateTailABase 0 8227)
        (firstBTwoTailDLower 7)
        (firstBTwoTailDUpper 7) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 8227 0 1 1 (firstBLateTailALower 0 7 8227)
        (firstBLateTailABase 0 8227) (firstBTwoTailDLower 7) (firstBTwoTailDUpper 7) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 8227 0 z 1
        (firstBLateTailALower 0 7 8227) (firstBLateTailABase 0 8227) (firstBTwoTailDLower 7)
          (firstBTwoTailDUpper 7)
        a d rectangle corners root_eq
  · have position_bound : 8 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 8227
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 8227 * z =
      firstBTwoTailZNumerator a d 203 8227 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 8 j rest 8227 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 8 8227) (firstBLateTailABase 0 8227) 39
      (firstBTwoTailDUpper 8) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 203 8227 1 (firstBLateTailALower 0 8 8227)
      (firstBLateTailABase 0 8227) 39 (firstBTwoTailDUpper 8) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_negative 203 8227 z 1
      (firstBLateTailALower 0 8 8227) (firstBLateTailABase 0 8227) 39 (firstBTwoTailDUpper 8)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_8228_8228
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 8228 ≤ y) (y_upper : y ≤ 8228)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (8228 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 8228 := by exact_mod_cast y_upper
  by_cases position_small : j < 7
  · have position_bound : j ≤ 6 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 3 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 4 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 5 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 5 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 6 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 6 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 6 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 6 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6)
        a d rectangle corners root_eq
  · have position_bound : 7 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 7 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 7) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 203 y 1 (firstBLateTailALower 0 7 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 7) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_negative 203 y z 1
      (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 7)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_8229_8232
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 8229 ≤ y) (y_upper : y ≤ 8232)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (8229 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 8232 := by exact_mod_cast y_upper
  by_cases position_small : j < 6
  · have position_bound : j ≤ 5 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 3 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 4 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 5 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 5 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
  · have position_bound : 6 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 6 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 6) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 203 y 1 (firstBLateTailALower 0 6 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 6) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_negative 203 y z 1
      (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 6)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_8233_8243
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 8233 ≤ y) (y_upper : y ≤ 8243)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (8233 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 8243 := by exact_mod_cast y_upper
  by_cases position_small : j < 5
  · have position_bound : j ≤ 4 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 3 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 0 1 1 (firstBLateTailALower 0 4 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 0 z 1
        (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
  · have position_bound : 5 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 5 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 5) a d at rectangle
    have corners : FirstBTwoTailNegativeCorners 203 y 1 (firstBLateTailALower 0 5 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 5) := by
      norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_negative 203 y z 1
      (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 5)
      a d rectangle corners root_eq

end MatrixMortality.ParabolicBlade
