import MatrixMortality.ParabolicFirstBZeroOuter
import MatrixMortality.ParabolicFirstBZeroReductionCertificate0
import MatrixMortality.ParabolicFirstBZeroReductionCertificate1
import MatrixMortality.ParabolicFirstBZeroReductionCertificate2
import MatrixMortality.ParabolicFirstBZeroReductionCertificate3
import MatrixMortality.ParabolicFirstBZeroReductionCertificate4
import MatrixMortality.ParabolicFirstBZeroReductionCertificate5
import MatrixMortality.ParabolicFirstBZeroReductionCertificate6
import MatrixMortality.ParabolicFirstBZeroReductionCertificate7
import MatrixMortality.ParabolicFirstBZeroReductionCertificate8

/-!
# Leading-`b` tail reduction shard 9

This file is generated by `scripts/generate-parabolic-first-b-zero-reduction.py`.
-/

namespace MatrixMortality.ParabolicBlade

set_option maxHeartbeats 2000000 in
/-- One generated outer-root survivor enters its exact indexed terminal chamber. -/
theorem firstBZeroTail_candidate_203_6955
    (j : Nat) (rest : List TagLetter) (z : Nat)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 6955)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 6955 * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) 6955)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 6955) :
    FirstBZeroTailCandidate 203 6955 j z := by
  by_cases position_small : j < 8
  · have position_bound : j ≤ 7 := by omega
    interval_cases j
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) 6955
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 6955 * z =
        firstBTwoTailZNumerator a d 203 6955 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest 6955 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 6955) (firstBLateTailABase 0 6955)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 6955 (-1) (firstBLateTailALower 0 0 6955)
        (firstBLateTailABase 0 6955) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 6955 z (-1)
        (firstBLateTailALower 0 0 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) 6955
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 6955 * z =
        firstBTwoTailZNumerator a d 203 6955 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest 6955 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 6955) (firstBLateTailABase 0 6955)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 6955 (-1) (firstBLateTailALower 0 1 6955)
        (firstBLateTailABase 0 6955) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 6955 z (-1)
        (firstBLateTailALower 0 1 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) 6955
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 6955 * z =
        firstBTwoTailZNumerator a d 203 6955 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest 6955 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 6955) (firstBLateTailABase 0 6955)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 6955 (-1) (firstBLateTailALower 0 2 6955)
        (firstBLateTailABase 0 6955) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 6955 z (-1)
        (firstBLateTailALower 0 2 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) 6955
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 6955 * z =
        firstBTwoTailZNumerator a d 203 6955 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest 6955 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 6955) (firstBLateTailABase 0 6955)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 6955 (-1) (firstBLateTailALower 0 3 6955)
        (firstBLateTailABase 0 6955) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 6955 z (-1)
        (firstBLateTailALower 0 3 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) 6955
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 6955 * z =
        firstBTwoTailZNumerator a d 203 6955 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest 6955 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 6955) (firstBLateTailABase 0 6955)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 6955 (-1) (firstBLateTailALower 0 4 6955)
        (firstBLateTailABase 0 6955) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_negative 203 6955 z (-1)
        (firstBLateTailALower 0 4 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) 6955
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 6955 * z =
        firstBTwoTailZNumerator a d 203 6955 at root_eq
      have rectangle := firstBLateTail_exact_rectangle
        0 5 rest 6955 (by norm_num)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 6955) (firstBLateTailABase 0 6955)
        (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners
          203 6955 85 88 1
          (firstBLateTailALower 0 5 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 5)
            (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners,
          firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper,
          firstBTwoTailZDenominator, firstBTwoTailZNumerator,
          firstBLatePrefixScale]
      have z_interval := firstBTwoTailZ_mem_open_interval
        203 6955 85 88 z 1
        (firstBLateTailALower 0 5 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
      refine ⟨18, by norm_num, ?_, ?_, ?_, ?_, ?_⟩
      · norm_num [firstBZeroTailX]
      · norm_num [firstBZeroTailY]
      · norm_num [firstBZeroTailPosition]
      · norm_num [firstBZeroTailLower]
      · norm_num [firstBZeroTailUpper]
        omega
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 6 .c ++ .b :: rest) 6955
      let d := firstBTwoTailD
        (List.replicate 6 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 6955 * z =
        firstBTwoTailZNumerator a d 203 6955 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 6 rest 6955 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 6 6955) (firstBLateTailABase 0 6955)
        (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 6955 25 26 1 (firstBLateTailALower 0 6 6955)
        (firstBLateTailABase 0 6955) (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 6955 25 z 1
        (firstBLateTailALower 0 6 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6)
        a d rectangle corners root_eq
    · exfalso
      let a := firstBLateTailA 0
        (List.replicate 7 .c ++ .b :: rest) 6955
      let d := firstBTwoTailD
        (List.replicate 7 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 6955 * z =
        firstBTwoTailZNumerator a d 203 6955 at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 7 rest 6955 (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 7 6955) (firstBLateTailABase 0 6955)
        (firstBTwoTailDLower 7)
        (firstBTwoTailDUpper 7) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 6955 20 21 1 (firstBLateTailALower 0 7 6955)
        (firstBLateTailABase 0 6955) (firstBTwoTailDLower 7) (firstBTwoTailDUpper 7) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
      exact firstBTwoTailZ_no_nat_of_gap 203 6955 20 z 1
        (firstBLateTailALower 0 7 6955) (firstBLateTailABase 0 6955) (firstBTwoTailDLower 7)
          (firstBTwoTailDUpper 7)
        a d rectangle corners root_eq
  · have position_bound : 8 ≤ j := by omega
    exfalso
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) 6955
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 6955 * z =
      firstBTwoTailZNumerator a d 203 6955 at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 8 j rest 6955 position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 8 6955) (firstBLateTailABase 0 6955) 39
      (firstBTwoTailDUpper 8) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 6955 19 20 1 (firstBLateTailALower 0 8 6955)
      (firstBLateTailABase 0 6955) 39 (firstBTwoTailDUpper 8) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
    exact firstBTwoTailZ_no_nat_of_gap 203 6955 19 z 1
      (firstBLateTailALower 0 8 6955) (firstBLateTailABase 0 6955) 39 (firstBTwoTailDUpper 8)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_6956_6956
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 6956 ≤ y) (y_upper : y ≤ 6956)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (6956 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 6956 := by exact_mod_cast y_upper
  by_cases position_small : j < 8
  · have position_bound : j ≤ 7 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 3 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 4 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 5 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 46 47 1 (firstBLateTailALower 0 5 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 46 z 1
        (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 6 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 6 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 6 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 20 21 1 (firstBLateTailALower 0 6 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 20 z 1
        (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 7 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 7 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 7 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 7)
        (firstBTwoTailDUpper 7) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 17 18 1 (firstBLateTailALower 0 7 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 7) (firstBTwoTailDUpper 7) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 17 z 1
        (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 7)
          (firstBTwoTailDUpper 7)
        a d rectangle corners root_eq
  · have position_bound : 8 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 8 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 8 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 8) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 16 17 1 (firstBLateTailALower 0 8 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 8) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 16 z 1
      (firstBLateTailALower 0 8 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 8)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_6957_6957
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 6957 ≤ y) (y_upper : y ≤ 6957)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (6957 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 6957 := by exact_mod_cast y_upper
  by_cases position_small : j < 9
  · have position_bound : j ≤ 8 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 3 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 4 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 5 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 31 32 1 (firstBLateTailALower 0 5 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 31 z 1
        (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 6 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 6 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 6 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 17 18 1 (firstBLateTailALower 0 6 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 17 z 1
        (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 7 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 7 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 7 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 7)
        (firstBTwoTailDUpper 7) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 14 15 1 (firstBLateTailALower 0 7 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 7) (firstBTwoTailDUpper 7) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 14 z 1
        (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 7)
          (firstBTwoTailDUpper 7)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 8 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 8 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 8 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 8 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 8)
        (firstBTwoTailDUpper 8) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 14 15 1 (firstBLateTailALower 0 8 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 8) (firstBTwoTailDUpper 8) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 14 z 1
        (firstBLateTailALower 0 8 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 8)
          (firstBTwoTailDUpper 8)
        a d rectangle corners root_eq
  · have position_bound : 9 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 9 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 9 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 9) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 13 14 1 (firstBLateTailALower 0 9 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 9) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 13 z 1
      (firstBLateTailALower 0 9 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 9)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_6958_6958
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 6958 ≤ y) (y_upper : y ≤ 6958)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (6958 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 6958 := by exact_mod_cast y_upper
  by_cases position_small : j < 7
  · have position_bound : j ≤ 6 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 3 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 4 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 5 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 24 25 1 (firstBLateTailALower 0 5 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 24 z 1
        (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 6 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 6 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 6 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 14 15 1 (firstBLateTailALower 0 6 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 14 z 1
        (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6)
        a d rectangle corners root_eq
  · have position_bound : 7 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 7 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 7) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 12 13 1 (firstBLateTailALower 0 7 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 7) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 12 z 1
      (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 7)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_6959_6959
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 6959 ≤ y) (y_upper : y ≤ 6959)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (6959 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 6959 := by exact_mod_cast y_upper
  by_cases position_small : j < 9
  · have position_bound : j ≤ 8 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 3 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 4 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 5 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 19 20 1 (firstBLateTailALower 0 5 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 19 z 1
        (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 6 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 6 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 6 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 12 13 1 (firstBLateTailALower 0 6 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 12 z 1
        (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 7 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 7 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 7 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 7)
        (firstBTwoTailDUpper 7) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 11 12 1 (firstBLateTailALower 0 7 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 7) (firstBTwoTailDUpper 7) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 11 z 1
        (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 7)
          (firstBTwoTailDUpper 7)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 8 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 8 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 8 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 8 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 8)
        (firstBTwoTailDUpper 8) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 11 12 1 (firstBLateTailALower 0 8 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 8) (firstBTwoTailDUpper 8) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 11 z 1
        (firstBLateTailALower 0 8 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 8)
          (firstBTwoTailDUpper 8)
        a d rectangle corners root_eq
  · have position_bound : 9 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 9 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 9 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 9) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 10 11 1 (firstBLateTailALower 0 9 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 9) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 10 z 1
      (firstBLateTailALower 0 9 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 9)
      a d rectangle corners root_eq
set_option maxHeartbeats 2000000 in
/-- A generated maximal middle-wait range has no natural tail root. -/
theorem firstBZeroTail_false_203_6960_6960
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 6960 ≤ y) (y_upper : y ≤ 6960)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    False := by
  have y_lower_rat : (6960 : ℚ) ≤ y := by exact_mod_cast y_lower
  have y_upper_rat : (y : ℚ) ≤ 6960 := by exact_mod_cast y_upper
  by_cases position_small : j < 8
  · have position_bound : j ≤ 7 := by omega
    interval_cases j
    · let a := firstBLateTailA 0
        (List.replicate 0 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 0 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 0 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 0)
        (firstBTwoTailDUpper 0) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 0 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 0) (firstBTwoTailDUpper 0) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 0 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 0)
          (firstBTwoTailDUpper 0)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 1 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 1 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 1 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 1)
        (firstBTwoTailDUpper 1) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 1 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 1) (firstBTwoTailDUpper 1) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 1 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 1)
          (firstBTwoTailDUpper 1)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 2 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 2 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 2 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 2)
        (firstBTwoTailDUpper 2) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 2 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 2) (firstBTwoTailDUpper 2) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 2 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 2)
          (firstBTwoTailDUpper 2)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 3 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 3 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 3 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 3)
        (firstBTwoTailDUpper 3) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 3 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 3) (firstBTwoTailDUpper 3) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 3 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 3)
          (firstBTwoTailDUpper 3)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 4 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 4 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 4 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 4)
        (firstBTwoTailDUpper 4) a d at rectangle
      have corners : FirstBTwoTailNegativeCorners 203 y (-1) (firstBLateTailALower 0 4 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 4) (firstBTwoTailDUpper 4) := by
        norm_num [FirstBTwoTailNegativeCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_negative 203 y z (-1)
        (firstBLateTailALower 0 4 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 4)
          (firstBTwoTailDUpper 4)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 5 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 5 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 5 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 5)
        (firstBTwoTailDUpper 5) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 16 17 1 (firstBLateTailALower 0 5 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 5) (firstBTwoTailDUpper 5) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 16 z 1
        (firstBLateTailALower 0 5 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 5)
          (firstBTwoTailDUpper 5)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 6 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 6 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 6 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 6)
        (firstBTwoTailDUpper 6) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 11 12 1 (firstBLateTailALower 0 6 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 6) (firstBTwoTailDUpper 6) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 11 z 1
        (firstBLateTailALower 0 6 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 6)
          (firstBTwoTailDUpper 6)
        a d rectangle corners root_eq
    · let a := firstBLateTailA 0
        (List.replicate 7 .c ++ .b :: rest) y
      let d := firstBTwoTailD
        (List.replicate 7 .c ++ .b :: rest)
      change firstBTwoTailZDenominator a d 203 y * z =
        firstBTwoTailZNumerator a d 203 y at root_eq
      have rectangle := firstBLateTail_exact_rectangle 0 7 rest y (by omega)
      dsimp only at rectangle
      change FirstBTwoTailRectangle (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y)
        (firstBTwoTailDLower 7)
        (firstBTwoTailDUpper 7) a d at rectangle
      have corners : FirstBTwoTailOpenCorners 203 y 10 11 1 (firstBLateTailALower 0 7 y)
        (firstBLateTailABase 0 y) (firstBTwoTailDLower 7) (firstBTwoTailDUpper 7) := by
        norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
          firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
          firstBTwoTailZNumerator, firstBLatePrefixScale]
        (repeat' apply And.intro) <;> nlinarith
      exact firstBTwoTailZ_no_nat_of_gap 203 y 10 z 1
        (firstBLateTailALower 0 7 y) (firstBLateTailABase 0 y) (firstBTwoTailDLower 7)
          (firstBTwoTailDUpper 7)
        a d rectangle corners root_eq
  · have position_bound : 8 ≤ j := by omega
    let a := firstBLateTailA 0
      (List.replicate j .c ++ .b :: rest) y
    let d := firstBTwoTailD
      (List.replicate j .c ++ .b :: rest)
    change firstBTwoTailZDenominator a d 203 y * z =
      firstBTwoTailZNumerator a d 203 y at root_eq
    have rectangle := firstBLateTail_envelope_rectangle 0 8 j rest y position_bound (by omega)
    dsimp only at rectangle
    change FirstBTwoTailRectangle (firstBLateTailALower 0 8 y) (firstBLateTailABase 0 y) 39
      (firstBTwoTailDUpper 8) a d at rectangle
    have corners : FirstBTwoTailOpenCorners 203 y 9 10 1 (firstBLateTailALower 0 8 y)
      (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 8) := by
      norm_num [FirstBTwoTailOpenCorners, firstBLateTailALower, firstBLateTailABase,
        firstBTwoTailDLower, firstBTwoTailDUpper, firstBTwoTailZDenominator,
        firstBTwoTailZNumerator, firstBLatePrefixScale]
      (repeat' apply And.intro) <;> nlinarith
    exact firstBTwoTailZ_no_nat_of_gap 203 y 9 z 1
      (firstBLateTailALower 0 8 y) (firstBLateTailABase 0 y) 39 (firstBTwoTailDUpper 8)
      a d rectangle corners root_eq

end MatrixMortality.ParabolicBlade
