import MatrixMortality.ParabolicFirstBZeroOuter
import MatrixMortality.ParabolicFirstBZeroReductionCertificate0
import MatrixMortality.ParabolicFirstBZeroReductionCertificate1
import MatrixMortality.ParabolicFirstBZeroReductionCertificate2
import MatrixMortality.ParabolicFirstBZeroReductionCertificate3
import MatrixMortality.ParabolicFirstBZeroReductionCertificate4
import MatrixMortality.ParabolicFirstBZeroReductionCertificate5
import MatrixMortality.ParabolicFirstBZeroReductionCertificate6
import MatrixMortality.ParabolicFirstBZeroReductionCertificate7
import MatrixMortality.ParabolicFirstBZeroReductionCertificate8
import MatrixMortality.ParabolicFirstBZeroReductionCertificate9
import MatrixMortality.ParabolicFirstBZeroReductionCertificate10
import MatrixMortality.ParabolicFirstBZeroReductionCertificate11
import MatrixMortality.ParabolicFirstBZeroReductionCertificate12
import MatrixMortality.ParabolicFirstBZeroReductionCertificate13
import MatrixMortality.ParabolicFirstBZeroReductionCertificate14
import MatrixMortality.ParabolicFirstBZeroReductionCertificate15
import MatrixMortality.ParabolicFirstBZeroReductionCertificate16
import MatrixMortality.ParabolicFirstBZeroReductionCertificate17
import MatrixMortality.ParabolicFirstBZeroReductionCertificate18
import MatrixMortality.ParabolicFirstBZeroReductionCertificate19
import MatrixMortality.ParabolicFirstBZeroReductionCertificate20
import MatrixMortality.ParabolicFirstBZeroReductionCertificate21
import MatrixMortality.ParabolicFirstBZeroReductionCertificate22
import MatrixMortality.ParabolicFirstBZeroReductionCertificate23
import MatrixMortality.ParabolicFirstBZeroReductionCertificate24

/-!
# Leading-`b` tail reduction shard 25

This file is generated by `scripts/generate-parabolic-first-b-zero-reduction.py`.
-/

namespace MatrixMortality.ParabolicBlade

/-- One generated outer-wait fiber contracts to the indexed terminal chamber set. -/
theorem firstBZeroTailCandidate_of_outer_203
    (j : Nat) (rest : List TagLetter) (y z : Nat)
    (y_lower : 6950 ≤ y) (y_upper : y ≤ 9880)
    (root_eq : firstBTwoTailZDenominator
      (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
      (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y * z =
        firstBTwoTailZNumerator
          (firstBLateTailA 0 (List.replicate j .c ++ .b :: rest) y)
          (firstBTwoTailD (List.replicate j .c ++ .b :: rest)) 203 y) :
    FirstBZeroTailCandidate 203 y j z := by
  by_cases y_left : y ≤ 7308
  ·
    by_cases y_left : y ≤ 7006
    ·
      by_cases y_left : y ≤ 6974
      ·
        by_cases y_left : y ≤ 6961
        ·
          by_cases y_left : y ≤ 6955
          ·
            by_cases y_left : y ≤ 6952
            ·
              by_cases y_left : y ≤ 6950
              ·
                have y_eq : y = 6950 := by omega
                subst y
                exact firstBZeroTail_candidate_203_6950 j rest z root_eq
              ·
                by_cases y_left : y ≤ 6951
                ·
                  have y_eq : y = 6951 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6951 j rest z root_eq
                ·
                  have y_eq : y = 6952 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6952 j rest z root_eq
            ·
              by_cases y_left : y ≤ 6953
              ·
                exact False.elim (firstBZeroTail_false_203_6953_6953 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6954
                ·
                  have y_eq : y = 6954 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6954 j rest z root_eq
                ·
                  have y_eq : y = 6955 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6955 j rest z root_eq
          ·
            by_cases y_left : y ≤ 6958
            ·
              by_cases y_left : y ≤ 6956
              ·
                exact False.elim (firstBZeroTail_false_203_6956_6956 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6957
                ·
                  exact False.elim (firstBZeroTail_false_203_6957_6957 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_6958_6958 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 6959
              ·
                exact False.elim (firstBZeroTail_false_203_6959_6959 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6960
                ·
                  exact False.elim (firstBZeroTail_false_203_6960_6960 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  have y_eq : y = 6961 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6961 j rest z root_eq
        ·
          by_cases y_left : y ≤ 6967
          ·
            by_cases y_left : y ≤ 6964
            ·
              by_cases y_left : y ≤ 6962
              ·
                have y_eq : y = 6962 := by omega
                subst y
                exact firstBZeroTail_candidate_203_6962 j rest z root_eq
              ·
                by_cases y_left : y ≤ 6963
                ·
                  have y_eq : y = 6963 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6963 j rest z root_eq
                ·
                  have y_eq : y = 6964 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6964 j rest z root_eq
            ·
              by_cases y_left : y ≤ 6965
              ·
                exact False.elim (firstBZeroTail_false_203_6965_6965 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6966
                ·
                  exact False.elim (firstBZeroTail_false_203_6966_6966 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_6967_6967 j rest y z (by omega) (by
                    omega) root_eq)
          ·
            by_cases y_left : y ≤ 6970
            ·
              by_cases y_left : y ≤ 6968
              ·
                exact False.elim (firstBZeroTail_false_203_6968_6968 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6969
                ·
                  exact False.elim (firstBZeroTail_false_203_6969_6969 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_6970_6970 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 6972
              ·
                by_cases y_left : y ≤ 6971
                ·
                  exact False.elim (firstBZeroTail_false_203_6971_6971 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_6972_6972 j rest y z (by omega) (by
                    omega) root_eq)
              ·
                by_cases y_left : y ≤ 6973
                ·
                  exact False.elim (firstBZeroTail_false_203_6973_6973 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_6974_6974 j rest y z (by omega) (by
                    omega) root_eq)
      ·
        by_cases y_left : y ≤ 6991
        ·
          by_cases y_left : y ≤ 6983
          ·
            by_cases y_left : y ≤ 6978
            ·
              by_cases y_left : y ≤ 6975
              ·
                exact False.elim (firstBZeroTail_false_203_6975_6975 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6976
                ·
                  exact False.elim (firstBZeroTail_false_203_6976_6976 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_6977_6978 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 6981
              ·
                exact False.elim (firstBZeroTail_false_203_6979_6981 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6982
                ·
                  exact False.elim (firstBZeroTail_false_203_6982_6982 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_6983_6983 j rest y z (by omega) (by
                    omega) root_eq)
          ·
            by_cases y_left : y ≤ 6988
            ·
              by_cases y_left : y ≤ 6986
              ·
                exact False.elim (firstBZeroTail_false_203_6984_6986 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6987
                ·
                  have y_eq : y = 6987 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6987 j rest z root_eq
                ·
                  have y_eq : y = 6988 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6988 j rest z root_eq
            ·
              by_cases y_left : y ≤ 6989
              ·
                have y_eq : y = 6989 := by omega
                subst y
                exact firstBZeroTail_candidate_203_6989 j rest z root_eq
              ·
                by_cases y_left : y ≤ 6990
                ·
                  have y_eq : y = 6990 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6990 j rest z root_eq
                ·
                  have y_eq : y = 6991 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6991 j rest z root_eq
        ·
          by_cases y_left : y ≤ 6997
          ·
            by_cases y_left : y ≤ 6994
            ·
              by_cases y_left : y ≤ 6992
              ·
                have y_eq : y = 6992 := by omega
                subst y
                exact firstBZeroTail_candidate_203_6992 j rest z root_eq
              ·
                by_cases y_left : y ≤ 6993
                ·
                  have y_eq : y = 6993 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_6993 j rest z root_eq
                ·
                  exact False.elim (firstBZeroTail_false_203_6994_6994 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 6995
              ·
                have y_eq : y = 6995 := by omega
                subst y
                exact firstBZeroTail_candidate_203_6995 j rest z root_eq
              ·
                by_cases y_left : y ≤ 6996
                ·
                  exact False.elim (firstBZeroTail_false_203_6996_6996 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_6997_6997 j rest y z (by omega) (by
                    omega) root_eq)
          ·
            by_cases y_left : y ≤ 7000
            ·
              by_cases y_left : y ≤ 6998
              ·
                exact False.elim (firstBZeroTail_false_203_6998_6998 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 6999
                ·
                  exact False.elim (firstBZeroTail_false_203_6999_6999 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_7000_7000 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 7002
              ·
                by_cases y_left : y ≤ 7001
                ·
                  have y_eq : y = 7001 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7001 j rest z root_eq
                ·
                  exact False.elim (firstBZeroTail_false_203_7002_7002 j rest y z (by omega) (by
                    omega) root_eq)
              ·
                by_cases y_left : y ≤ 7003
                ·
                  exact False.elim (firstBZeroTail_false_203_7003_7003 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_7004_7006 j rest y z (by omega) (by
                    omega) root_eq)
    ·
      by_cases y_left : y ≤ 7078
      ·
        by_cases y_left : y ≤ 7064
        ·
          by_cases y_left : y ≤ 7044
          ·
            by_cases y_left : y ≤ 7019
            ·
              by_cases y_left : y ≤ 7010
              ·
                exact False.elim (firstBZeroTail_false_203_7007_7010 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7011
                ·
                  exact False.elim (firstBZeroTail_false_203_7011_7011 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_7012_7019 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 7035
              ·
                exact False.elim (firstBZeroTail_false_203_7020_7035 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7043
                ·
                  exact False.elim (firstBZeroTail_false_203_7036_7043 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_7044_7044 j rest y z (by omega) (by
                    omega) root_eq)
          ·
            by_cases y_left : y ≤ 7061
            ·
              by_cases y_left : y ≤ 7047
              ·
                exact False.elim (firstBZeroTail_false_203_7045_7047 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7055
                ·
                  exact False.elim (firstBZeroTail_false_203_7048_7055 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_7056_7061 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 7062
              ·
                have y_eq : y = 7062 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7062 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7063
                ·
                  have y_eq : y = 7063 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7063 j rest z root_eq
                ·
                  have y_eq : y = 7064 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7064 j rest z root_eq
        ·
          by_cases y_left : y ≤ 7070
          ·
            by_cases y_left : y ≤ 7067
            ·
              by_cases y_left : y ≤ 7065
              ·
                have y_eq : y = 7065 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7065 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7066
                ·
                  have y_eq : y = 7066 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7066 j rest z root_eq
                ·
                  have y_eq : y = 7067 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7067 j rest z root_eq
            ·
              by_cases y_left : y ≤ 7068
              ·
                have y_eq : y = 7068 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7068 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7069
                ·
                  have y_eq : y = 7069 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7069 j rest z root_eq
                ·
                  have y_eq : y = 7070 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7070 j rest z root_eq
          ·
            by_cases y_left : y ≤ 7073
            ·
              by_cases y_left : y ≤ 7071
              ·
                have y_eq : y = 7071 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7071 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7072
                ·
                  exact False.elim (firstBZeroTail_false_203_7072_7072 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  have y_eq : y = 7073 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7073 j rest z root_eq
            ·
              by_cases y_left : y ≤ 7075
              ·
                by_cases y_left : y ≤ 7074
                ·
                  exact False.elim (firstBZeroTail_false_203_7074_7074 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_7075_7075 j rest y z (by omega) (by
                    omega) root_eq)
              ·
                by_cases y_left : y ≤ 7076
                ·
                  have y_eq : y = 7076 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7076 j rest z root_eq
                ·
                  exact False.elim (firstBZeroTail_false_203_7077_7078 j rest y z (by omega) (by
                    omega) root_eq)
      ·
        by_cases y_left : y ≤ 7295
        ·
          by_cases y_left : y ≤ 7094
          ·
            by_cases y_left : y ≤ 7082
            ·
              by_cases y_left : y ≤ 7080
              ·
                exact False.elim (firstBZeroTail_false_203_7079_7080 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7081
                ·
                  have y_eq : y = 7081 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7081 j rest z root_eq
                ·
                  have y_eq : y = 7082 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7082 j rest z root_eq
            ·
              by_cases y_left : y ≤ 7086
              ·
                exact False.elim (firstBZeroTail_false_203_7083_7086 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7087
                ·
                  have y_eq : y = 7087 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7087 j rest z root_eq
                ·
                  exact False.elim (firstBZeroTail_false_203_7088_7094 j rest y z (by omega) (by
                    omega) root_eq)
          ·
            by_cases y_left : y ≤ 7157
            ·
              by_cases y_left : y ≤ 7095
              ·
                have y_eq : y = 7095 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7095 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7111
                ·
                  exact False.elim (firstBZeroTail_false_203_7096_7111 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_7112_7157 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 7158
              ·
                have y_eq : y = 7158 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7158 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7294
                ·
                  exact False.elim (firstBZeroTail_false_203_7159_7294 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  have y_eq : y = 7295 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7295 j rest z root_eq
        ·
          by_cases y_left : y ≤ 7301
          ·
            by_cases y_left : y ≤ 7298
            ·
              by_cases y_left : y ≤ 7296
              ·
                have y_eq : y = 7296 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7296 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7297
                ·
                  have y_eq : y = 7297 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7297 j rest z root_eq
                ·
                  have y_eq : y = 7298 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7298 j rest z root_eq
            ·
              by_cases y_left : y ≤ 7299
              ·
                have y_eq : y = 7299 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7299 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7300
                ·
                  have y_eq : y = 7300 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7300 j rest z root_eq
                ·
                  have y_eq : y = 7301 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7301 j rest z root_eq
          ·
            by_cases y_left : y ≤ 7304
            ·
              by_cases y_left : y ≤ 7302
              ·
                have y_eq : y = 7302 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7302 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7303
                ·
                  have y_eq : y = 7303 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7303 j rest z root_eq
                ·
                  have y_eq : y = 7304 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7304 j rest z root_eq
            ·
              by_cases y_left : y ≤ 7306
              ·
                by_cases y_left : y ≤ 7305
                ·
                  have y_eq : y = 7305 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7305 j rest z root_eq
                ·
                  have y_eq : y = 7306 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7306 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7307
                ·
                  have y_eq : y = 7307 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7307 j rest z root_eq
                ·
                  have y_eq : y = 7308 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7308 j rest z root_eq
  ·
    by_cases y_left : y ≤ 8123
    ·
      by_cases y_left : y ≤ 8098
      ·
        by_cases y_left : y ≤ 7323
        ·
          by_cases y_left : y ≤ 7314
          ·
            by_cases y_left : y ≤ 7311
            ·
              by_cases y_left : y ≤ 7309
              ·
                have y_eq : y = 7309 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7309 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7310
                ·
                  have y_eq : y = 7310 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7310 j rest z root_eq
                ·
                  have y_eq : y = 7311 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7311 j rest z root_eq
            ·
              by_cases y_left : y ≤ 7312
              ·
                exact False.elim (firstBZeroTail_false_203_7312_7312 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7313
                ·
                  have y_eq : y = 7313 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7313 j rest z root_eq
                ·
                  have y_eq : y = 7314 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7314 j rest z root_eq
          ·
            by_cases y_left : y ≤ 7318
            ·
              by_cases y_left : y ≤ 7316
              ·
                exact False.elim (firstBZeroTail_false_203_7315_7316 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7317
                ·
                  have y_eq : y = 7317 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7317 j rest z root_eq
                ·
                  have y_eq : y = 7318 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7318 j rest z root_eq
            ·
              by_cases y_left : y ≤ 7321
              ·
                exact False.elim (firstBZeroTail_false_203_7319_7321 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7322
                ·
                  have y_eq : y = 7322 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7322 j rest z root_eq
                ·
                  have y_eq : y = 7323 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7323 j rest z root_eq
        ·
          by_cases y_left : y ≤ 7397
          ·
            by_cases y_left : y ≤ 7332
            ·
              by_cases y_left : y ≤ 7330
              ·
                exact False.elim (firstBZeroTail_false_203_7324_7330 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7331
                ·
                  have y_eq : y = 7331 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7331 j rest z root_eq
                ·
                  have y_eq : y = 7332 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7332 j rest z root_eq
            ·
              by_cases y_left : y ≤ 7348
              ·
                exact False.elim (firstBZeroTail_false_203_7333_7348 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 7349
                ·
                  have y_eq : y = 7349 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7349 j rest z root_eq
                ·
                  exact False.elim (firstBZeroTail_false_203_7350_7397 j rest y z (by omega) (by
                    omega) root_eq)
          ·
            by_cases y_left : y ≤ 8094
            ·
              by_cases y_left : y ≤ 7398
              ·
                have y_eq : y = 7398 := by omega
                subst y
                exact firstBZeroTail_candidate_203_7398 j rest z root_eq
              ·
                by_cases y_left : y ≤ 7399
                ·
                  have y_eq : y = 7399 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_7399 j rest z root_eq
                ·
                  exact False.elim (firstBZeroTail_false_203_7400_8094 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 8096
              ·
                by_cases y_left : y ≤ 8095
                ·
                  have y_eq : y = 8095 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8095 j rest z root_eq
                ·
                  have y_eq : y = 8096 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8096 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8097
                ·
                  have y_eq : y = 8097 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8097 j rest z root_eq
                ·
                  have y_eq : y = 8098 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8098 j rest z root_eq
      ·
        by_cases y_left : y ≤ 8110
        ·
          by_cases y_left : y ≤ 8104
          ·
            by_cases y_left : y ≤ 8101
            ·
              by_cases y_left : y ≤ 8099
              ·
                have y_eq : y = 8099 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8099 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8100
                ·
                  have y_eq : y = 8100 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8100 j rest z root_eq
                ·
                  have y_eq : y = 8101 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8101 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8102
              ·
                have y_eq : y = 8102 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8102 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8103
                ·
                  have y_eq : y = 8103 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8103 j rest z root_eq
                ·
                  have y_eq : y = 8104 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8104 j rest z root_eq
          ·
            by_cases y_left : y ≤ 8107
            ·
              by_cases y_left : y ≤ 8105
              ·
                have y_eq : y = 8105 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8105 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8106
                ·
                  have y_eq : y = 8106 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8106 j rest z root_eq
                ·
                  have y_eq : y = 8107 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8107 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8108
              ·
                have y_eq : y = 8108 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8108 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8109
                ·
                  have y_eq : y = 8109 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8109 j rest z root_eq
                ·
                  have y_eq : y = 8110 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8110 j rest z root_eq
        ·
          by_cases y_left : y ≤ 8116
          ·
            by_cases y_left : y ≤ 8113
            ·
              by_cases y_left : y ≤ 8111
              ·
                have y_eq : y = 8111 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8111 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8112
                ·
                  have y_eq : y = 8112 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8112 j rest z root_eq
                ·
                  have y_eq : y = 8113 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8113 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8114
              ·
                have y_eq : y = 8114 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8114 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8115
                ·
                  have y_eq : y = 8115 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8115 j rest z root_eq
                ·
                  have y_eq : y = 8116 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8116 j rest z root_eq
          ·
            by_cases y_left : y ≤ 8119
            ·
              by_cases y_left : y ≤ 8117
              ·
                have y_eq : y = 8117 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8117 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8118
                ·
                  have y_eq : y = 8118 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8118 j rest z root_eq
                ·
                  have y_eq : y = 8119 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8119 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8121
              ·
                by_cases y_left : y ≤ 8120
                ·
                  have y_eq : y = 8120 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8120 j rest z root_eq
                ·
                  have y_eq : y = 8121 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8121 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8122
                ·
                  have y_eq : y = 8122 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8122 j rest z root_eq
                ·
                  have y_eq : y = 8123 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8123 j rest z root_eq
    ·
      by_cases y_left : y ≤ 8166
      ·
        by_cases y_left : y ≤ 8139
        ·
          by_cases y_left : y ≤ 8129
          ·
            by_cases y_left : y ≤ 8126
            ·
              by_cases y_left : y ≤ 8124
              ·
                have y_eq : y = 8124 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8124 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8125
                ·
                  have y_eq : y = 8125 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8125 j rest z root_eq
                ·
                  have y_eq : y = 8126 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8126 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8127
              ·
                have y_eq : y = 8127 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8127 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8128
                ·
                  exact False.elim (firstBZeroTail_false_203_8128_8128 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  have y_eq : y = 8129 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8129 j rest z root_eq
          ·
            by_cases y_left : y ≤ 8132
            ·
              by_cases y_left : y ≤ 8130
              ·
                have y_eq : y = 8130 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8130 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8131
                ·
                  have y_eq : y = 8131 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8131 j rest z root_eq
                ·
                  have y_eq : y = 8132 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8132 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8133
              ·
                have y_eq : y = 8133 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8133 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8134
                ·
                  have y_eq : y = 8134 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8134 j rest z root_eq
                ·
                  exact False.elim (firstBZeroTail_false_203_8135_8139 j rest y z (by omega) (by
                    omega) root_eq)
        ·
          by_cases y_left : y ≤ 8145
          ·
            by_cases y_left : y ≤ 8142
            ·
              by_cases y_left : y ≤ 8140
              ·
                have y_eq : y = 8140 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8140 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8141
                ·
                  have y_eq : y = 8141 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8141 j rest z root_eq
                ·
                  have y_eq : y = 8142 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8142 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8143
              ·
                have y_eq : y = 8143 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8143 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8144
                ·
                  have y_eq : y = 8144 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8144 j rest z root_eq
                ·
                  have y_eq : y = 8145 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8145 j rest z root_eq
          ·
            by_cases y_left : y ≤ 8162
            ·
              by_cases y_left : y ≤ 8160
              ·
                exact False.elim (firstBZeroTail_false_203_8146_8160 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 8161
                ·
                  have y_eq : y = 8161 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8161 j rest z root_eq
                ·
                  have y_eq : y = 8162 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8162 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8164
              ·
                by_cases y_left : y ≤ 8163
                ·
                  have y_eq : y = 8163 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8163 j rest z root_eq
                ·
                  have y_eq : y = 8164 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8164 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8165
                ·
                  have y_eq : y = 8165 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8165 j rest z root_eq
                ·
                  have y_eq : y = 8166 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8166 j rest z root_eq
      ·
        by_cases y_left : y ≤ 8383
        ·
          by_cases y_left : y ≤ 8226
          ·
            by_cases y_left : y ≤ 8223
            ·
              by_cases y_left : y ≤ 8221
              ·
                exact False.elim (firstBZeroTail_false_203_8167_8221 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 8222
                ·
                  have y_eq : y = 8222 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8222 j rest z root_eq
                ·
                  have y_eq : y = 8223 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8223 j rest z root_eq
            ·
              by_cases y_left : y ≤ 8224
              ·
                have y_eq : y = 8224 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8224 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8225
                ·
                  have y_eq : y = 8225 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8225 j rest z root_eq
                ·
                  have y_eq : y = 8226 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8226 j rest z root_eq
          ·
            by_cases y_left : y ≤ 8232
            ·
              by_cases y_left : y ≤ 8227
              ·
                have y_eq : y = 8227 := by omega
                subst y
                exact firstBZeroTail_candidate_203_8227 j rest z root_eq
              ·
                by_cases y_left : y ≤ 8228
                ·
                  exact False.elim (firstBZeroTail_false_203_8228_8228 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_8229_8232 j rest y z (by omega) (by
                    omega) root_eq)
            ·
              by_cases y_left : y ≤ 8278
              ·
                by_cases y_left : y ≤ 8243
                ·
                  exact False.elim (firstBZeroTail_false_203_8233_8243 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  exact False.elim (firstBZeroTail_false_203_8244_8278 j rest y z (by omega) (by
                    omega) root_eq)
              ·
                by_cases y_left : y ≤ 8382
                ·
                  exact False.elim (firstBZeroTail_false_203_8279_8382 j rest y z (by omega) (by
                    omega) root_eq)
                ·
                  have y_eq : y = 8383 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8383 j rest z root_eq
        ·
          by_cases y_left : y ≤ 9873
          ·
            by_cases y_left : y ≤ 8714
            ·
              by_cases y_left : y ≤ 8712
              ·
                exact False.elim (firstBZeroTail_false_203_8384_8712 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 8713
                ·
                  have y_eq : y = 8713 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8713 j rest z root_eq
                ·
                  have y_eq : y = 8714 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_8714 j rest z root_eq
            ·
              by_cases y_left : y ≤ 9871
              ·
                exact False.elim (firstBZeroTail_false_203_8715_9871 j rest y z (by omega) (by
                  omega) root_eq)
              ·
                by_cases y_left : y ≤ 9872
                ·
                  have y_eq : y = 9872 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_9872 j rest z root_eq
                ·
                  have y_eq : y = 9873 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_9873 j rest z root_eq
          ·
            by_cases y_left : y ≤ 9876
            ·
              by_cases y_left : y ≤ 9874
              ·
                have y_eq : y = 9874 := by omega
                subst y
                exact firstBZeroTail_candidate_203_9874 j rest z root_eq
              ·
                by_cases y_left : y ≤ 9875
                ·
                  have y_eq : y = 9875 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_9875 j rest z root_eq
                ·
                  have y_eq : y = 9876 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_9876 j rest z root_eq
            ·
              by_cases y_left : y ≤ 9878
              ·
                by_cases y_left : y ≤ 9877
                ·
                  have y_eq : y = 9877 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_9877 j rest z root_eq
                ·
                  have y_eq : y = 9878 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_9878 j rest z root_eq
              ·
                by_cases y_left : y ≤ 9879
                ·
                  have y_eq : y = 9879 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_9879 j rest z root_eq
                ·
                  have y_eq : y = 9880 := by omega
                  subst y
                  exact firstBZeroTail_candidate_203_9880 j rest z root_eq

end MatrixMortality.ParabolicBlade
