import MatrixMortality.ParabolicFirstBZeroCore

/-!
# Leading-`b` suffix certificate shard 16

This file is generated by
`scripts/generate-parabolic-first-b-zero-suffix.py`.
-/

namespace MatrixMortality.ParabolicBlade

private abbrev SCore := FirstBOneOuterSuffixCore
private abbrev killN := firstBOneOuterSuffixCore_false_of_nonpositive
private abbrev killG := firstBOneOuterSuffixCore_false_of_global
private abbrev killK := firstBOneOuterSuffixCore_false_of_gap
private abbrev kill0 := firstBOneOuterSuffixCore_false_of_nil
private abbrev stepB := firstBOneOuterSuffixCore_cons_b
private abbrev stepC := firstBOneOuterSuffixCore_cons_c
private abbrev hRoot := firstBZeroSuffixH
private abbrev aRoot := firstBZeroScaleCoefficient
private abbrev corr := firstBOneOuterCorrection
private abbrev qRoot := firstBOneOuterQ
private abbrev jRoot := firstBOneOuterJ

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8103_49_49
    (body : List TagLetter) (z : Nat) (z_lower : 49 ≤ z)
    (z_upper : z ≤ 49)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8103 z)
      (firstBOneOuterJ 203 8103 z)
      (firstBOneOuterCorrection 203 8103 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8103 z
  let J : ℤ := jRoot 203 8103 z
  let B : ℤ := corr 203 8103 z
  change SCore body H_root J B at core
  have z_lower_int : (49 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 49 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_b J B
              · intro equality
                norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_b
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_bb : ℤ := 243 * H_b - 39 * J
                  have core_bb : SCore tail2 H_bb J B := by
                    dsimp [H_bb]
                    exact stepB tail2 H_b J B core_b
                  apply killN tail2 H_bb J B
                    J_positive B_positive
                  · norm_num [H_bb, H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_bb
              | c =>
                  let H_bc : ℤ := 3 * H_b
                  have core_bc : SCore tail2 H_bc J B := by
                    dsimp [H_bc]
                    exact stepC tail2 H_b J B core_b
                  cases tail2 with
                  | nil =>
                      apply kill0 H_bc J B
                      · intro equality
                        norm_num [H_bc, H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_bc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_bcb : ℤ := 243 * H_bc - 39 * J
                          have core_bcb : SCore tail3 H_bcb J B := by
                            dsimp [H_bcb]
                            exact stepB tail3 H_bc J B core_bc
                          apply killN tail3 H_bcb J B
                            J_positive B_positive
                          · norm_num [H_bcb, H_bc, H_b, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_bcb
                      | c =>
                          let H_bcc : ℤ := 3 * H_bc
                          have core_bcc : SCore tail3 H_bcc J B := by
                            dsimp [H_bcc]
                            exact stepC tail3 H_bc J B core_bc
                          cases tail3 with
                          | nil =>
                              apply kill0 H_bcc J B
                              · intro equality
                                norm_num [H_bcc, H_bc, H_b, B, J, H_root, hRoot, aRoot, corr, qRoot,
                                  jRoot] at equality
                                nlinarith
                              · exact core_bcc
                          | cons letter tail4 =>
                              cases letter with
                              | b =>
                                  let H_bccb : ℤ := 243 * H_bcc - 39 * J
                                  have core_bccb : SCore tail4 H_bccb J B := by
                                    dsimp [H_bccb]
                                    exact stepB tail4 H_bcc J B core_bcc
                                  apply killN tail4 H_bccb J B
                                    J_positive B_positive
                                  · norm_num [H_bccb, H_bcc, H_bc, H_b, B, J, H_root, hRoot, aRoot,
                                    corr, qRoot, jRoot]
                                    nlinarith
                                  · exact core_bccb
                              | c =>
                                  let H_bccc : ℤ := 3 * H_bcc
                                  have core_bccc : SCore tail4 H_bccc J B := by
                                    dsimp [H_bccc]
                                    exact stepC tail4 H_bcc J B core_bcc
                                  cases tail4 with
                                  | nil =>
                                      apply kill0 H_bccc J B
                                      · intro equality
                                        norm_num [H_bccc, H_bcc, H_bc, H_b, B, J, H_root, hRoot,
                                          aRoot, corr, qRoot, jRoot] at equality
                                        nlinarith
                                      · exact core_bccc
                                  | cons letter tail5 =>
                                      cases letter with
                                      | b =>
                                          let H_bcccb : ℤ := 243 * H_bccc - 39 * J
                                          have core_bcccb : SCore tail5 H_bcccb J B := by
                                            dsimp [H_bcccb]
                                            exact stepB tail5 H_bccc J B core_bccc
                                          apply killN tail5 H_bcccb J B
                                            J_positive B_positive
                                          · norm_num [H_bcccb, H_bccc, H_bcc, H_bc, H_b, B, J,
                                            H_root, hRoot, aRoot, corr, qRoot, jRoot]
                                            nlinarith
                                          · exact core_bcccb
                                      | c =>
                                          let H_bcccc : ℤ := 3 * H_bccc
                                          have core_bcccc : SCore tail5 H_bcccc J B := by
                                            dsimp [H_bcccc]
                                            exact stepC tail5 H_bccc J B core_bccc
                                          cases tail5 with
                                          | nil =>
                                              apply kill0 H_bcccc J B
                                              · intro equality
                                                norm_num [H_bcccc, H_bccc, H_bcc, H_bc, H_b, B, J,
                                                  H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                                                  equality
                                                nlinarith
                                              · exact core_bcccc
                                          | cons letter tail6 =>
                                              cases letter with
                                              | b =>
                                                  let H_bccccb : ℤ := 243 * H_bcccc - 39 * J
                                                  have core_bccccb : SCore tail6 H_bccccb J B := by
                                                    dsimp [H_bccccb]
                                                    exact stepB tail6 H_bcccc J B core_bcccc
                                                  apply killN tail6 H_bccccb J B
                                                    J_positive B_positive
                                                  · norm_num [H_bccccb, H_bcccc, H_bccc, H_bcc,
                                                    H_bc, H_b, B, J, H_root, hRoot, aRoot, corr,
                                                    qRoot, jRoot]
                                                    nlinarith
                                                  · exact core_bccccb
                                              | c =>
                                                  let H_bccccc : ℤ := 3 * H_bcccc
                                                  have core_bccccc : SCore tail6 H_bccccc J B := by
                                                    dsimp [H_bccccc]
                                                    exact stepC tail6 H_bcccc J B core_bcccc
                                                  cases tail6 with
                                                  | nil =>
                                                      apply kill0 H_bccccc J B
                                                      · intro equality
                                                        norm_num [H_bccccc, H_bcccc, H_bccc, H_bcc,
                                                          H_bc, H_b, B, J, H_root, hRoot, aRoot,
                                                          corr, qRoot, jRoot] at equality
                                                        nlinarith
                                                      · exact core_bccccc
                                                  | cons letter tail7 =>
                                                      cases letter with
                                                      | b =>
                                                          let H_bcccccb : ℤ := 243 * H_bccccc - 39 *
                                                            J
                                                          have core_bcccccb : SCore tail7 H_bcccccb
                                                            J B := by
                                                            dsimp [H_bcccccb]
                                                            exact stepB tail7 H_bccccc J B
                                                              core_bccccc
                                                          apply killG tail7 H_bcccccb J B
                                                            J_positive B_positive
                                                          · norm_num [H_bcccccb, H_bccccc, H_bcccc,
                                                            H_bccc, H_bcc, H_bc, H_b, B, J, H_root,
                                                            hRoot, aRoot, corr, qRoot, jRoot]
                                                            nlinarith
                                                          · exact core_bcccccb
                                                      | c =>
                                                          let H_bcccccc : ℤ := 3 * H_bccccc
                                                          have core_bcccccc : SCore tail7 H_bcccccc
                                                            J B := by
                                                            dsimp [H_bcccccc]
                                                            exact stepC tail7 H_bccccc J B
                                                              core_bccccc
                                                          apply killG tail7 H_bcccccc J B
                                                            J_positive B_positive
                                                          · norm_num [H_bcccccc, H_bccccc, H_bcccc,
                                                            H_bccc, H_bcc, H_bc, H_b, B, J, H_root,
                                                            hRoot, aRoot, corr, qRoot, jRoot]
                                                            nlinarith
                                                          · exact core_bcccccc
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8103_50_63
    (body : List TagLetter) (z : Nat) (z_lower : 50 ≤ z)
    (z_upper : z ≤ 63)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8103 z)
      (firstBOneOuterJ 203 8103 z)
      (firstBOneOuterCorrection 203 8103 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8103 z
  let J : ℤ := jRoot 203 8103 z
  let B : ℤ := corr 203 8103 z
  change SCore body H_root J B at core
  have z_lower_int : (50 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 63 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8104_15_15
    (body : List TagLetter) (z : Nat) (z_lower : 15 ≤ z)
    (z_upper : z ≤ 15)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8104 z)
      (firstBOneOuterJ 203 8104 z)
      (firstBOneOuterCorrection 203 8104 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8104 z
  let J : ℤ := jRoot 203 8104 z
  let B : ℤ := corr 203 8104 z
  change SCore body H_root J B at core
  have z_lower_int : (15 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 15 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  cases tail2 with
                  | nil =>
                      apply kill0 H_cc J B
                      · intro equality
                        norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at
                          equality
                        nlinarith
                      · exact core_cc
                  | cons letter tail3 =>
                      cases letter with
                      | b =>
                          let H_ccb : ℤ := 243 * H_cc - 39 * J
                          have core_ccb : SCore tail3 H_ccb J B := by
                            dsimp [H_ccb]
                            exact stepB tail3 H_cc J B core_cc
                          apply killN tail3 H_ccb J B
                            J_positive B_positive
                          · norm_num [H_ccb, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                            jRoot]
                            nlinarith
                          · exact core_ccb
                      | c =>
                          let H_ccc : ℤ := 3 * H_cc
                          have core_ccc : SCore tail3 H_ccc J B := by
                            dsimp [H_ccc]
                            exact stepC tail3 H_cc J B core_cc
                          cases tail3 with
                          | nil =>
                              apply kill0 H_ccc J B
                              · intro equality
                                norm_num [H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot,
                                  jRoot] at equality
                                nlinarith
                              · exact core_ccc
                          | cons letter tail4 =>
                              cases letter with
                              | b =>
                                  let H_cccb : ℤ := 243 * H_ccc - 39 * J
                                  have core_cccb : SCore tail4 H_cccb J B := by
                                    dsimp [H_cccb]
                                    exact stepB tail4 H_ccc J B core_ccc
                                  apply killG tail4 H_cccb J B
                                    J_positive B_positive
                                  · norm_num [H_cccb, H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                    corr, qRoot, jRoot]
                                    nlinarith
                                  · exact core_cccb
                              | c =>
                                  let H_cccc : ℤ := 3 * H_ccc
                                  have core_cccc : SCore tail4 H_cccc J B := by
                                    dsimp [H_cccc]
                                    exact stepC tail4 H_ccc J B core_ccc
                                  apply killG tail4 H_cccc J B
                                    J_positive B_positive
                                  · norm_num [H_cccc, H_ccc, H_cc, H_c, B, J, H_root, hRoot, aRoot,
                                    corr, qRoot, jRoot]
                                    nlinarith
                                  · exact core_cccc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8104_16_18
    (body : List TagLetter) (z : Nat) (z_lower : 16 ≤ z)
    (z_upper : z ≤ 18)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8104 z)
      (firstBOneOuterJ 203 8104 z)
      (firstBOneOuterCorrection 203 8104 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8104 z
  let J : ℤ := jRoot 203 8104 z
  let B : ℤ := corr 203 8104 z
  change SCore body H_root J B at core
  have z_lower_int : (16 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 18 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killG tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8104_19_36
    (body : List TagLetter) (z : Nat) (z_lower : 19 ≤ z)
    (z_upper : z ≤ 36)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8104 z)
      (firstBOneOuterJ 203 8104 z)
      (firstBOneOuterCorrection 203 8104 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8104 z
  let J : ℤ := jRoot 203 8104 z
  let B : ℤ := corr 203 8104 z
  change SCore body H_root J B at core
  have z_lower_int : (19 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 36 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8104_37_43
    (body : List TagLetter) (z : Nat) (z_lower : 37 ≤ z)
    (z_upper : z ≤ 43)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8104 z)
      (firstBOneOuterJ 203 8104 z)
      (firstBOneOuterCorrection 203 8104 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8104 z
  let J : ℤ := jRoot 203 8104 z
  let B : ℤ := corr 203 8104 z
  change SCore body H_root J B at core
  have z_lower_int : (37 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 43 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8105_14_14
    (body : List TagLetter) (z : Nat) (z_lower : 14 ≤ z)
    (z_upper : z ≤ 14)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8105 z)
      (firstBOneOuterJ 203 8105 z)
      (firstBOneOuterCorrection 203 8105 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8105 z
  let J : ℤ := jRoot 203 8105 z
  let B : ℤ := corr 203 8105 z
  change SCore body H_root J B at core
  have z_lower_int : (14 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 14 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killK 1 tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8105_15_16
    (body : List TagLetter) (z : Nat) (z_lower : 15 ≤ z)
    (z_upper : z ≤ 16)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8105 z)
      (firstBOneOuterJ 203 8105 z)
      (firstBOneOuterCorrection 203 8105 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8105 z
  let J : ℤ := jRoot 203 8105 z
  let B : ℤ := corr 203 8105 z
  change SCore body H_root J B at core
  have z_lower_int : (15 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 16 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killK 0 tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8105_17_28
    (body : List TagLetter) (z : Nat) (z_lower : 17 ≤ z)
    (z_upper : z ≤ 28)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8105 z)
      (firstBOneOuterJ 203 8105 z)
      (firstBOneOuterCorrection 203 8105 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8105 z
  let J : ℤ := jRoot 203 8105 z
  let B : ℤ := corr 203 8105 z
  change SCore body H_root J B at core
  have z_lower_int : (17 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 28 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8105_29_32
    (body : List TagLetter) (z : Nat) (z_lower : 29 ≤ z)
    (z_upper : z ≤ 32)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8105 z)
      (firstBOneOuterJ 203 8105 z)
      (firstBOneOuterCorrection 203 8105 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8105 z
  let J : ℤ := jRoot 203 8105 z
  let B : ℤ := corr 203 8105 z
  change SCore body H_root J B at core
  have z_lower_int : (29 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 32 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8106_13_14
    (body : List TagLetter) (z : Nat) (z_lower : 13 ≤ z)
    (z_upper : z ≤ 14)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8106 z)
      (firstBOneOuterJ 203 8106 z)
      (firstBOneOuterCorrection 203 8106 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8106 z
  let J : ℤ := jRoot 203 8106 z
  let B : ℤ := corr 203 8106 z
  change SCore body H_root J B at core
  have z_lower_int : (13 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 14 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killK 0 tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8106_15_23
    (body : List TagLetter) (z : Nat) (z_lower : 15 ≤ z)
    (z_upper : z ≤ 23)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8106 z)
      (firstBOneOuterJ 203 8106 z)
      (firstBOneOuterCorrection 203 8106 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8106 z
  let J : ℤ := jRoot 203 8106 z
  let B : ℤ := corr 203 8106 z
  change SCore body H_root J B at core
  have z_lower_int : (15 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 23 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8106_24_26
    (body : List TagLetter) (z : Nat) (z_lower : 24 ≤ z)
    (z_upper : z ≤ 26)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8106 z)
      (firstBOneOuterJ 203 8106 z)
      (firstBOneOuterCorrection 203 8106 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8106 z
  let J : ℤ := jRoot 203 8106 z
  let B : ℤ := corr 203 8106 z
  change SCore body H_root J B at core
  have z_lower_int : (24 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 26 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8107_12_12
    (body : List TagLetter) (z : Nat) (z_lower : 12 ≤ z)
    (z_upper : z ≤ 12)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8107 z)
      (firstBOneOuterJ 203 8107 z)
      (firstBOneOuterCorrection 203 8107 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8107 z
  let J : ℤ := jRoot 203 8107 z
  let B : ℤ := corr 203 8107 z
  change SCore body H_root J B at core
  have z_lower_int : (12 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 12 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killK 0 tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8107_13_13
    (body : List TagLetter) (z : Nat) (z_lower : 13 ≤ z)
    (z_upper : z ≤ 13)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8107 z)
      (firstBOneOuterJ 203 8107 z)
      (firstBOneOuterCorrection 203 8107 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8107 z
  let J : ℤ := jRoot 203 8107 z
  let B : ℤ := corr 203 8107 z
  change SCore body H_root J B at core
  have z_lower_int : (13 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 13 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killK 0 tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killG tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8107_14_20
    (body : List TagLetter) (z : Nat) (z_lower : 14 ≤ z)
    (z_upper : z ≤ 20)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8107 z)
      (firstBOneOuterJ 203 8107 z)
      (firstBOneOuterCorrection 203 8107 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8107 z
  let J : ℤ := jRoot 203 8107 z
  let B : ℤ := corr 203 8107 z
  change SCore body H_root J B at core
  have z_lower_int : (14 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 20 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  apply killK 0 body H_root J B
    J_positive B_positive
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
    nlinarith
  · exact core

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8107_21_22
    (body : List TagLetter) (z : Nat) (z_lower : 21 ≤ z)
    (z_upper : z ≤ 22)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8107 z)
      (firstBOneOuterJ 203 8107 z)
      (firstBOneOuterCorrection 203 8107 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8107 z
  let J : ℤ := jRoot 203 8107 z
  let B : ℤ := corr 203 8107 z
  change SCore body H_root J B at core
  have z_lower_int : (21 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 22 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8108_11_11
    (body : List TagLetter) (z : Nat) (z_lower : 11 ≤ z)
    (z_upper : z ≤ 11)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8108 z)
      (firstBOneOuterJ 203 8108 z)
      (firstBOneOuterCorrection 203 8108 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8108 z
  let J : ℤ := jRoot 203 8108 z
  let B : ℤ := corr 203 8108 z
  change SCore body H_root J B at core
  have z_lower_int : (11 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 11 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killK 0 tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8108_12_17
    (body : List TagLetter) (z : Nat) (z_lower : 12 ≤ z)
    (z_upper : z ≤ 17)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8108 z)
      (firstBOneOuterJ 203 8108 z)
      (firstBOneOuterCorrection 203 8108 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8108 z
  let J : ℤ := jRoot 203 8108 z
  let B : ℤ := corr 203 8108 z
  change SCore body H_root J B at core
  have z_lower_int : (12 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 17 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killG tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killG tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8108_18_19
    (body : List TagLetter) (z : Nat) (z_lower : 18 ≤ z)
    (z_upper : z ≤ 19)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8108 z)
      (firstBOneOuterJ 203 8108 z)
      (firstBOneOuterCorrection 203 8108 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8108 z
  let J : ℤ := jRoot 203 8108 z
  let B : ℤ := corr 203 8108 z
  change SCore body H_root J B at core
  have z_lower_int : (18 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 19 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killG tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          apply killG tail1 H_c J B
            J_positive B_positive
          · norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_c

/-- Kernel-rechecked suffix extinction on one generated inner-wait interval. -/
theorem firstBZeroSuffix_false_203_0_8109_10_10
    (body : List TagLetter) (z : Nat) (z_lower : 10 ≤ z)
    (z_upper : z ≤ 10)
    (core : FirstBOneOuterSuffixCore body
      (firstBZeroSuffixH 0 203 8109 z)
      (firstBOneOuterJ 203 8109 z)
      (firstBOneOuterCorrection 203 8109 z)) : False := by
  let H_root : ℤ := hRoot 0 203 8109 z
  let J : ℤ := jRoot 203 8109 z
  let B : ℤ := corr 203 8109 z
  change SCore body H_root J B at core
  have z_lower_int : (10 : ℤ) ≤ z := by exact_mod_cast z_lower
  have z_upper_int : (z : ℤ) ≤ 10 := by exact_mod_cast z_upper
  have J_positive : (0 : ℤ) < J := by
    dsimp [J]
    unfold jRoot
    positivity
  have B_positive : (0 : ℤ) < B := by
    dsimp [B]
    unfold corr qRoot
    positivity
  cases body with
  | nil =>
      apply kill0 H_root J B
      · intro equality
        norm_num [B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
        nlinarith
      · exact core
  | cons letter tail1 =>
      cases letter with
      | b =>
          let H_b : ℤ := 243 * H_root - 39 * J
          have core_b : SCore tail1 H_b J B := by
            dsimp [H_b]
            exact stepB tail1 H_root J B core
          apply killN tail1 H_b J B
            J_positive B_positive
          · norm_num [H_b, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
            nlinarith
          · exact core_b
      | c =>
          let H_c : ℤ := 3 * H_root
          have core_c : SCore tail1 H_c J B := by
            dsimp [H_c]
            exact stepC tail1 H_root J B core
          cases tail1 with
          | nil =>
              apply kill0 H_c J B
              · intro equality
                norm_num [H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot] at equality
                nlinarith
              · exact core_c
          | cons letter tail2 =>
              cases letter with
              | b =>
                  let H_cb : ℤ := 243 * H_c - 39 * J
                  have core_cb : SCore tail2 H_cb J B := by
                    dsimp [H_cb]
                    exact stepB tail2 H_c J B core_c
                  apply killN tail2 H_cb J B
                    J_positive B_positive
                  · norm_num [H_cb, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cb
              | c =>
                  let H_cc : ℤ := 3 * H_c
                  have core_cc : SCore tail2 H_cc J B := by
                    dsimp [H_cc]
                    exact stepC tail2 H_c J B core_c
                  apply killG tail2 H_cc J B
                    J_positive B_positive
                  · norm_num [H_cc, H_c, B, J, H_root, hRoot, aRoot, corr, qRoot, jRoot]
                    nlinarith
                  · exact core_cc

end MatrixMortality.ParabolicBlade
