import MatrixMortality.ReturnGuardQuotientCompleteness

/-!
# Classification of drift-divisor quotient certificates

When a finite quotient prime divides the drift numerator, every guarded residual transfer has
rank one.  The resulting affine survivor shell is invariant exactly when the center numerator
avoids the finite power orbit of the scaled base.  For a primitive divisor this orbit is the
cyclic subgroup generated by the base, expressed in homogeneous coordinates.

The criterion is finite and executable.  It also subsumes the terminal-denominator side
condition: the zero residue belongs to the orbit, so avoidance already forces the terminal
denominator to survive.
-/

namespace MatrixMortality.ReturnGuard

noncomputable section

/-- The scaled base-power orbit in one exact-order quotient. -/
def centerPowerOrbit
    (factor prime period : Nat) [Fact factor.Prime] (scale : ℤ) :
    Finset (ZMod factor) :=
  Finset.univ.image fun residue : Fin period =>
    (scale : ZMod factor) * (prime : ZMod factor) ^ (residue : Nat)

theorem mem_centerPowerOrbit_iff
    {factor prime period : Nat} [Fact factor.Prime]
    {scale : ℤ} {value : ZMod factor} :
    value ∈ centerPowerOrbit factor prime period scale ↔
      ∃ residue : Fin period,
        value =
          (scale : ZMod factor) *
            (prime : ZMod factor) ^ (residue : Nat) := by
  simp only [centerPowerOrbit, Finset.mem_image, Finset.mem_univ, true_and]
  constructor
  · rintro ⟨residue, equality⟩
    exact ⟨residue, equality.symm⟩
  · rintro ⟨residue, equality⟩
    exact ⟨residue, equality.symm⟩

/-- Avoiding the finite power orbit is exactly the residue-by-residue condition used by the
rank-one survivor certificate. -/
theorem not_mem_centerPowerOrbit_iff
    {factor prime period : Nat} [Fact factor.Prime]
    {centerNumerator scale : ℤ} :
    (centerNumerator : ZMod factor) ∉
        centerPowerOrbit factor prime period scale ↔
      ∀ residue : Fin period,
        (centerNumerator : ZMod factor) -
            (scale : ZMod factor) *
              (prime : ZMod factor) ^ (residue : Nat) ≠ 0 := by
  constructor
  · intro avoids residue equality
    apply avoids
    exact mem_centerPowerOrbit_iff.mpr
      ⟨residue, sub_eq_zero.mp equality⟩
  · intro every orbit_mem
    obtain ⟨residue, equality⟩ :=
      mem_centerPowerOrbit_iff.mp orbit_mem
    exact every residue (sub_eq_zero.mpr equality)

/-- Power-orbit avoidance already forces the terminal denominator to survive. -/
theorem terminal_denominator_ne_of_not_mem_centerPowerOrbit
    {factor prime period : Nat} [Fact factor.Prime]
    {centerNumerator scale : ℤ}
    (period_positive : 0 < period)
    (avoids :
      (centerNumerator : ZMod factor) ∉
        centerPowerOrbit factor prime period scale) :
    (centerNumerator : ZMod factor) - (scale : ZMod factor) ≠ 0 := by
  rw [not_mem_centerPowerOrbit_iff] at avoids
  simpa using avoids ⟨0, period_positive⟩

/-- A drift-zero terminal state is never a nonzero affine ray, whether its denominator
survives or collapses modulo the quotient factor. -/
theorem quotientPairState_driftZero_terminal_not_mem_affineSurvivors
    {factor : Nat} [Fact factor.Prime]
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0) :
    quotientPairState factor
        (-driftNumerator, centerNumerator - scale) ∉
      AffineSurvivors factor := by
  by_cases terminal_denominator_ne :
      (centerNumerator : ZMod factor) - (scale : ZMod factor) ≠ 0
  · exact quotientPairState_terminal_not_mem_affineSurvivors
      drift_zero terminal_denominator_ne
  · simp only [ne_eq, not_not] at terminal_denominator_ne
    simp [AffineSurvivors, quotientPairState, quotientPoint,
      ProjectiveLine.ofPair, terminal_denominator_ne]

/-- If the center lies on the scaled power orbit, closure from the reset forces either
quotient annihilation or the drift-zero terminal state in one transition. -/
theorem quotientInvariant_orbit_hit_forces_cancelled_or_terminal
    {factor prime period depth : Nat} [Fact factor.Prime]
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0)
    {states : Set (QuotientState (ZMod factor))}
    (closed :
      QuotientInvariant factor prime period depth
        centerNumerator driftNumerator scale states)
    (reset_mem :
      quotientPairState factor ((1 : ℤ), (1 : ℤ)) ∈ states)
    (orbit_mem :
      (centerNumerator : ZMod factor) ∈
        centerPowerOrbit factor prime period scale) :
    none ∈ states ∨
      quotientPairState factor
          (-driftNumerator, centerNumerator - scale) ∈ states := by
  obtain ⟨residue, center_eq⟩ :=
    mem_centerPowerOrbit_iff.mp orbit_mem
  have source_eq :
      quotientPairState factor ((1 : ℤ), (1 : ℤ)) =
        some (some 1) := by
    simp [quotientPairState, quotientPoint, ProjectiveLine.ofPair]
  rw [source_eq] at reset_mem
  have image_mem := closed _ reset_mem residue
  let bottom : ZMod factor :=
    (prime : ZMod factor) ^ (depth * (residue : Nat)) *
      ((centerNumerator : ZMod factor) - (scale : ZMod factor))
  have transfer_eq :
      quotientTransfer factor prime depth centerNumerator
          driftNumerator scale residue =
        !![(0 : ZMod factor), 0; bottom, 0] := by
    rw [quotientTransfer_eq_firstColumn_of_drift_zero residue drift_zero]
    simp only [center_eq, sub_self, bottom]
  rw [transfer_eq] at image_mem
  by_cases bottom_zero : bottom = 0
  · left
    have transition_cancelled :
        quotientTransition
            !![(0 : ZMod factor), 0; bottom, 0]
            (some (some 1)) = none := by
      apply quotientTransition_point_of_image_eq_zero
      rw [bottom_zero]
      ext i
      fin_cases i <;>
        simp [ProjectiveLine.ray, Matrix.mulVec, dotProduct,
          Fin.sum_univ_succ]
    rwa [transition_cancelled] at image_mem
  · right
    have column_ne : ![(0 : ZMod factor), bottom] ≠ 0 := by
      intro column_zero
      exact bottom_zero (by simpa using congrFun column_zero 1)
    rw [quotientTransition_firstColumn 0 bottom 1 column_ne one_ne_zero] at image_mem
    have terminal_denominator_ne :
        (centerNumerator : ZMod factor) - (scale : ZMod factor) ≠ 0 := by
      intro denominator_zero
      apply bottom_zero
      simp [bottom, denominator_zero]
    have terminal_eq :
        quotientPairState factor
            (-driftNumerator, centerNumerator - scale) =
          some (some 0) := by
      simp [quotientPairState, quotientPoint, ProjectiveLine.ofPair,
        drift_zero, terminal_denominator_ne]
    change some (ProjectiveLine.ofPair 0 bottom) ∈ states at image_mem
    have point_eq : ProjectiveLine.ofPair 0 bottom = some 0 := by
      simp [ProjectiveLine.ofPair, bottom_zero]
    rwa [point_eq, ← terminal_eq] at image_mem

/-- When the drift vanishes, the raw terminal state is annihilated at residue zero even if its
integral coordinates collapse simultaneously modulo the quotient factor. -/
theorem quotientTransition_zero_driftZero_terminal_eq_cancelled
    {factor prime depth : Nat} [Fact factor.Prime]
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0) :
    quotientTransition
        (quotientTransfer factor prime depth
          centerNumerator driftNumerator scale 0)
        (quotientPairState factor
          (-driftNumerator, centerNumerator - scale)) = none := by
  apply quotientTransition_point_of_image_eq_zero
  rw [quotientTransfer_zero]
  by_cases denominator_zero :
      (centerNumerator : ZMod factor) - (scale : ZMod factor) = 0
  · ext i
    fin_cases i <;>
      simp [quotientPoint, ProjectiveLine.ofPair,
        ProjectiveLine.ray, Matrix.mulVec, dotProduct,
        Fin.sum_univ_succ, drift_zero, denominator_zero]
  · ext i
    fin_cases i <;>
      simp [quotientPoint, ProjectiveLine.ofPair,
        ProjectiveLine.ray, Matrix.mulVec, dotProduct,
        Fin.sum_univ_succ, drift_zero, denominator_zero]

/-- Orbit membership forces annihilation, possibly through the terminal ray as one
intermediate state. -/
theorem quotientInvariant_orbit_hit_forces_cancelled
    {factor prime period depth : Nat} [Fact factor.Prime]
    (period_positive : 0 < period)
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0)
    {states : Set (QuotientState (ZMod factor))}
    (closed :
      QuotientInvariant factor prime period depth
        centerNumerator driftNumerator scale states)
    (reset_mem :
      quotientPairState factor ((1 : ℤ), (1 : ℤ)) ∈ states)
    (orbit_mem :
      (centerNumerator : ZMod factor) ∈
        centerPowerOrbit factor prime period scale) :
    none ∈ states := by
  rcases quotientInvariant_orbit_hit_forces_cancelled_or_terminal
      drift_zero closed reset_mem orbit_mem with cancelled | terminal
  · exact cancelled
  · have image_mem := closed _ terminal ⟨0, period_positive⟩
    rwa [quotientTransition_zero_driftZero_terminal_eq_cancelled
      drift_zero] at image_mem

/-- For a drift-zero primitive quotient, the nonzero affine shell is invariant if and only if
the center avoids the finite scaled power orbit.  This is an exact classification of this
certificate architecture, not merely a sufficient condition. -/
theorem affineSurvivors_quotientInvariant_iff_centerPowerOrbit_avoids
    {factor prime period depth : Nat} [Fact factor.Prime]
    (primitive : IsPrimitivePrimeDivisor factor prime period)
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0) :
    QuotientInvariant factor prime period depth
        centerNumerator driftNumerator scale (AffineSurvivors factor) ↔
      (centerNumerator : ZMod factor) ∉
        centerPowerOrbit factor prime period scale := by
  constructor
  · intro invariant orbit_mem
    rcases quotientInvariant_orbit_hit_forces_cancelled_or_terminal
        drift_zero invariant
        (quotientPairState_one_mem_affineSurvivors factor) orbit_mem with
      cancelled | terminal
    · simp [AffineSurvivors] at cancelled
    · exact
        (quotientPairState_driftZero_terminal_not_mem_affineSurvivors
          drift_zero) terminal
  · intro avoids
    have base_ne : (prime : ZMod factor) ≠ 0 := by
      intro base_zero
      have factor_dvd_prime : factor ∣ prime :=
        (ZMod.natCast_eq_zero_iff prime factor).mp base_zero
      exact primitivePrimeDivisor_not_dvd_base_int primitive
        (by exact_mod_cast factor_dvd_prime)
    exact affineSurvivors_quotientInvariant drift_zero base_ne
      (terminal_denominator_ne_of_not_mem_centerPowerOrbit
        primitive.exponent_positive avoids)
      (not_mem_centerPowerOrbit_iff.mp avoids)

/-- At a primitive drift divisor, cancellation-free invariant existence is exactly scaled
power-orbit avoidance. -/
theorem hasCancellationFreeInvariant_iff_centerPowerOrbit_avoids
    {factor prime period depth : Nat} [Fact factor.Prime]
    (primitive : IsPrimitivePrimeDivisor factor prime period)
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0) :
    HasCancellationFreeInvariant factor prime period depth
        centerNumerator driftNumerator scale ((1 : ℤ), (1 : ℤ)) ↔
      (centerNumerator : ZMod factor) ∉
        centerPowerOrbit factor prime period scale := by
  constructor
  · rintro ⟨states, closed, cancelled_absent, reset_mem⟩ orbit_mem
    exact cancelled_absent
      (quotientInvariant_orbit_hit_forces_cancelled
        primitive.exponent_positive drift_zero closed reset_mem orbit_mem)
  · intro avoids
    exact ⟨
      AffineSurvivors factor,
      (affineSurvivors_quotientInvariant_iff_centerPowerOrbit_avoids
        primitive drift_zero).mpr avoids,
      by simp [AffineSurvivors],
      quotientPairState_one_mem_affineSurvivors factor⟩

/-- Orbit avoidance exactly classifies all safe quotient invariants at a primitive drift
divisor.  If one residue hits the center, closure forces either annihilation or the terminal
zero ray immediately from the reset; no smaller invariant can evade the failure. -/
theorem hasQuotientCertificate_iff_centerPowerOrbit_avoids
    {factor prime period depth : Nat} [Fact factor.Prime]
    (primitive : IsPrimitivePrimeDivisor factor prime period)
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0) :
    HasQuotientCertificate factor prime period depth
        centerNumerator driftNumerator scale
        ((1 : ℤ), (1 : ℤ))
        (-driftNumerator, centerNumerator - scale) ↔
      (centerNumerator : ZMod factor) ∉
        centerPowerOrbit factor prime period scale := by
  constructor
  · rintro ⟨states, closed, cancelled_absent, reset_mem, terminal_absent⟩
      orbit_mem
    rcases quotientInvariant_orbit_hit_forces_cancelled_or_terminal
        drift_zero closed reset_mem orbit_mem with cancelled | terminal
    · exact cancelled_absent cancelled
    · exact terminal_absent terminal
  · intro avoids
    refine ⟨AffineSurvivors factor,
      (affineSurvivors_quotientInvariant_iff_centerPowerOrbit_avoids
        primitive drift_zero).mpr avoids,
      by simp [AffineSurvivors],
      quotientPairState_one_mem_affineSurvivors factor, ?_⟩
    exact quotientPairState_terminal_not_mem_affineSurvivors drift_zero
      (terminal_denominator_ne_of_not_mem_centerPowerOrbit
        primitive.exponent_positive avoids)

/-- The finite power orbit is the cyclic subgroup generated by the base after dividing out a
nonzero scale. -/
theorem mem_centerPowerOrbit_iff_centerRatio_mem_zpowers
    {factor prime period : Nat} [Fact factor.Prime]
    (primitive : IsPrimitivePrimeDivisor factor prime period)
    {centerNumerator scale : ℤ}
    (center_ne : (centerNumerator : ZMod factor) ≠ 0)
    (scale_ne : (scale : ZMod factor) ≠ 0) :
    (centerNumerator : ZMod factor) ∈
        centerPowerOrbit factor prime period scale ↔
      Units.mk0
          ((centerNumerator : ZMod factor) / (scale : ZMod factor))
          (div_ne_zero center_ne scale_ne) ∈
        Subgroup.zpowers
          (ZMod.unitOfCoprime prime primitive.base_coprime) := by
  rw [mem_centerPowerOrbit_iff,
    mem_zpowers_iff_mem_range_orderOf,
    primitive.unit_orderOf_eq_exponent]
  simp only [Finset.mem_image, Finset.mem_range]
  constructor
  · rintro ⟨residue, center_eq⟩
    refine ⟨residue, residue.isLt, ?_⟩
    apply Units.ext
    change
      (prime : ZMod factor) ^ (residue : Nat) =
        (centerNumerator : ZMod factor) / (scale : ZMod factor)
    apply (eq_div_iff scale_ne).2
    simpa [mul_comm] using center_eq.symm
  · rintro ⟨power, power_lt, power_eq⟩
    refine ⟨⟨power, power_lt⟩, ?_⟩
    have value_eq := congrArg Units.val power_eq
    change
      (prime : ZMod factor) ^ power =
        (centerNumerator : ZMod factor) / (scale : ZMod factor) at value_eq
    have multiplied := (eq_div_iff scale_ne).1 value_eq
    simpa [mul_comm] using multiplied.symm

/-- A nonzero scaling preserves all `period` distinct powers of a primitive base. -/
theorem card_centerPowerOrbit
    {factor prime period : Nat} [Fact factor.Prime]
    (primitive : IsPrimitivePrimeDivisor factor prime period)
    {scale : ℤ} (scale_ne : (scale : ZMod factor) ≠ 0) :
    (centerPowerOrbit factor prime period scale).card = period := by
  have injective :
      Set.InjOn
        (fun residue : Fin period =>
          (scale : ZMod factor) *
            (prime : ZMod factor) ^ (residue : Nat))
        (Finset.univ : Finset (Fin period)) := by
    intro left _ right _ equality
    have power_eq :
        (prime : ZMod factor) ^ (left : Nat) =
          (prime : ZMod factor) ^ (right : Nat) :=
      mul_left_cancel₀ scale_ne equality
    let baseUnit :=
      ZMod.unitOfCoprime prime primitive.base_coprime
    have unit_power_eq :
        baseUnit ^ (left : Nat) = baseUnit ^ (right : Nat) := by
      apply Units.ext
      exact power_eq
    have residue_eq_order :
        (left : Nat) % orderOf baseUnit =
          (right : Nat) % orderOf baseUnit :=
      pow_inj_mod.mp unit_power_eq
    have residue_eq :
        (left : Nat) % period = (right : Nat) % period := by
      simpa [baseUnit, primitive.unit_orderOf_eq_exponent] using
        residue_eq_order
    rw [Nat.mod_eq_of_lt left.isLt, Nat.mod_eq_of_lt right.isLt] at residue_eq
    exact Fin.ext residue_eq
  calc
    (centerPowerOrbit factor prime period scale).card =
        (Finset.univ : Finset (Fin period)).card := by
      exact Finset.card_image_iff.mpr injective
    _ = period := Fintype.card_fin period

/-- Exactly `factor - period` center residues pass the drift-divisor test when the scale
survives. -/
theorem card_certifyingCenters
    {factor prime period : Nat} [Fact factor.Prime]
    (primitive : IsPrimitivePrimeDivisor factor prime period)
    {scale : ℤ} (scale_ne : (scale : ZMod factor) ≠ 0) :
    ((Finset.univ : Finset (ZMod factor)) \
        centerPowerOrbit factor prime period scale).card =
      factor - period := by
  rw [Finset.card_sdiff]
  simp [card_centerPowerOrbit primitive scale_ne]

/-- Executable finite test for the drift-divisor certificate. -/
def driftDivisorCertifies
    (factor prime period : Nat) [Fact factor.Prime]
    (centerNumerator scale : ℤ) : Bool :=
  decide
    ((centerNumerator : ZMod factor) ∉
      centerPowerOrbit factor prime period scale)

@[simp]
theorem driftDivisorCertifies_eq_true_iff
    {factor prime period : Nat} [Fact factor.Prime]
    {centerNumerator scale : ℤ} :
    driftDivisorCertifies factor prime period centerNumerator scale = true ↔
      (centerNumerator : ZMod factor) ∉
        centerPowerOrbit factor prime period scale := by
  simp [driftDivisorCertifies]

/-- The Boolean test decides cancellation-free invariant existence at a primitive drift
divisor. -/
theorem hasCancellationFreeInvariant_iff_driftDivisorCertifies
    {factor prime period depth : Nat} [Fact factor.Prime]
    (primitive : IsPrimitivePrimeDivisor factor prime period)
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0) :
    HasCancellationFreeInvariant factor prime period depth
        centerNumerator driftNumerator scale ((1 : ℤ), (1 : ℤ)) ↔
      driftDivisorCertifies factor prime period
        centerNumerator scale = true :=
  (hasCancellationFreeInvariant_iff_centerPowerOrbit_avoids
    primitive drift_zero).trans driftDivisorCertifies_eq_true_iff.symm

/-- The Boolean test decides existence of every safe invariant in the drift-zero quotient, not
only the canonical affine shell. -/
theorem hasQuotientCertificate_iff_driftDivisorCertifies
    {factor prime period depth : Nat} [Fact factor.Prime]
    (primitive : IsPrimitivePrimeDivisor factor prime period)
    {centerNumerator driftNumerator scale : ℤ}
    (drift_zero : (driftNumerator : ZMod factor) = 0) :
    HasQuotientCertificate factor prime period depth
        centerNumerator driftNumerator scale
        ((1 : ℤ), (1 : ℤ))
        (-driftNumerator, centerNumerator - scale) ↔
      driftDivisorCertifies factor prime period
        centerNumerator scale = true :=
  (hasQuotientCertificate_iff_centerPowerOrbit_avoids
    primitive drift_zero).trans driftDivisorCertifies_eq_true_iff.symm

/-- A successful finite drift-divisor test is a physical immortality certificate. -/
theorem not_physical_isMortal_of_driftDivisorCertifies
    (parameters : Parameters)
    {centerNumerator driftNumerator scale : ℤ}
    (center_eq :
      parameters.center = (centerNumerator : ℚ) / scale)
    (drift_eq :
      drift parameters.center parameters.reset =
        (driftNumerator : ℚ) / scale)
    (scale_ne : scale ≠ 0)
    {factor period : Nat} [Fact factor.Prime]
    (primitive :
      IsPrimitivePrimeDivisor factor parameters.prime period)
    (drift_zero : (driftNumerator : ZMod factor) = 0)
    (certifies :
      driftDivisorCertifies factor parameters.prime period
        centerNumerator scale = true) :
    ¬IsMortal
      (ReturnFamily.pairGenerator
        (ambient (parameters.prime : ℚ) parameters.depth)
        (cut parameters.center parameters.reset)) := by
  obtain ⟨states, closed, cancelled_absent, reset_mem⟩ :=
    (hasCancellationFreeInvariant_iff_driftDivisorCertifies
      primitive drift_zero).mpr certifies
  apply not_physical_isMortal_of_cancellationFreeQuotient parameters
    center_eq drift_eq scale_ne primitive closed cancelled_absent
  simpa [rationalPair] using reset_mem

end
end MatrixMortality.ReturnGuard
