import Frankl.CertificateObjective

namespace Frankl

/-- Coordinate whose first-order error contribution is currently larger. -/
def preferHorizontalSplit (terms fuel bits : ℕ) (rectangle : RatRectangle)
    (expression : EntropyExpr) : Bool :=
  match evaluateDual terms fuel bits rectangle expression with
  | some dual =>
      match dual.gradient with
      | some gradient =>
          gradient.2.absUpper * rectangle.vertical.radius ≤
            gradient.1.absUpper * rectangle.horizontal.radius
      | none => rectangle.vertical.radius ≤ rectangle.horizontal.radius
  | none => rectangle.vertical.radius ≤ rectangle.horizontal.radius

/-- A deterministic reflected subdivision. Each successful terminal is rechecked by
`certifySubdivision`; this generator only chooses the proof tree. -/
def adaptiveSubdivision (terms fuel bits : ℕ) (allowCorners : Bool)
    (rectangle : RatRectangle) (expression : EntropyExpr) : ℕ → Subdivision
  | 0 => .leaf .interval
  | depth + 1 =>
      match certifyLeaf terms fuel bits .interval rectangle expression with
      | some _ => .leaf .interval
      | none =>
          if allowCorners then
            match certifyLeaf terms fuel bits .zeroCorner rectangle expression with
            | some _ => .leaf .zeroCorner
            | none =>
                match certifyLeaf terms fuel bits .oneCorner rectangle expression with
                | some _ => .leaf .oneCorner
                | none => split depth
          else
            split depth
where
  /-- Bisect the preferred coordinate and recursively construct both children. -/
  split (depth : ℕ) : Subdivision :=
    if preferHorizontalSplit terms fuel bits rectangle expression then
      let cut := rectangle.horizontal.center
      .horizontal cut
        (adaptiveSubdivision terms fuel bits allowCorners
          (rectangle.lowerHorizontal cut) expression depth)
        (adaptiveSubdivision terms fuel bits allowCorners
          (rectangle.upperHorizontal cut) expression depth)
    else
      let cut := rectangle.vertical.center
      .vertical cut
        (adaptiveSubdivision terms fuel bits allowCorners
          (rectangle.lowerVertical cut) expression depth)
        (adaptiveSubdivision terms fuel bits allowCorners
          (rectangle.upperVertical cut) expression depth)

/-- Direct reflected adjudication of the adaptive subdivision. This is extensionally the tree
checker below, but it avoids constructing and then traversing the same tree a second time. -/
def certifyAdaptive (terms fuel bits : ℕ) (allowCorners : Bool)
    (rectangle : RatRectangle) (expression : EntropyExpr) : ℕ → Option Unit
  | 0 => certifyLeaf terms fuel bits .interval rectangle expression
  | depth + 1 =>
      match certifyLeaf terms fuel bits .interval rectangle expression with
      | some _ => some ()
      | none =>
          if allowCorners then
            match certifyLeaf terms fuel bits .zeroCorner rectangle expression with
            | some _ => some ()
            | none =>
                match certifyLeaf terms fuel bits .oneCorner rectangle expression with
                | some _ => some ()
                | none => split depth
          else
            split depth
where
  /-- Bisect the preferred coordinate and directly adjudicate both children. -/
  split (depth : ℕ) : Option Unit :=
    if preferHorizontalSplit terms fuel bits rectangle expression then
      let cut := rectangle.horizontal.center
      do
        let _ ← certifyAdaptive terms fuel bits allowCorners
          (rectangle.lowerHorizontal cut) expression depth
        certifyAdaptive terms fuel bits allowCorners
          (rectangle.upperHorizontal cut) expression depth
    else
      let cut := rectangle.vertical.center
      do
        let _ ← certifyAdaptive terms fuel bits allowCorners
          (rectangle.lowerVertical cut) expression depth
        certifyAdaptive terms fuel bits allowCorners
          (rectangle.upperVertical cut) expression depth

/-- The direct adaptive adjudicator checks exactly the subdivision generated by
`adaptiveSubdivision`. -/
theorem certifyAdaptive_eq_subdivision (terms fuel bits : ℕ) (allowCorners : Bool)
    (rectangle : RatRectangle) (expression : EntropyExpr) (depth : ℕ)
    (hhorizontalRadius : 0 ≤ rectangle.horizontal.radius)
    (hverticalRadius : 0 ≤ rectangle.vertical.radius) :
    certifyAdaptive terms fuel bits allowCorners rectangle expression depth =
      certifySubdivision terms fuel bits rectangle expression
        (adaptiveSubdivision terms fuel bits allowCorners rectangle expression depth) := by
  induction depth generalizing rectangle with
  | zero => simp [certifyAdaptive, adaptiveSubdivision, certifySubdivision]
  | succ depth ih =>
    have hhorizontalCut :
        rectangle.horizontal.lower ≤ rectangle.horizontal.center ∧
          rectangle.horizontal.center ≤ rectangle.horizontal.upper := by
      dsimp [RatBall.lower, RatBall.upper]
      exact ⟨by linarith, by linarith⟩
    have hverticalCut :
        rectangle.vertical.lower ≤ rectangle.vertical.center ∧
          rectangle.vertical.center ≤ rectangle.vertical.upper := by
      dsimp [RatBall.lower, RatBall.upper]
      exact ⟨by linarith, by linarith⟩
    rw [certifyAdaptive, adaptiveSubdivision]
    cases hinterval : certifyLeaf terms fuel bits .interval rectangle expression with
    | some intervalWitness =>
      cases intervalWitness
      simp [hinterval, certifySubdivision]
    | none =>
      simp only
      cases allowCorners with
      | false =>
        simp only [Bool.false_eq_true, if_false]
        unfold certifyAdaptive.split adaptiveSubdivision.split
        cases hcoordinate : preferHorizontalSplit terms fuel bits rectangle expression <;>
          simp only [hcoordinate, Bool.false_eq_true, if_false, if_true]
        · simp only [certifySubdivision, hverticalCut, and_self, if_true]
          rw [ih (rectangle.upperVertical rectangle.vertical.center) hhorizontalRadius
              (RatBall.upperAt_radius_nonnegative hverticalCut.2),
            ih (rectangle.lowerVertical rectangle.vertical.center) hhorizontalRadius
              (RatBall.lowerAt_radius_nonnegative hverticalCut.1)]
        · simp only [certifySubdivision, hhorizontalCut, and_self, if_true]
          rw [ih (rectangle.upperHorizontal rectangle.horizontal.center)
              (RatBall.upperAt_radius_nonnegative hhorizontalCut.2) hverticalRadius,
            ih (rectangle.lowerHorizontal rectangle.horizontal.center)
              (RatBall.lowerAt_radius_nonnegative hhorizontalCut.1) hverticalRadius]
      | true =>
        simp only [if_true]
        cases hzero : certifyLeaf terms fuel bits .zeroCorner rectangle expression with
        | some zeroWitness =>
          cases zeroWitness
          simp [hzero, certifySubdivision]
        | none =>
          simp only
          cases hone : certifyLeaf terms fuel bits .oneCorner rectangle expression with
          | some oneWitness =>
            cases oneWitness
            simp [hone, certifySubdivision]
          | none =>
            simp only
            unfold certifyAdaptive.split adaptiveSubdivision.split
            cases hcoordinate : preferHorizontalSplit terms fuel bits rectangle expression <;>
              simp only [hcoordinate, Bool.false_eq_true, if_false, if_true]
            · simp only [certifySubdivision, hverticalCut, and_self, if_true]
              rw [ih (rectangle.upperVertical rectangle.vertical.center) hhorizontalRadius
                  (RatBall.upperAt_radius_nonnegative hverticalCut.2),
                ih (rectangle.lowerVertical rectangle.vertical.center) hhorizontalRadius
                  (RatBall.lowerAt_radius_nonnegative hverticalCut.1)]
            · simp only [certifySubdivision, hhorizontalCut, and_self, if_true]
              rw [ih (rectangle.upperHorizontal rectangle.horizontal.center)
                  (RatBall.upperAt_radius_nonnegative hhorizontalCut.2) hverticalRadius,
                ih (rectangle.lowerHorizontal rectangle.horizontal.center)
                  (RatBall.lowerAt_radius_nonnegative hhorizontalCut.1) hverticalRadius]

/-- Apply increasing vertical seed cuts, then adaptively certify every resulting band. -/
def seededVerticalSubdivision (terms fuel bits depth : ℕ) (allowCorners : Bool)
    (rectangle : RatRectangle) (expression : EntropyExpr) : List ℚ → Subdivision
  | [] => adaptiveSubdivision terms fuel bits allowCorners rectangle expression depth
  | cut :: cuts =>
      .vertical cut
        (adaptiveSubdivision terms fuel bits allowCorners
          (rectangle.lowerVertical cut) expression depth)
        (seededVerticalSubdivision terms fuel bits depth allowCorners
          (rectangle.upperVertical cut) expression cuts)

/-- Apply increasing horizontal seed cuts and the same vertical seed partition in every
resulting strip. -/
def seededGridSubdivision (terms fuel bits depth : ℕ) (allowCorners : Bool)
    (rectangle : RatRectangle) (expression : EntropyExpr) (verticalCuts : List ℚ) :
    List ℚ → Subdivision
  | [] =>
      seededVerticalSubdivision terms fuel bits depth allowCorners rectangle expression
        verticalCuts
  | cut :: cuts =>
      .horizontal cut
        (seededVerticalSubdivision terms fuel bits depth allowCorners
          (rectangle.lowerHorizontal cut) expression verticalCuts)
        (seededGridSubdivision terms fuel bits depth allowCorners
          (rectangle.upperHorizontal cut) expression verticalCuts cuts)

/-- Direct adjudication of a vertically seeded adaptive partition. -/
def certifySeededVertical (terms fuel bits depth : ℕ) (allowCorners : Bool)
    (rectangle : RatRectangle) (expression : EntropyExpr) : List ℚ → Option Unit
  | [] => certifyAdaptive terms fuel bits allowCorners rectangle expression depth
  | cut :: cuts =>
      if rectangle.vertical.lower ≤ cut ∧ cut ≤ rectangle.vertical.upper then do
        let _ ← certifyAdaptive terms fuel bits allowCorners
          (rectangle.lowerVertical cut) expression depth
        certifySeededVertical terms fuel bits depth allowCorners
          (rectangle.upperVertical cut) expression cuts
      else none

/-- Direct adjudication of a rectangular seeded adaptive partition. -/
def certifySeededGrid (terms fuel bits depth : ℕ) (allowCorners : Bool)
    (rectangle : RatRectangle) (expression : EntropyExpr) (verticalCuts : List ℚ) :
    List ℚ → Option Unit
  | [] =>
      certifySeededVertical terms fuel bits depth allowCorners rectangle expression verticalCuts
  | cut :: cuts =>
      if rectangle.horizontal.lower ≤ cut ∧ cut ≤ rectangle.horizontal.upper then do
        let _ ← certifySeededVertical terms fuel bits depth allowCorners
          (rectangle.lowerHorizontal cut) expression verticalCuts
        certifySeededGrid terms fuel bits depth allowCorners
          (rectangle.upperHorizontal cut) expression verticalCuts cuts
      else none

/-- Direct vertical adjudication equals the corresponding generated-tree check. -/
theorem certifySeededVertical_eq_subdivision (terms fuel bits depth : ℕ)
    (allowCorners : Bool) (rectangle : RatRectangle) (expression : EntropyExpr)
    (cuts : List ℚ) (hhorizontalRadius : 0 ≤ rectangle.horizontal.radius)
    (hverticalRadius : 0 ≤ rectangle.vertical.radius) :
    certifySeededVertical terms fuel bits depth allowCorners rectangle expression cuts =
      certifySubdivision terms fuel bits rectangle expression
        (seededVerticalSubdivision terms fuel bits depth allowCorners rectangle expression
          cuts) := by
  induction cuts generalizing rectangle with
  | nil =>
    exact certifyAdaptive_eq_subdivision terms fuel bits allowCorners rectangle expression depth
      hhorizontalRadius hverticalRadius
  | cons cut cuts ih =>
    unfold certifySeededVertical seededVerticalSubdivision certifySubdivision
    by_cases hcut : rectangle.vertical.lower ≤ cut ∧ cut ≤ rectangle.vertical.upper
    · simp only [hcut, if_true]
      rw [certifyAdaptive_eq_subdivision terms fuel bits allowCorners
          (rectangle.lowerVertical cut) expression depth hhorizontalRadius
          (RatBall.lowerAt_radius_nonnegative hcut.1),
        ih (rectangle.upperVertical cut) hhorizontalRadius
          (RatBall.upperAt_radius_nonnegative hcut.2)]
    · simp [hcut]

/-- Direct grid adjudication equals the corresponding generated-tree check. -/
theorem certifySeededGrid_eq_subdivision (terms fuel bits depth : ℕ)
    (allowCorners : Bool) (rectangle : RatRectangle) (expression : EntropyExpr)
    (verticalCuts horizontalCuts : List ℚ)
    (hhorizontalRadius : 0 ≤ rectangle.horizontal.radius)
    (hverticalRadius : 0 ≤ rectangle.vertical.radius) :
    certifySeededGrid terms fuel bits depth allowCorners rectangle expression
        verticalCuts horizontalCuts =
      certifySubdivision terms fuel bits rectangle expression
        (seededGridSubdivision terms fuel bits depth allowCorners rectangle expression
          verticalCuts horizontalCuts) := by
  induction horizontalCuts generalizing rectangle with
  | nil =>
    exact certifySeededVertical_eq_subdivision terms fuel bits depth allowCorners rectangle
      expression verticalCuts hhorizontalRadius hverticalRadius
  | cons cut cuts ih =>
    unfold certifySeededGrid seededGridSubdivision certifySubdivision
    by_cases hcut : rectangle.horizontal.lower ≤ cut ∧ cut ≤ rectangle.horizontal.upper
    · simp only [hcut, if_true]
      rw [certifySeededVertical_eq_subdivision terms fuel bits depth allowCorners
          (rectangle.lowerHorizontal cut) expression verticalCuts
          (RatBall.lowerAt_radius_nonnegative hcut.1) hverticalRadius,
        ih (rectangle.upperHorizontal cut)
          (RatBall.upperAt_radius_nonnegative hcut.2) hverticalRadius]
    · simp [hcut]

/-- The endpoint certificate rectangle `0 ≤ a ≤ t, 0 ≤ q ≤ 1`. -/
def endpointRectangle : RatRectangle :=
  ⟨RatBall.ofBounds 0 (19099 / 50000), RatBall.ofBounds 0 1⟩

/-- The lower diagonal certificate rectangle `0 ≤ w ≤ 2t, 0 ≤ d ≤ 1`. -/
def lowerRegionRectangle : RatRectangle :=
  ⟨RatBall.ofBounds 0 (19099 / 25000), RatBall.ofBounds 0 1⟩

/-- The upper diagonal certificate rectangle `2t ≤ w ≤ 1, 0 ≤ d ≤ 1`. -/
def upperRegionRectangle : RatRectangle :=
  ⟨RatBall.ofBounds (19099 / 25000) 1, RatBall.ofBounds 0 1⟩

/-- Endpoint-orbit coordinate cuts. -/
def endpointVerticalCuts : List ℚ :=
  [1 / 1000, 1 / 20, 1 / 8, 1 / 4, 1 / 2, 3 / 4, 999 / 1000]

/-- Low-diagonal coordinate cuts for the endpoint objective. -/
def endpointHorizontalCuts : List ℚ := [1 / 1000, 1 / 20, 1 / 8, 1 / 4]

/-- Displacement cuts shared by the two diagonal objectives. -/
def diagonalVerticalCuts : List ℚ := [1 / 8, 1 / 4, 1 / 2]

/-- Upper-weight cuts in the lower diagonal region. -/
def lowerRegionHorizontalCuts : List ℚ := [1 / 8, 1 / 4, 1 / 2]

/-- Upper-weight cuts in the upper diagonal region. -/
def upperRegionHorizontalCuts : List ℚ := [4 / 5, 7 / 8]

/-- Seeded endpoint tree. The seed isolates its two entropy-zero corners and major analytic
regimes; all fine cuts remain autonomous. -/
def endpointSubdivision (terms fuel bits depth : ℕ) : Subdivision :=
  seededGridSubdivision terms fuel bits depth true endpointRectangle
    CertificateObjective.endpointExpression
    endpointVerticalCuts endpointHorizontalCuts

/-- Seeded lower-diagonal tree. -/
def lowerRegionSubdivision (terms fuel bits depth : ℕ) : Subdivision :=
  seededGridSubdivision terms fuel bits depth false lowerRegionRectangle
    CertificateObjective.lowerRegionExpression
    diagonalVerticalCuts lowerRegionHorizontalCuts

/-- Seeded upper-diagonal tree. -/
def upperRegionSubdivision (terms fuel bits depth : ℕ) : Subdivision :=
  seededGridSubdivision terms fuel bits depth false upperRegionRectangle
    CertificateObjective.upperRegionExpression
    diagonalVerticalCuts upperRegionHorizontalCuts

/-- Direct endpoint certificate. -/
def certifyEndpoint (terms fuel bits depth : ℕ) : Option Unit :=
  certifySeededGrid terms fuel bits depth true endpointRectangle
    CertificateObjective.endpointExpression endpointVerticalCuts endpointHorizontalCuts

/-- Direct lower-diagonal certificate. -/
def certifyLowerRegion (terms fuel bits depth : ℕ) : Option Unit :=
  certifySeededGrid terms fuel bits depth false lowerRegionRectangle
    CertificateObjective.lowerRegionExpression diagonalVerticalCuts lowerRegionHorizontalCuts

/-- Direct upper-diagonal certificate. -/
def certifyUpperRegion (terms fuel bits depth : ℕ) : Option Unit :=
  certifySeededGrid terms fuel bits depth false upperRegionRectangle
    CertificateObjective.upperRegionExpression diagonalVerticalCuts upperRegionHorizontalCuts

theorem certifyEndpoint_eq_subdivision (terms fuel bits depth : ℕ) :
    certifyEndpoint terms fuel bits depth =
      certifySubdivision terms fuel bits endpointRectangle
        CertificateObjective.endpointExpression (endpointSubdivision terms fuel bits depth) := by
  apply certifySeededGrid_eq_subdivision
  all_goals norm_num [endpointRectangle, RatBall.ofBounds]

theorem certifyLowerRegion_eq_subdivision (terms fuel bits depth : ℕ) :
    certifyLowerRegion terms fuel bits depth =
      certifySubdivision terms fuel bits lowerRegionRectangle
        CertificateObjective.lowerRegionExpression
        (lowerRegionSubdivision terms fuel bits depth) := by
  apply certifySeededGrid_eq_subdivision
  all_goals norm_num [lowerRegionRectangle, RatBall.ofBounds]

theorem certifyUpperRegion_eq_subdivision (terms fuel bits depth : ℕ) :
    certifyUpperRegion terms fuel bits depth =
      certifySubdivision terms fuel bits upperRegionRectangle
        CertificateObjective.upperRegionExpression
        (upperRegionSubdivision terms fuel bits depth) := by
  apply certifySeededGrid_eq_subdivision
  all_goals norm_num [upperRegionRectangle, RatBall.ofBounds]

end Frankl
